### ISSUE TITLE
Subscription SubLevel incorrect default value

### ISSUE THREAD

**Issue by brianpaulcarpenter** [dsuch/pymqi#10]
I may have found a nasty gotcha in pymqi.

The SD class in pymqi sets the default SubLevel to 0, however according to IBM the default value is in fact 1.

http://publib.boulder.ibm.com/infocenter/wmqv7/v7r0/index.jsp?topic=%2Fcom.ibm.mq.amqnar.doc%2Fps20005_.htm

_To ensure the interceptor receives the messages before any other subscribers, make sure it has the highest subscription level of all subscribers by using the SubLevel field in the MQSD. By default, subscribers have a SubLevel of 1._

Another developer (coding in Java using JMS) started subscribing to the same topic as me (in python with pymqi) and suddenly I stopped receiving messages published to the topic.  Strangely we noticed that he did receive them.  We used mqexplorer to examine the differences in our subscriptions and saw that his SubLevel was 1 and mine was 0.  That got us to the page above.

_You can have a subscriber with a SubLevel of value 0 that serves as a catchall if no other subscriber is interested in the message. This configuration can be useful because you can monitor the messages this subscriber receives and check why no other subscribers received it and whether it is correct that it not be received by anyone else._

So I think that once he subscribed with SubLevel of 1, I stopped receiving the messages because I was no longer the only subscriber interested in the message per the above.  He didn’t explicitly set the SubLevel to 1, it was done by default from the JMS libraries.  Once I explicitly set my SubLevel to 1 we both received messages published to the topic.

Maybe you could correct the default value, might save others some hair pulling?

**Comment by dsuch** [comment]
Thank you for investigating it @brianpaulcarpenter - will definitely have a look at it and issue a new release once it's updated!

**Comment by drychlik76** [comment]
@brianpaulcarpenter @dsuch Hello gentlemen.  I have run into this exact same issue and have been trying to figure this out.  How exactly did Brian implement this SubLevel value to 1?
I tried it like this.

` 
sub_desc = pymqi.SD()
sub_desc["SubLevel"] = 1
sub_desc["Options"] = pymqi.CMQC.MQSO_CREATE + pymqi.CMQC.MQSO_RESUME + pymqi.CMQC.MQSO_DURABLE + pymqi.CMQC.MQSO_MANAGED`

This appears to not be correct.  Thank you in advance for any direction.

**Comment by brianpaulcarpenter** [comment]
What I do is pumping

**Comment by brianpaulcarpenter** [comment]
What 
I d

**Comment by brianpaulcarpenter** [comment]
Try pymqi.SD(SubLevel=1)

**Comment by drychlik76** [comment]
@brianpaulcarpenter I had to have the admin delete my subscription from web sphere, once he did that and I re-subscribe back to the topic it started working.  Hopefully this help someone else in the future.  Thanks Brian for your help.

**Comment by dsuch** [comment]
Closing - thanks for input everyone!
