### ISSUE TITLE
Failing to get strings from Queue getting unreadable byte data 

### ISSUE THREAD

**Issue by Kayt** [dsuch/pymqi#100]
I am connecting to Equation banking system using MQ and interacting with it using pymqi, i am able to send data to MQ however when trying to get the response from the queue i am getting the data as a bytes format i am failing to pass. Is there any way to retrieve the data as a readable string

**Comment by dsuch** [comment]
Hello @Kayt,

you need to send in sample code that reproduces the situation along with information what exact data you receive and what precisely you would like to receive instead.

Otherwise, it is quite impossible to investigate it further.

Thanks.

**Comment by Kayt** [comment]
thanks for the swift response please find the code below:
`import pymqi`

`queue_manager = "APP.QUEUE.MANAGER"`
`channel = "SYSTEM.DEF.SVRCONN"`
`host = "x.x.x.x"`
`port = "1414"`
`queue_name = "APP.RESP.QUEUE"`


`conn_info = "%s(%s)" % (host, port)`

`qmgr = pymqi.connect(queue_manager, channel, conn_info,'mqm','mqm')`
`queue = pymqi.Queue(qmgr, queue_name)`
`md = pymqi.MD()`
`md.Format = pymqi.CMQC.MQFMT_STRING`
 
`message = queue.get(None, md)`

and the returned result was:
`b'\xc1\xc3K\xd9\xc5\xe2\xd7K\xd8\xe4\xc5\xe4\xc5@@@@@@@@@@@@@@@@@@@\xc5\xd8\xe4\xc1\xe3\xc9\xd6\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xd6\xe3\xc3\xe7@@@@@@@@@@@@@@@@@@@@@@@@\xd4\xc5\xd9\xc9\xc4\xc9\xc1\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xc1\xc1\xd1\xc5\xc5\xf2\xf3\xf0\xf6\xf0\xf3\xf0\xf6\xf2\xf3\xf7\xf2@@@@@\xf0\xf0\xf5\xf1\xf8\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf0\xf1\xf9`\xf0\xf3`\xf2\xf6`\xf2\xf0K\xf1\xf1K\xf0\xf2K\xf2\xf1\xf0\xf0\xf0\xf0\xd5\xf0\xf0\xf1\xe8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf4\xf1\xf4\xf4\xf1\xf8\xf9\xf5\xf9\xf5\xf2\xf0\xf1\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xf1\xf8\xf9\xf5\xf9\xf5@@@\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xe2\xc8\xc5@\xd4\xd9@@@@@@@@@@@@@@\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xe2\xc8\xc5@\xd4\xd9@@@@@@@@@@@@@@\xc5\xc4@@\xd4\xe9\xe6\xd3\xf2\xd5\xd5\xd5\xd5\xd5@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf0\xf0\xf0\xf1\xf2\xf8\xf1\xf0\xf2\xf9\xd5@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1@@@@@@@@@@@@@@@@\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xd5\xd5\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@@@@@@@'`

I was expecting a response close to this:
`EQBET.FIN EQUATION BETX MERIDIAN AAEOS219866149512 0051800000000002018-11-22-09.58.17.649000N001Y 4610245907200XXXS ACCOUNT 1 XXXX ACCOUNT 1 245907 XXXX ACCOUNT 1 XXXXX ACCOUNT 1 EB MUSD2NNNNN 0000000000000000000000N 000000000000000 000000003120865 000000003167753 000000003204620 000000003317543 000000003317543Y 00000000331 7543Y 000000003317543 Y 000000003167753Y 000000000112923 000000000000000 000000000000000-000000000149790-000000000111753 000000000158641 000000000000000NNN 000000000000000`

**Comment by JoshMcMQ** [comment]
@Kayt what is the CCSID of the message on the queue?

You could try to add the convert option so messages are converted to local character set, ex: from EBCDIC to ASCII.

```
# Get Message Options
gmo = pymqi.GMO()
gmo.Options = pymqi.CMQC.MQGMO_CONVERT | pymqi.CMQC.MQGMO_FAIL_IF_QUIESCING
message = queue.get(None, md, gmo)
```

**Comment by JoshMcMQ** [comment]
No response,  closing issue.
