### ISSUE TITLE
Pymqi failing to get bytes message as string in Python 3

### ISSUE THREAD

**Issue by dilonne** [dsuch/pymqi#101]
unicodedecodeerror: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)

**Comment by dsuch** [comment]
Hello @dilonne,

I can only say that the chance that anyone will look into a ticket without any description, code or information how to reproduce a given situation is practically nil.

**Comment by JoshMcMQ** [comment]
Closed for lack of update from @dilonne
