### ISSUE TITLE
IntegerFilter in PCF.MQCMD_INQUIRE_Q

### ISSUE THREAD

**Issue by fetidbell** [dsuch/pymqi#102]
Hi there!
Can you please suggest me how can i apply IntegerFilter in my MQCMD_INQUIRE_Q method? I want to get all queues with current depth greater then 1000. Just dont know, how put this condition in my args here :(

```Python
prefix = "*".encode()
args = {
    pymqi.CMQC.MQCA_Q_NAME: prefix,
    pymqi.IntegerFilter(pymqi.CMQC.MQIA_CURRENT_Q_DEPTH, ) #here i just confused
}

qmgr = pymqi.connect(queue_manager, channel, conn_info)
pcf = pymqi.PCFExecute(qmgr)

try:
    response = pcf.MQCMD_INQUIRE_Q(args)
```

**Comment by fetidbell** [comment]
Im done with it, thanks Google =)
I use [this](https://bugs.launchpad.net/pymqi/+bug/754999)

```Python
prefix = '*'.encode()
filter = pymqi.Filter(pymqi.CMQC.MQIA_CURRENT_Q_DEPTH).greater(1000)
args = {
    pymqi.CMQC.MQCA_Q_NAME: prefix
}

qmgr = pymqi.connect(queue_manager, channel, conn_info)
pcf = pymqi.PCFExecute(qmgr)

try:
    response = pcf.MQCMD_INQUIRE_Q(args, [filter])
```

**Comment by dsuch** [comment]
Hi @fetidbell - I moved that code to the list of examples so it will be easier to find it now, thanks for bringing it to my attention.

https://dsuch.github.io/pymqi/examples.html#how-to-use-query-filters
