### ISSUE TITLE
The pymqe_MQCRTMH call is the cause of the crash in 64-bit system.

### ISSUE THREAD

**Issue by mixakamenev** [dsuch/pymqi#103]
Following the https://github.com/dsuch/pymqi/issues/45

pymqe.c +972 at 41c27c3899d942a89b8e2fb40459863319dd745b

```c++
  char *cmho_buffer;
  long cmho_buffer_length;

  MQCMHO *cmho;

  MQHMSG msg_handle = MQHM_UNUSABLE_HMSG;
  MQLONG comp_code = MQCC_UNKNOWN, comp_reason = MQRC_NONE;

  PyObject *rv;

#if PY_MAJOR_VERSION==2
  if (!PyArg_ParseTuple(args, "ls#", &conn_handle, &cmho_buffer, &cmho_buffer_length)) {
#else
  if (!PyArg_ParseTuple(args, "ly#", &conn_handle, &cmho_buffer, &cmho_buffer_length)) {
#endif
    return NULL;
  }
```
cmho_buffet_length - is uninitialized `long`.

At the same time https://docs.python.org/2/c-api/arg.html :

> s# (string, Unicode or any read buffer compatible object) [const char *, int (or Py_ssize_t, see below)]
This variant on s stores into two C variables, the first one a pointer to a character string, the second one its length. In this case the Python string may contain embedded null bytes. Unicode objects pass back a pointer to the default encoded string version of the object if such a conversion is possible. All other read-buffer compatible objects pass back a reference to the raw internal data representation.
Starting with Python 2.5 the type of the length argument can be controlled by defining the macro PY_SSIZE_T_CLEAN before including Python.h. If the macro is defined, length is a Py_ssize_t rather than an int.

And https://docs.python.org/3/c-api/arg.html :

> Note For all # variants of formats (s#, y#, etc.), the type of the length argument (int or Py_ssize_t) is controlled by defining the macro PY_SSIZE_T_CLEAN before including Python.h. If the macro was defined, length is a Py_ssize_t rather than an int. This behavior will change in a future Python version to only support Py_ssize_t and drop int support. It is best to always define PY_SSIZE_T_CLEAN.

It is possible to reproduce this behavour if you initialize a variable with a value greater than expected size:
```c++
long cmho_buffet_length = LONG_MAX;
```
Patch that fixes it:
```diff
diff --git a/code/pymqi/pymqe.c b/code/pymqi/pymqe.c
index 74c2b9f..2f6f51e 100644
--- a/code/pymqi/pymqe.c
+++ b/code/pymqi/pymqe.c
@@ -105,6 +105,8 @@ it is set to 'server'.\
 #include <cmqbc.h>
 #endif
 
+#define PY_SSIZE_T_CLEAN 1
+
 #include "Python.h"
 static PyObject *ErrorObj;
 
@@ -247,7 +249,7 @@ static char* Py23BytesOrText_AsString(PyObject *txtObj) {
 /* ----------------------------------------------------- */
 
 
-static int checkArgSize(size_t given, size_t expected, const char *name) {
+static int checkArgSize(Py_ssize_t given, Py_ssize_t expected, const char *name) {
   if (given != expected) {
     PyErr_Format(ErrorObj, "%s wrong size. Given: %lu, expected %lu", name, (unsigned long)given, (unsigned long)expected);
     return 1;
@@ -315,7 +317,7 @@ static PyObject * pymqe_MQCONNX(PyObject *self, PyObject *args) {
   MQHCONN handle;
   MQLONG comp_code, comp_reason;
   char* mqcd = NULL;
-  int mqcd_buf_len = 0;
+  Py_ssize_t mqcd_buf_len = 0;
   MQCNO cno = {MQCNO_DEFAULT};
   PyObject* user_password = NULL;
 
@@ -328,7 +330,7 @@ static PyObject * pymqe_MQCONNX(PyObject *self, PyObject *args) {
 
 #ifdef PYMQI_FEATURE_SSL
   char *sco = NULL;
-  int sco_len = 0;
+  Py_ssize_t sco_len = 0;
 #if PY_MAJOR_VERSION==2
   if (!PyArg_ParseTuple(args, "sls#O|s#", &name, &options, &mqcd, &mqcd_buf_len, &user_password, &sco, &sco_len)) {
 #else
@@ -441,7 +443,7 @@ static PyObject *pymqe_MQOPEN(PyObject *self, PyObject *args) {
 
   MQOD *qDescP;
   char *qDescBuffer;
-  int qDescBufferLength;
+  Py_ssize_t qDescBufferLength = 0;
   MQHOBJ qHandle;
   MQLONG compCode, compReason;
 
@@ -510,15 +512,15 @@ static PyObject * pymqe_MQCLOSE(PyObject *self, PyObject *args) {
 static PyObject *mqputN(int put1Flag, PyObject *self, PyObject *args) {
   MQLONG compCode, compReason;
   char *mDescBuffer;
-  int mDescBufferLength;
+  Py_ssize_t mDescBufferLength = 0;
   MQMD *mDescP;
   char *putOptsBuffer;
-  int putOptsBufferLength;
+  Py_ssize_t putOptsBufferLength = 0;
   MQPMO *pmoP;
   char *msgBuffer;
-  int msgBufferLength;
+  Py_ssize_t msgBufferLength = 0;
   char *qDescBuffer;
-  int qDescBufferLength;
+  Py_ssize_t qDescBufferLength = 0;
   MQOD *qDescP = NULL;
 
   long lQmgrHandle, lqHandle;
@@ -655,10 +657,10 @@ If mDesc or getOpts are the wrong size, an exception is raised. \
 static PyObject *pymqe_MQGET(PyObject *self, PyObject *args) {
   MQLONG compCode, compReason;
   char *mDescBuffer;
-  int mDescBufferLength;
+  Py_ssize_t mDescBufferLength = 0;
   MQMD *mDescP;
   char *getOptsBuffer;
-  int getOptsBufferLength;
+  Py_ssize_t getOptsBufferLength = 0;
   MQGMO *gmoP;
   long maxLength, returnLength;
   MQLONG actualLength;
@@ -915,7 +917,7 @@ static PyObject * pymqe_MQSUB(PyObject *self, PyObject *args) {
   PyObject *rv;
 
   char *subDescBuffer;
-  int subDescBufferLength;
+  Py_ssize_t subDescBufferLength = 0;
 
 
   long lQmgrHandle;
@@ -969,7 +971,7 @@ static PyObject* pymqe_MQCRTMH(PyObject *self, PyObject *args) {
   long conn_handle;
 
   char *cmho_buffer;
-  long cmho_buffer_length;
+  Py_ssize_t cmho_buffer_length = 0;
 
   MQCMHO *cmho;
   MQHMSG msg_handle = MQHM_UNUSABLE_HMSG;
@@ -1011,17 +1013,17 @@ static PyObject* pymqe_MQSETMP(PyObject *self, PyObject *args) {
   long conn_handle, msg_handle;
 
   char *smpo_buffer;
-  long smpo_buffer_length;
+  Py_ssize_t smpo_buffer_length = 0;
 
   char *pd_buffer;
-  long pd_buffer_length;
+  Py_ssize_t pd_buffer_length = 0;
 
   MQSMPO *smpo;
   MQPD *pd;
 
   MQCHARV name = {MQCHARV_DEFAULT};
   char *property_name;
-  long property_name_length = 0;
+  Py_ssize_t property_name_length = 0;
 
   long property_type;
 
@@ -1080,7 +1082,7 @@ static PyObject* pymqe_MQINQMP(PyObject *self, PyObject *args) {
 
   MQCHARV name = {MQCHARV_DEFAULT};
   char *property_name;
-  long property_name_length = 0;
+  Py_ssize_t property_name_length = 0;
 
   MQLONG property_type;
   MQLONG actual_value_length;
```
Minimal solution is replacement types of `cmho_buffer_length, smpo_buffer_length, pd_buffer_length, property_name_length, property_name_length` from `long` to `int`.
Initialization is useful.

**Comment by SeyfSV** [comment]
@mixakamenev, i think we got the same issues with trying to work with message's handlers. Please look to this [patch](https://github.com/SeyfSV/pymqi/commit/1a71d7d3b57e70e6a6a103bb72d30d0885200bfe), may be it can be helpful. I did not test it on 32-bit systems, but it works on windows and linux.

**Comment by mixakamenev** [comment]
@SeyfSV, thanks for your comment and patch.
```c++
#if defined(MQ_64_BIT)
 typedef int MQLONG;
 typedef unsigned int MQULONG;
 typedef long MQINT64;
 typedef unsigned long MQUINT64;
#else
 typedef long MQLONG;
 typedef unsigned long MQULONG;
 typedef long long MQINT64;
 typedef unsigned long long MQUINT64;
#endif
```
It seems that until these typedefs from cmqc.h will be changed MQLONG will be the appropriate solution. For the sake of clarity I would prefer native C types. It is subjectively.

**Comment by dsuch** [comment]
Hello everyone,

I like the idea of using Py_ssize_t - this is good and I would be happy to incorporate it. Would it be please possible for you to send in a PR?

As for typedefing long etc. in terms of MQ types (MQLONG and similar) - I am not sure if this is really needed?

Thanks.

**Comment by mixakamenev** [comment]
> I like the idea of using Py_ssize_t - this is good and I would be happy to incorporate it. Would it be please possible for you to send in a PR?

Done.

**Comment by dsuch** [comment]
Thanks, this is merged in.

**Comment by SeyfSV** [comment]
@dsuch, messageHandle.properties.set() does not work with current version. It does not return errors but message's propertie is epmty.

**Comment by dsuch** [comment]
@SeyfSV - I need concrete details. What do you mean by current version, by does not work, and how to reproduce it?

**Comment by SeyfSV** [comment]
I checked out #106, build it and ran sample.
For testing just put this block between `pymqi.Queue` and `queue.close`
```
        cmho = pymqi.CMHO()
        messageHandle = pymqi.MessageHandle(qmgr, cmho)
        messageHandle.properties.set(b'test', pymqi.py3str2bytes('test'))
        pmo = pymqi.PMO()
        pmo.OriginalMsgHandle = messageHandle.msg_handle
        md = pymqi.MD()
        queue.put(b'', md, pmo)
```
On Ubuntu 18.04.1 error does not occurs, but properties does not set.
Additionally I checked it on Windows 2016. I got an error:

> pymqi.MQMIError: MQI Error. Comp: 2, Reason 2460: FAILED: MQRC_HMSG_ERROR

**Comment by mixakamenev** [comment]
It also do not works for me without a patch from https://github.com/dsuch/pymqi/issues/104
With CMQC.MQPMO_VERSION_1 IBM MQ igonores pmo.OriginalMsgHandle and pmo.NewMsgHandle.

**Comment by SeyfSV** [comment]
@mixakamenev, what OS do you use?

**Comment by mixakamenev** [comment]
@SeyfSV, Red Hat.
