### ISSUE TITLE
PyMQI String Format

### ISSUE THREAD

**Issue by TimothyTakudzwa** [dsuch/pymqi#105]
Hie is there a way to specify the response that i get to be in string format. I am trying to get my message from IBM Websphere MQ but however it is coming as bytes data. Is there i can get the message as is in string format. Please find below the sample messages and the expected message 

**Expected Response**
0000.FIN EQUATION BETX AAAAAAA AAEOS219866149512 0051800000000002018-11-22-09.58.17.649000N001Y 4610245907200XXXS ACCOUNT 1 XXXX ACCOUNT 1 245907 XXXX ACCOUNT 1 XXXXX ACCOUNT 1 EB MUSD2NNNNN 0000000000000000000000N 000000000000000 000000003120865 000000003167753 000000003204620 000000003317543 000000003317543Y 00000000331 7543Y 000000003317543 Y 000000003167753Y 000000000112923 000000000000000 000000000000000-000000000149790-000000000111753 000000000158641 000000000000000NNN 000000000000000

This message is the expected message which is in string format however after executing the below script 

`import pymqi

queue_manager = "xx.xxx.xxx"
channel = "xxxx.xxx.xxx"
host = "x.x.x.x"
port = "1414"
queue_name = "xxx.xxxxxx.xxx"

conn_info = "%s(%s)" % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info,'xxx','xxx')
queue = pymqi.Queue(qmgr, queue_name)
md = pymqi.MD()
md.Format = pymqi.CMQC.MQFMT_STRING

message = queue.get(None, md)`

**The response Message**
b'\xc1\xc3K\xd9\xc5\xe2\xd7K\xd8\xe4\xc5\xe4\xc5@@@@@@@@@@@@@@@@@@@\xc5\xd8\xe4\xc1\xe3\xc9\xd6\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xd6\xe3\xc3\xe7@@@@@@@@@@@@@@@@@@@@@@@@\xd4\xc5\xd9\xc9\xc4\xc9\xc1\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xc1\xc1\xd1\xc5\xc5\xf2\xf3\xf0\xf6\xf0\xf3\xf0\xf6\xf2\xf3\xf7\xf2@@@@@\xf0\xf0\xf5\xf1\xf8\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf0\xf1\xf9\xf0\xf3\xf2\xf6\xf2\xf0K\xf1\xf1K\xf0\xf2K\xf2\xf1\xf0\xf0\xf0\xf0\xd5\xf0\xf0\xf1\xe8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf4\xf1\xf4\xf4\xf1\xf8\xf9\xf5\xf9\xf5\xf2\xf0\xf1\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xf1\xf8\xf9\xf5\xf9\xf5@@@\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xe2\xc8\xc5@\xd4\xd9@@@@@@@@@@@@@@\xc3\xc8\xc9\xc4\xd6\xc4\xd6@\xe2\xc9\xd4\xc2\xc1\xd9\xc1\xe2\xc8\xc5@\xd4\xd9@@@@@@@@@@@@@@\xc5\xc4@@\xd4\xe9\xe6\xd3\xf2\xd5\xd5\xd5\xd5\xd5@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf0\xf0\xf0\xf1\xf2\xf8\xf1\xf0\xf2\xf9\xd5@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf2\xf4\xf1\xf1@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1@@@@@@@@@@@@@@@@\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf1\xf4\xf1\xf1\xe8@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xd5\xd5\xd5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0\xf0@@@@@@@'`

Is there a way i can specify the message format to be received

**Comment by dsuch** [comment]
Hello @TimothyTakudzwa,

I am not sure myself why you are receiving these bytes instead of the intended message - can you explain your setup some more? What are the OS / MQ versions involved and byte encodings used by MQ + the sending application?

Thanks.

**Comment by TimothyTakudzwa** [comment]
I am connecting with a third party application and we are using queues for communication within the same network however i am trying to get the messages that would have come from the application via IBM Websphere MQ Version: 8.0.0.5 and they are coming back as bytes. I had had the similar message on using put message to send the message to MQ and the message was being send as bytes and i was able to fix that issue by adding the below line 

`md = pymqi.MD()
md.Format = pymqi.CMQC.MQFMT_STRING

message = queue.putget(None, md)``

and then the message was now being send as Strings however i tried implementing the same concept with getting the message

`md = pymqi.MD()
md.Format = pymqi.CMQC.MQFMT_STRING

message = queue.get(None, md)`` 

and all i could get was just the same data. 

I am using Windows 10 and the sending application is a core banking system

**Comment by dsuch** [comment]
What I am saying is that I do not see anything wrong with your code so I am trying to understand better the circumstances.

I suggest that you:

* Use another tool, possibly a GUI one to investigate the contents of the queue, prior to getting the message using PyMQI, in order to double-check what the message actually is

* Use PyMQI to send another message to the queue and get it using the code you submitted to this ticket to check how it will look like

**Comment by TimothyTakudzwa** [comment]
I did all that, i checked the GUI and saw the message was the one that i was expecting to get the one in string format. I also tried dumping my own message into a queue and getting it but it still comes back as bytes

**Comment by dsuch** [comment]
Please post the exact code that you used to send a message to a queue.

**Comment by dsuch** [comment]
Also, looking at the bytes again, I appears that this message is in EBCDIC. You need to decode them to Unicode to get a human-readable form.

**Comment by TimothyTakudzwa** [comment]
Thank you. I solved it by converting the EBDIC format  to Unicode
