### ISSUE TITLE
Put a rfh2 message in topic not implemented

### ISSUE THREAD

**Issue by bityon** [dsuch/pymqi#11]
There is a function put_rfh2 for message in queue, but not for a topic.

**Comment by bityon** [comment]
#12 Pull which implement the put_rfh2

**Comment by JoshMcMQ** [comment]
@dsuch This seems like a reasonable request, any reason this was not merged?

**Comment by dsuch** [comment]
@JoshMcMQ - I have had a look at this PR and it looks it has a merge conflict. It was 3+ years ago though so a few things might have changed since then. Do you think it can be brought up to a good state easily?

**Comment by JoshMcMQ** [comment]
It appears they just copied the code from queue and added it to topic.  Underlying at the MQ level you can "put" messages to a queue or a topic.
