### ISSUE TITLE
pymqi on macos Library not loaded: @rpath/libmqic_r.dylib

### ISSUE THREAD

**Issue by guimarc-br** [dsuch/pymqi#111]
Hello Guys.

I am running on MAC OS MOJAVE and running a project on PYTHOn under Intellij.

ImportError: dlopen(/Users/guilhermemarcondes/IdeaProjects/ODOO_ENV2/lib/python3.6/site-packages/pymqi/pymqe.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmqic_r.dylib
  Referenced from: /Users/guilhermemarcondes/IdeaProjects/ODOO_ENV2/lib/python3.6/site-packages/pymqi/pymqe.cpython-36m-darwin.so
  Reason: image not found

1 - Installed XCODE
2 - Created a ENV from scratch
3 - Download and unziped the toolkit from mac to OPT/MQM
4 - Performed the Export for MQ installation and DYL .
5 - Install the pymqi
But go the same error.

Please help me on that.. I really appreaciated

**Comment by burizz** [comment]
Same issue 

`python setup.py install
Building PyMQI client mode 64bits
Using library_dirs:`['/opt/mqm/lib64']`, include:`['/opt/mqm/inc']`, libraries:`['mqic_r']`
running install
running bdist_egg
running egg_info
writing pymqi.egg-info/PKG-INFO
writing dependency_links to pymqi.egg-info/dependency_links.txt
writing top-level names to pymqi.egg-info/top_level.txt
reading manifest file 'pymqi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pymqi.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/pymqe.cpython-37m-darwin.so -> build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/CMQZC.py -> build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/CMQXC.py -> build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/CMQC.py -> build/bdist.macosx-10.9-x86_64/egg/pymqi
copying build/lib.macosx-10.9-x86_64-3.7/pymqi/CMQCFC.py -> build/bdist.macosx-10.9-x86_64/egg/pymqi
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/CMQZC.py to CMQZC.cpython-37.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/CMQXC.py to CMQXC.cpython-37.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/CMQC.py to CMQC.cpython-37.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/CMQCFC.py to CMQCFC.cpython-37.pyc
creating stub loader for pymqi/pymqe.cpython-37m-darwin.so
byte-compiling build/bdist.macosx-10.9-x86_64/egg/pymqi/pymqe.py to pymqe.cpython-37.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying pymqi.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying pymqi.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying pymqi.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying pymqi.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pymqi.__pycache__.pymqe.cpython-37: module references _file_
creating 'dist/pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg
removing '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg' (and everything under it)
creating /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg
Extracting pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg to /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
pymqi 1.9.2 is already the active version in easy-install.pth

Installed /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymqi-1.9.2-py3.7-macosx-10.9-x86_64.egg
Processing dependencies for pymqi==1.9.2
Finished processing dependencies for pymqi==1.9.2
`

`Type "help", "copyright", "credits" or "license" for more information.
>>> import pymqi
Traceback (most recent call last):
  File "/Users/asdfg/mq/pymqi/code/pymqi/__init__.py", line 110, in <module>
    from . import pymqe
ImportError: cannot import name 'pymqe' from 'pymqi' (/Users/asdfg/mq/pymqi/code/pymqi/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asdfg/mq/pymqi/code/pymqi/__init__.py", line 112, in <module>
    import pymqe  # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'
>>> `

Compiling goes through fine. But it doesnt seem to be copied during python setup.py install
`python setup.py build build_ext -I /opt/mqm/
Building PyMQI client mode 64bits
Using library_dirs:`['/opt/mqm/lib64']`, include:`['/opt/mqm/inc']`, libraries:`['mqic_r']`
running build
running build_py
running build_ext`

**Comment by chughts** [comment]
Before you install pymqi you need to install and set up paths for the MQ MacOS Toolkit. If you have tried to install pymqi, had it fail, then set up the MQ MacOS Toolkit Paths, then the install will continue to fail. You need to uninstall and wipe out pymqi. Then set up the MQ MacOS Toolkits Paths 

- Downalod IBM MQ MacOS toolkit for developers v 9.x
- Add <unzip location>/IBM-MQ-Toolkit-Mac-x64-9.1.1.0/bin and <unzip location>/IBM-MQ-Toolkit-Mac-x64-9.1.1.0/samp/bin, to the PATH by editing /etc/paths
- export DYLD_LIBRARY_PATH = <unzip location>/IBM-MQ-Toolkit-Mac-x64-9.1.1.0/lib64

Then install pymqi.

**Comment by JoshMcMQ** [comment]
@guimarc-br and @burizz ok to close?

**Comment by pspratihar** [comment]
how do you uninstall pymqi?
