### ISSUE TITLE
pymqi.MessageHandle(qmgr, cmho) throws MQCMHO Wrong Size Error

### ISSUE THREAD

**Issue by chughts** [dsuch/pymqi#112]
I am putting blob data through pymqi, but get the following error
````
    messageHandle = pymqi.MessageHandle(qmgr, cmho)
  File "/Users/soheelchughtai/Documents/dev/python/mqdatasender/mqenv/lib/python2.7/site-packages/pymqi/__init__.py", line 2390, in __init__
    cmho.pack())
pymqe.error: MQCMHO wrong size. Given: 140728898420748, expected 12
````  

My code is: 

```python
                cmho = pymqi.CMHO()
                messageHandle = pymqi.MessageHandle(qmgr, cmho)
                messageHandle.properties.set("filename", name)
                messageHandle.properties.set("location", loc)

                pmo = pymqi.PMO()
                pmo.OriginalMsgHandle = messageHandle.msg_handle

                md = pymqi.MD()
                queue.put(data, md, pmo)
```

and the line messageHandle = pymqi.MessageHandle(qmgr, cmho), is causing the error. How do I specify a size so that the cmho.pack() doesn't throw the wrong size error?

**Comment by dsuch** [comment]
Hi @chughts,

message properties and MQCMHO were contributed by a user and this is a part of PyMQI that I myself do not know nor use at all.

That value, 140728898420748 - does it bear a relation do your data? Or is it random each time?

**Comment by chughts** [comment]
It's consistent, yet it doesn't appear to be related to my actual data, as if fails before I get round to the put, but even if I try to put `b"abc"` it keeps failing on the `pymqi.MessageHandle(qmgr, cmho)` line. 

I based the code on the test 
 https://github.com/dsuch/pymqi/blob/master/code/tests/test_message_property.py  that @SeyfSV last modified. Does that test succeed?

**Comment by SeyfSV** [comment]
Hi @chughts 
Please add some description about your environment.
Do you run the test? (`nosetests tests/test_message_property.py`).
Please note #103 issue and this [comment](https://github.com/dsuch/pymqi/issues/103#issuecomment-480069401).
As a test you can try pymqi from my fork

**Comment by chughts** [comment]
@SeyfSV 
I have not run the test. How do I go about doing that. 

MQ is running in the IBM Cloud
Client is running on a Mac in a clean virtualenv. I have the following pip libraries:
````
Click==7.0
Flask==1.0.2
image-slicer==0.2.0
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
Pillow==6.0.0
pymqi==1.9.2
Werkzeug==0.15.2
````

I am running a flask app. If I don't try to add message properties the following code works:

```python
self.queue.put(data)
```

but I need to add some meta data to the message, and when I try to add in message properties, the line 

```python 
                messageHandle = pymqi.MessageHandle(qmgr, cmho)
```

fails with the size error.

**Comment by SeyfSV** [comment]
Am I right that you use pymqi from pip?
Published version 1.9.2 from Mar 12 has issue #103 from Apr 2 about CMHO (pymqe_MQCRTMH) function and issue #104 from Apr 2 about version of PMO structure, that needed for setting properties.
#103 is closed, but I steel can't run this version on Windows machine.
#104 is not closed, but is has a code in it for fixing.

**Comment by chughts** [comment]
Yes its a pip install. To confirm is your fork - https://github.com/SeyfSV/pymqi ? Do I use the #master branch ?

**Comment by dsuch** [comment]
Thank you both for collaborating on it - @chughts, if you confirm everything using @SeyfSV's fork, I will be happy to incorporate all the changes to PyMQI.

**Comment by chughts** [comment]
Ran the following in my virtualenv

````
pip uninstall pymqe
git clone https://github.com/SeyfSV/pymqi
pip install  <path to clone>/pymqi/setup.py
````

but keep getting

````
ERROR: /Users/soheelchughtai/Documents/dev/python/mqtransporter/pymqi/code/setup.py should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
````

same error when I try

````
pip install  <path to clone>/pymqi/code/setup.py
````

**Comment by chughts** [comment]
Got over that by running 
````
pip install /Users/soheelchughtai/Documents/dev/python/mqtransporter/pymqi/code
````

**Comment by chughts** [comment]
I can confirm that running with @SeyfSV fork, I am able to send and retrieve string values as message header properties.

**Comment by JoshMcMQ** [comment]
@dsuch I think this should be closed now?
