### ISSUE TITLE
PYMQI installation problems Redistributable Client IBM MQC

### ISSUE THREAD

**Issue by srPuebla** [dsuch/pymqi#120]
Hello,

We are having problems with installation of pymqi wheel.

We tell you the full history:

We installed client ibmmq in a ubuntu server. After that, we installed successfully pymqi and we generated the .whl file. 

We took that .whl file to other server container and it is installed successfully, however when the pymqi its imported we get the next error below:

`
ERR     import pymqi
ERR   File "/home/vcap/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pymqi/__init__.py", line 112, in 
ERR     import pymqe  # Backward compatibility
ERR ImportError: libmqic_r.so: cannot open shared object file: No such file or directory
ImportError: libmqic_r.so: cannot open shared object file: No such file or directory
`

We have put "9.0.0.7-IBM-MQC-Redist-LinuxX64.tar.gz" Redistributable version on the container in path "/home/vcap/app/mqm/" and we untar it. After that we modified the enviroment variable "LD_LIBRARY_PATH" to '/home/vcap/app/mqclient/lib' but the error persists.

We cant install rpms, yum or apt-get cause it is an "application as a service" and application must contain all resources to work
We dont have permmissions on /opt/... so we cant create /opt/mqm/ where pymqi reads to get the MQ Client. 

What can we do?

Regards,

**Comment by chughts** [comment]
I think that should be `/home/vcap/app/mqclient/lib64`

**Comment by srPuebla** [comment]
Also we tested with that, but it doesnt work.

**Comment by srPuebla** [comment]
I think that library is looking for /opt/mqm path and doesnt look other paths configured. In setup,py we see that lines:

`    if bits == 64:
        library_dirs = ['/opt/mqm/lib64']
    else:
        library_dirs = ['/opt/mqm/lib']

    include_dirs = ['/opt/mqm/inc']`

**Comment by srPuebla** [comment]
@ @ @ @ @ @ @

**Comment by srPuebla** [comment]
Sorry i closed it, miss click

**Comment by chughts** [comment]
You might need to create a symbolic link to `/opt/mqm`

**Comment by srPuebla** [comment]
Thanks for reply so quickly.

Could you try to install the library in a clean server (ubuntu, centros, etc ) with the redist client mq?

At the end, its imposible cause It needs rpm installed to work. If you try to install, and configure the path, you Will get that kind of errors.

Try It if posible.

Regards!

**Comment by srPuebla** [comment]
Hello Again,

I am gonna update the issue. You have a machine with python and we try to install pymqi:

```

[root@centos7carlos opt]# pip install pymqi
Collecting pymqi
  Using cached https://files.pythonhosted.org/packages/15/d9/b5babbd3f296b47a9d8bca417ca185ede9e8780ce4ca6b66bbf2dd1b7880/pymqi-1.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YOdqKV/pymqi/setup.py", line 156, in <module>
        raise Exception('MQ libraries could not be found')
    Exception: MQ libraries could not be found

```

After that, we download "9.0.0.7-IBM-MQC-Redist-LinuxX64.tar.gz" Redistributable version of IBM web and we untar in the folder /opt/mqm/

```
[root@centos7carlos opt]# pip install pymqi
Collecting pymqi
  Using cached https://files.pythonhosted.org/packages/15/d9/b5babbd3f296b47a9d8                                                                                                                                                      bca417ca185ede9e8780ce4ca6b66bbf2dd1b7880/pymqi-1.9.2.tar.gz
Building wheels for collected packages: pymqi
...
    pymqi/pymqe.c:78:18: error fatal: cmqc.h: No existe el fichero o el director                                                                                                                                                      io
     #include <cmqc.h>
                      ^
    compilaciÃ³n terminada.
    error: command 'gcc' failed with exit status 1

```
Finally we put "inc" folder on /opt/mqm with cmqc.h and others files

```
[root@centos7carlos mqm]# ls
bin  gskit8  inc  java  lib  lib64  licenses  msg  samp
[root@centos7carlos mqm]# cd inc/
[root@centos7carlos inc]# ls
amqsvmha.h  CMQBOV   CMQCFBFL  CMQCFHL   CMQCFINV  CMQCFV    CMQCHRVV  CMQCSPL   CMQDLHV   CMQEPHV  CMQIMPOL  CMQMDEV   CMQORL    CMQPSV    CMQRRL    CMQSMPOV   CMQTMC2V  CMQXQHL     imqbin.hpp  imqgmo.hpp  imqmtr.hpp  imqstr.hpp
CMQAIRL     CMQCBCL  CMQCFBFV  CMQCFHV   CMQCFSFL  CMQCFXLL  CMQCIHL   CMQCSPV   CMQDMHOL  CMQGMOL  CMQIMPOV  CMQMDL    CMQORV    CMQRFH2L  CMQRRV    CMQSROL    CMQTML    CMQXQHV     imqcac.hpp  imqhdr.hpp  imqnml.hpp  imqtrg.hpp
CMQAIRV     CMQCBCV  CMQCFBSL  CMQCFIFL  CMQCFSFV  CMQCFXLV  CMQCIHV   CMQCTLOL  CMQDMHOV  CMQGMOV  CMQMD1L   CMQMDV    CMQPDL    CMQRFH2V  CMQSCOL   CMQSROV    CMQTMV    CMQXV       imqchl.hpp  imqi.hpp    imqobj.hpp  imqtype.h
cmqbc.h     CMQCBDL  CMQCFBSV  CMQCFIFV  CMQCFSLL  CMQCFXNL  CMQCMHOL  CMQCTLOV  CMQDMPOL  CMQIEPL  CMQMD1V   CMQMHBOL  CMQPDV    CMQRFHL   CMQSCOV   cmqstrc.h  CMQV      cmqzc.h     imqcih.hpp  imqiih.hpp  imqpmo.hpp  imqwih.hpp
CMQBMHOL    CMQCBDV  cmqcfc.h  CMQCFILL  CMQCFSLV  CMQCFXNV  CMQCMHOV  CMQDHL    CMQDMPOV  CMQIEPV  CMQMD2L   CMQMHBOV  CMQPMOL   CMQRFHV   CMQSDL    CMQSTSL    CMQWIHL   cobcpy32    imqdlh.hpp  imqitm.hpp  imqpro.hpp
CMQBMHOV    CMQCDL   CMQCFGRL  CMQCFILV  CMQCFSTL  cmqc.h    CMQCNOL   CMQDHV    cmqec.h   CMQIIHL  CMQMD2V   CMQODL    CMQPMOV   CMQRMHL   CMQSDV    CMQSTSV    CMQWIHV   cobcpy64    imqdst.hpp  imqmgr.hpp  imqque.hpp
CMQBOL      CMQCDV   CMQCFGRV  CMQCFINL  CMQCFSTV  CMQCHRVL  CMQCNOV   CMQDLHL   CMQEPHL   CMQIIHV  CMQMDEL   CMQODV    cmqpsc.h  CMQRMHV   CMQSMPOL  CMQTMC2L   cmqxc.h   imqair.hpp  imqerr.hpp  imqmsg.hpp  imqrfh.hpp
[root@centos7carlos inc]# pwd
/opt/mqm/inc

```
After that, we install pymqi and... it works, but... when you try to import we get the surprise.

```
[root@centos7carlos opt]# pip install pymqi
Collecting pymqi
  Using cached https://files.pythonhosted.org/packages/15/d9/b5babbd3f296b47a9d8bca417ca185ede9e8780ce4ca6b66bbf2dd1b7880/pymqi-1.9.2.tar.gz
Building wheels for collected packages: pymqi
  Running setup.py bdist_wheel for pymqi ... done
  Stored in directory: /root/.cache/pip/wheels/c7/ec/5c/ed2cd02afdd3e7232ecaec4eb1855c67a48d376dfcd75e1d31
Successfully built pymqi
Installing collected packages: pymqi
Successfully installed pymqi-1.9.2

```
When we use it on python...

```
[root@centos7carlos opt]# python
Python 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymqi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pymqi/__init__.py", line 112, in <module>
    import pymqe  # Backward compatibility
ImportError: libmqic_r.so: cannot open shared object file: No such file or directory
>>>
>>>

```

Thats the full problem. 

Regards,

**Comment by chughts** [comment]
The sequence is at fault here. If you try to install pymqi before setting up the MQ client and the paths, then there remains a remnant of pymqi on your machine that interferes with the correct installation and set-up of pymqi. I have seen something similar on mac. 


You need a clean install of pymqi from scratch, so you must uninstall what you have and clean up. I find that the easiest way is to have virtualenv, allowing me to simply delete a failed environment.

**Comment by JoshMcMQ** [comment]
The MQ v9.0 redist client does not include the `*.h` files, starting at MQ v9.1 Continuous Delivery those are included, so MQ v9.1.3 is the latest of that release level.

**Comment by JoshMcMQ** [comment]
What does `ldd` show on the compiled pymqe file?

**Comment by srPuebla** [comment]
Hi JoshMcMQ and chughts

Thanks for replay, tomorrow i will try with MQ v9.1.3 Redist and i will tell u!. Now i cant access to server.

Thanks,

**Comment by srPuebla** [comment]
JoshMcMQ and chughts, sorry for the Delay. You are genius. 9.1.3 version redist contains "inc" folder which it doesnt exist on 9.0.0.7 version. That was our main problem. 

It is solved. Thanks sooooo much for your replays!

:+1:

**Comment by JoshMcMQ** [comment]
Closing issue.
