### ISSUE TITLE
Install on RHEL 7, import error on pymqe

### ISSUE THREAD

**Issue by Alan-Graham** [dsuch/pymqi#121]
Hi, I've just installed pymqi  in a venv using
python3 -m pip install pymqi

After struggling for a while because it expects the MQ client to be in /opt/mqm, but on our systems it's in /opt/ibm/mqm (I set up a symlink, that fixed it), the install worked

But when I try to import it in a python interactive session in the activated venv session, I get this:

    Python 3.6.3 (default, Apr 10 2019, 14:37:36)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pymqi
    Traceback (most recent call last):
      File "/home/<my id>/pydev/iib_venv/lib64/python3.6/site- 
    packages/pymqi/__init__.py", line 110, in <module>
        from . import pymqe
    ImportError: libmqic_r.so: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/<my id>/pydev/iib_venv/lib64/python3.6/site- 
    packages/pymqi/__init__.py", line 112, in <module>
    import pymqe  # Backward compatibility
    ModuleNotFoundError: No module named 'pymqe'

I've looked at the site packages, and the file `pymqe.cpython-36m-x86_64-linux-gnu.so` does exist in that directory

--Update--
I've found that the libmqic_r.so file is in the /opt/ibm/mqm/lib64 directory, and is world readable and executable (chmod 555, owned by mqm), and so are all of the parent directories.  The symlink I created to get the install working means that I can run `ls /opt/mqm/lib64/libmqic_r.so` and it finds the file.

I'm thinking then that the pymqe object is searching for this in a way that the symlink doesn't provide?  maybe?

**Comment by SeyfSV** [comment]
Hi, 
Try to use PYTHONPATH environment variable as workaround before running interactive session:
`export PYTHONPATH=/home/<my id>/pydev/iib_venv/lib64/python3.6/site-packages/pymqi:$PYTHONPATH`

**Comment by chughts** [comment]
Make sure that LIBPATH includes $MQ_INSTALLATION_PATH/lib64. This will be either DYLD_LIBRARY_PATH or LD_LIBRARY_PATH

**Comment by KYDronePilot** [comment]
I had a similar issue, but my MQ installation was in the default `/opt/mqm`. Adding `/opt/mqm/lib64` to `LD_LIBRARY_PATH` fixed it for me.

**Comment by charly37** [comment]
I manage to get it running on centos8. It may help you >> https://github.com/dsuch/pymqi/issues/144

**Comment by sirkordi** [comment]
I was having the same issue. In my case, the problem was that I didn't set the primary installation on a freshly installed mq client. After executing below command the issue was gone:

sudo /opt/mqm/bin/setmqinst -i -p /opt/mqm/

**Comment by LeoValadares** [comment]
> I was having the same issue. In my case, the problem was that I didn't set the primary installation on a freshly installed mq client. After executing below command the issue was gone:
> 
> sudo /opt/mqm/bin/setmqinst -i -p /opt/mqm/

THANKS A BUNCH YOU SAVE MY LIFE

**Comment by sirkordi** [comment]
> THANKS A BUNCH YOU SAVE MY LIFE

Cheers!

**Comment by MrEzio** [comment]
> I was having the same issue. In my case, the problem was that I didn't set the primary installation on a freshly installed mq client. After executing below command the issue was gone:
> 
> sudo /opt/mqm/bin/setmqinst -i -p /opt/mqm/

I don't know who you are, you don't know who I am, but just know that you just saved me from 4 hours straight of hell. Bless you!!!!

**Comment by sirkordi** [comment]
> I don't know who you are, you don't know who I am, but just know that you just saved me from 4 hours straight of hell. Bless you!!!!

Glad I could help :)

**Comment by jgoncalvesnewstore** [comment]
#

> I was having the same issue. In my case, the problem was that I didn't set the primary installation on a freshly installed mq client. After executing below command the issue was gone:
> 
> sudo /opt/mqm/bin/setmqinst -i -p /opt/mqm/

Thank you so much, i was2 hours stuck with this
