### ISSUE TITLE
How to create a key repo in linux?

### ISSUE THREAD

**Issue by gowdhammurthi** [dsuch/pymqi#122]

**Comment by gowdhammurthi** [comment]
I am trying to connect to cloud MQ. I have created a repo but the sco object's attribute KeyRepository
returns error when the script is running.
'''File "/usr/local/lib/python3.5/dist-packages/pymqi/__init__.py", line 1412, in connectWithOptions
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2381: FAILED: MQRC_KEY_REPOSITORY_ERROR'''

**Comment by JoshMcMQ** [comment]
Please post you code showing how you reference the key store location.

**Comment by gowdhammurthi** [comment]
cd = pymqi.CD()
        cd.ChannelName = channel
        cd.ConnectionName = conn_info
        cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
        cd.TransportType = pymqi.CMQC.MQXPT_TCP
        cd.SSLCipherSpec = "TLS_RSA_WITH_AES_256_CBC_SHA256"

        sco = pymqi.SCO()
        sco.KeyRepository = "./cert/mqkey"

        qmgr = pymqi.QueueManager(None)
        qmgr.connect_with_options(queue_manager, cd, sco)

**Comment by gowdhammurthi** [comment]
./cert contains files mqkey.kdb, mqkey.sth, mqkey.rdb

**Comment by JoshMcMQ** [comment]
Check /var/mqm/errors/AMQERR01.LOG and set of it provides any additional data.

**Comment by gowdhammurthi** [comment]
Thanks solved that but got another issue /var/mqm/AMQCLCHL.TAB not found

**Comment by gowdhammurthi** [comment]
I am new to open-source community. I will take your advice.
I got the problem because the environment variable MQSSLKEYR was not set. 
Now, I have set the following environment variables 
MQSSLKEYR , MQCHLTAB, MQCHLLIB with full path and stem name.
Even now i get error as MQSSLKEYR is not set.Though,  I have added it to /etc/environment
What am I trying to do?
I am trying to connect from Python application to CLOUD MQ. 
The server channel is configured for encryption of messages, with ssl_cipher_spec.
I have the public certificate. I have added to key repo placed in /var/mqm/ssl/key

Kindly help me! Thanks! 

P.S. : If I am not clear tell me. I will add more information

**Comment by dsuch** [comment]
Thank you for the details @gowdhammurthi - myself, I will not be able to help you but perhaps others will be.

I just wanted to give you more background about how participating in this kind of communities works.

**Comment by gowdhammurthi** [comment]
Thanks @dsuch ! 
Can you clarify on this. 
Is it possible to enfore both encryption (TLS/SSL) and authentication(Userid/Password) in pymqi
Because, all overloading of connect function either allow (cd , sco) as arguments or (user,pass)
is there any possibilty to send all (cd,sco,user,pass)
Thanks

**Comment by dsuch** [comment]
Yes, you can do it via connect_with_options - here is a usage example:

https://dsuch.github.io/pymqi/examples.html#how-to-use-ssl-tls

**Comment by chughts** [comment]
Here is another example - https://github.com/ibm-messaging/mq-dev-patterns/blob/master/Python/basicput.py

**Comment by gowdhammurthi** [comment]
Thanks everyone
