### ISSUE TITLE
Default value for MQCD.TransportType is CMQC.MQXPT_LU62

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#125]
Hello,
I could not found any reference in IBM MQ docs or C header files about defining default value for  MQCD.TransportType variable, but class CD has this row:
            ['TransportType', CMQC.MQXPT_LU62, MQLONG_TYPE],
I have nothing against about default value, but what do you think about changing it to MQXPT_TCP?
Also I propose to change ChannelType to MQCHT_CLNTCONN

**Comment by dsuch** [comment]
Most of connections these days will be from remote TCP clients so it makes sense to change the defaults because that is what most people likely have to do anyway.

I will be happy to merge a PR if you send it in.

Thanks.
