### ISSUE TITLE
Linux: 2035 FAILED: MQRC_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by StinkyBell** [dsuch/pymqi#127]
HI there!
I know that this issue has already been discussed several times, but i just want to know is there any solution?
I try to execute this code 

```python
import pymqi

queue_manager = "PROD_QM01"
channel = "PROD_SVRCONN"
host = "v-dcr-esb"
port = "1414"
conn_info = f'{host}({port})'
try:
    qmgr = pymqi.connect(queue_manager, channel, conn_info)
    print('success')
except:
    raise
```

but get 2035 error. I use Python 3.6, pymqi 1.9.2, IBM MQ Client 8.0.0.12
Strange, but this behavior peculiar to Linux (Ubuntu 16), **when i execute this script on Windows i got no error**. To note - there is no auth on my channel, there is empty user and password. Can you please suggest me how can i fix it? Thank you!

+++ end yes, it is because my script substitue shell user (root) and try to authorize with it. **Is there a way to send blank user and password to IBM MQ broker?**

08/30/2019 05:16:29 PM - Process(20012.673915) User(iib) Program(amqrmppa)
                    Host(v-dcr-esb) Installation(Installation1)
                    VRMF(8.0.0.12) QMgr(PROD_QM01)

AMQ9557: Queue Manager User ID initialization failed for 'root'.

EXPLANATION:
The call to initialize the User ID 'root' failed with CompCode 2 and Reason
2035. If an MQCSP block was used, the User ID in the MQCSP block was ''.
ACTION:
Correct the error and try again.

Thanks for your time and help!

**Comment by SeyfSV** [comment]
Hi, what do you see in previous message?
I tried to run your test with sudo and got:
```
31.08.2019 17:45:49 - Process(362.15) User(seyf) Program(amqzlaa0)
                    Host(vsavchenko-mob) Installation(Installation1)
                    VRMF(7.5.0.4) QMgr(MQTEST)
                   
AMQ8077: Entity 'root        ' has insufficient authority to access object
'MQTEST'.

EXPLANATION:
The specified entity is not authorized to access the required object. The
following requested permissions are unauthorized: connect

```
From this error is clear that root does not have required grants.

PS
It is not good way to run something under the root user

**Comment by StinkyBell** [comment]
I don't have all logs right know, sorry. The thing is, that I run my script in a Docker container, so default user there is root. I create a new user, but it doesn't help, I still got 2035 error. Note: the authentication is off on my IBM MQ server, there is just no user or password needed to connect broker.

**Comment by SeyfSV** [comment]
You have client in a docker, but what about broker (MQ Server)? What do you have in MQ Server logs?

PS
You can use different user for running programs in container.

**Comment by StinkyBell** [comment]
I show my logs it my first message, it's not enough? do you need additional messages from logs?

**Comment by JoshMcMQ** [comment]
If you really don't want security (why I'm not sure? ) then cul in the `MCAUSER` on the `SVRCONN` channel with a valid user.

**Comment by StinkyBell** [comment]
@JoshMcMQ thank for your answer. There is absolutely no users in channel, and you suggest me to fill MCA(message channel agent, if i understand properly) with a valid user. What user is valid, if there is no users at all?

**Comment by SeyfSV** [comment]
> I show my logs it my first message, it's not enough? do you need additional messages from logs?

Yes, I need message before one mentioned by you.
MQ writes logs messages in a pair, the first one show more info than a second one.

**Comment by SeyfSV** [comment]
> @JoshMcMQ thank for your answer. There is absolutely no users in channel, and you suggest me to fill MCA(message channel agent, if i understand properly) with a valid user. What user is valid, if there is no users at all?

You can use user, used in Windows environment, for example

**Comment by StinkyBell** [comment]
Guys, im so sorry, it was absolutely my fault - i made a mistake with my channel string.
Thanks for your help, it teached me to be much more careful with my code. Close issue.
