### ISSUE TITLE
PyMQI MQ Client connection from Virtual Linux box on Windows-Host fails with MQI Error (Reason 2035)

### ISSUE THREAD

**Issue by Tom18** [dsuch/pymqi#128]
Hi,

I'm quite new to the topic and try to connect to Websphere MQ (Version 9) via PyMQI.

Following code snippet I have used to start testing:

    import pymqi

    queue_manager = '...'
    channel = '...'
    conn_info = '...'
    queue_name = '...'

    # My user credentials for MQ
    user = '...'
    password = '…' 

    qmgr = pymqi.connect(queue_manager, channel, conn_info, user, password)

    putq = pymqi.Queue(qmgr, queue_name)
    putq.put('Hello from Python!')

Unfortunately on the MQ side the request arrives with the user credentials of the virtual linux box user which results in the error message

    pymqi.MQMIError: MQI Error. Comp: 2, Reason 2035: FAILED: MQRC_NOT_AUTHORIZED

How can I tell the queue_manager to use the user/password I have defined in the snippet and not the user of the virtual linux box?

**Comment by JoshMcMQ** [comment]
What is the output of this command:

```
DIS  QMGR CONNAITH
```

If `CONNAUTH` has a value then run this command inserting the value:

```
DIS AUTHINFO(value from above)
```

**Comment by Tom18** [comment]
> What is the output of this command:
> 
> ```
> DIS QMGR CONNAUTH
> ```
> 
> If `CONNAUTH` has a value then provide the output of this command inserting the value:
> 
> ```
> DIS AUTHINFO(value from above) ALL
> ```

Sorry, but where do I have to put this command within python / pymqi? As I said, I'm quite new to the topic.

**Comment by JoshMcMQ** [comment]
That is a command the MQ Admin should execute in `runmqsc`.

**Comment by chughts** [comment]
I don't think that you are correct. In the code that you have shown, the MQ side will arrive with the credentials you have passed in the code. The most likely explanation for the MQRC_NOT_AUTHORIZED error is that that user does not have read / write permissions to the queue you are trying to write to.

**Comment by Tom18** [comment]
> I don't think that you are correct. In the code that you have shown, the MQ side will arrive with the credentials you have passed in the code. The most likely explanation for the MQRC_NOT_AUTHORIZED error is that that user does not have read / write permissions to the queue you are trying to write to.

Our MQ-Admins have already checked that the request arrives with the boxuser instead of the user/password parameters I pass in. And they have checked, that my user credentials are configured to have read/write permissions

**Comment by JoshMcMQ** [comment]
If they do not have connauth enabled with adoptctx(yes) then it makes no differences what you specify.  See my earlier request for more info.

**Comment by dsuch** [comment]
I think the ticket can be closed due to inactivity - thanks everyone for your participation.
