### ISSUE TITLE
pymqi is not compatible with 9.1.3 of the MQ C Client.

### ISSUE THREAD

**Issue by chughts** [dsuch/pymqi#129]
This has taken us a while to isolate as it appears that pip is caching the .so file that pip install of pymqi builds, even in virtual environments. ie in the past we built with 9.1.1 and pymqi 1.9.2 and the .so file from that install lingers so that it isn't actually rebuilt in newer virtual machines when pip installing pymqi 1.9.2

Which meant that on our development machines where we had been working with 9.1.1 or 9.1.2 all  is fine when we moved onto 9.1.3, but on our clean production machines it isn't. 

If you have a clean machine with a clean virtual environment and version 9.1.3 of the MQ Client then there is a mismatch in the MQCD length which causes a size incompatibility error in the connx code. 

In the 9.1.3 client the `cmcxc.h` file has 

````
#if defined(MQ_64_BIT)
 #define MQCD_LENGTH_12                 1992
#else
 #define MQCD_LENGTH_12                 1944
#endif
#if defined(MQ_64_BIT)
 #define MQCD_CURRENT_LENGTH            1992
#else
 #define MQCD_CURRENT_LENGTH            1944
#endif
````

In pymqi the file `CMQXC.py` the code 

````
# 64bit
if calcsize("P") == 8:
    MQACH_LENGTH_1 = 72
    MQACH_CURRENT_LENGTH = 72
    MQCD_LENGTH_4 = 1568
    MQCD_LENGTH_5 = 1584
    MQCD_LENGTH_6 = 1688
    MQCD_LENGTH_7 = 1792
    MQCD_LENGTH_8 = 1888
    MQCD_LENGTH_9 = 1912
    MQCD_LENGTH_10 = 1920
    MQCD_LENGTH_11 = 1984
else:
    MQACH_LENGTH_1 = 68
    MQACH_CURRENT_LENGTH = 68
    MQCD_LENGTH_4 = 1540
    MQCD_LENGTH_5 = 1552
    MQCD_LENGTH_6 = 1648
    MQCD_LENGTH_7 = 1748
    MQCD_LENGTH_8 = 1840
    MQCD_LENGTH_9 = 1864
    MQCD_LENGTH_10 = 1876
    MQCD_LENGTH_11 = 1940

MQCD_CURRENT_LENGTH = MQCD_LENGTH_11
````
needs updating to 

````
# 64bit
if calcsize("P") == 8:
    MQACH_LENGTH_1 = 72
    MQACH_CURRENT_LENGTH = 72
    MQCD_LENGTH_4 = 1568
    MQCD_LENGTH_5 = 1584
    MQCD_LENGTH_6 = 1688
    MQCD_LENGTH_7 = 1792
    MQCD_LENGTH_8 = 1888
    MQCD_LENGTH_9 = 1912
    MQCD_LENGTH_10 = 1920
    MQCD_LENGTH_11 = 1984
    MQCD_LENGTH_12 = 1992
else:
    MQACH_LENGTH_1 = 68
    MQACH_CURRENT_LENGTH = 68
    MQCD_LENGTH_4 = 1540
    MQCD_LENGTH_5 = 1552
    MQCD_LENGTH_6 = 1648
    MQCD_LENGTH_7 = 1748
    MQCD_LENGTH_8 = 1840
    MQCD_LENGTH_9 = 1864
    MQCD_LENGTH_10 = 1876
    MQCD_LENGTH_11 = 1940
    MQCD_LENGTH_12 = 1944

MQCD_CURRENT_LENGTH = MQCD_LENGTH_12
````

and in `__init__.py` 

````
class CD(MQOpts):
    """CD(**kw)
    Construct a MQCD Structure with default values as per MQI. The
    default values may be overridden by the optional keyword arguments
    'kw'."""

    # The MQCD_VERSION & MQCD_LENGTH_* we're going to use depend on the WMQ
    # version we had been compiled with but it is not known on Python side
    # until runtime so set it once here when first importing pymqi
    # (originally written by Brent S. Elmer, Ph.D. (mailto:webe3vt@aim.com)).

    if '8.0.0' in pymqe.__mqlevels__:
        _mqcd_version = CMQXC.MQCD_VERSION_11
        _mqcd_current_length = CMQXC.MQCD_LENGTH_11
````

changed to 
````
class CD(MQOpts):
    """CD(**kw)
    Construct a MQCD Structure with default values as per MQI. The
    default values may be overridden by the optional keyword arguments
    'kw'."""

    # The MQCD_VERSION & MQCD_LENGTH_* we're going to use depend on the WMQ
    # version we had been compiled with but it is not known on Python side
    # until runtime so set it once here when first importing pymqi
    # (originally written by Brent S. Elmer, Ph.D. (mailto:webe3vt@aim.com)).

    if '9.1.3' in pymqe.__mqlevels__:
        _mqcd_version = CMQXC.MQCD_VERSION_12
        _mqcd_current_length = CMQXC.MQCD_LENGTH_12

    elif '8.0.0' in pymqe.__mqlevels__:
        _mqcd_version = CMQXC.MQCD_VERSION_11
        _mqcd_current_length = CMQXC.MQCD_LENGTH_11

    elif
````

**Comment by chughts** [comment]
We can fix, if you will accept the pull request.

**Comment by SeyfSV** [comment]
Hi @chughts ,
Please check this [version](https://github.com/SeyfSV/pymqi/commit/01fb071c3ea8a1d194d5d0f0901b66b19aaca696)
I'll create PR from it, if it works. I checked it by tests on versions 2.7, 3.6 and 3.7.
By default I use `MQCD_VERSION_6` as defined in cmcxc.h:
'''
 #define MQCD_DEFAULT {""},\
                      MQCD_VERSION_6,\
'''
If you need another version, you should use `CD(Version=CMQXC.MQCD_VERSION_12)` for example

**Comment by gowdhammurthi** [comment]
Is there any possibility for making pymqi compatible with mq client version 9.1.3 anytime soon? 
Thanks

**Comment by chughts** [comment]
I have not had a chance to try out the fix provided by @SeyfSV , but it is on my radar, and I will try it out soon.

**Comment by SeyfSV** [comment]
Hi @gowdhammurthi, do you really use new MQCD (or other) fields?
If no, then just try to define CD as:
```
cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
```

**Comment by gowdhammurthi** [comment]
Hai @SeyfSV  @chughts, Sorry for my late reply. I have tried the above still, I get the same error. Even in the CMQXC.py file there is no attribute with the expected size 1992. I think we have to amend the code for bringing compatibility with the latest version. Thanks!

**Comment by JoshMcMQ** [comment]
Can you provide a minimal reproducible sample?

**Comment by gowdhammurthi** [comment]
Hi, I am currently using MQ_CLIENT 9.1.2 and it works well in all environments. At the same time, I will work on bringing a repoducible sample.

**Comment by SeyfSV** [comment]
@gowdhammurthi , I checked this [versoin](https://github.com/SeyfSV/pymqi/commit/01fb071c3ea8a1d194d5d0f0901b66b19aaca696) with client 9.1.3 - its works. Did you try it.
And I confirm that using Version does not solve issue on current pymqi version

**Comment by chughts** [comment]
@SeyfSV I have now built and run with the branch - https://github.com/SeyfSV/pymqi/tree/mqcd-913/code/pymqi - and I can set the Version in the CD constructor. Although as you also have the 913 changes the empty CD constructor also works.

**Comment by dsuch** [comment]
Hello @SeyfSV and @chughts,

I will have a couple of days now during which I could release a new version of PyMQI. I know that @SeyfSV has a few patches in his branches.

Is there anything you would like me to merge in to put out a release afterwards?

Regards.

**Comment by chughts** [comment]
@dsuch nothing immediate.

**Comment by gowdhammurthi** [comment]
@SeyfSV @chughts @dsuch , Thank you And I apologize for my late reply, The application is running inside docker. I cannot choose which version to opt for. It pulls and runs with the latest one. So, I don't think I would be able to use those options. As soon as the changes get merged. I would use 9.1.3 client version.

**Comment by reneverheij** [comment]
I'm experiencing the same issue, and I'd like to know when this fix will be released. Could someone please comment?
_Thanks_

**Comment by JoshMcMQ** [comment]
@reneverheij see https://github.com/dsuch/pymqi/issues/139, 1.9.3 was released last week.

**Comment by gowdhammurthi** [comment]
Pymqi 1.9.3 works with mqv9.1.3 without any issue. I have tested. Thanks for the release.
