### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by exhuma** [dsuch/pymqi#13]
I've come across the following commit: https://github.com/sky-chen/pymqi/commit/6807dff5b513639b33455939b94006f3caa6ade9

It looks okay to me (I have not tested it yet).

Any comments on that one? Or plans when this can be integrated for Python3 support? From what I can tell, it should even be backwards-compatible to probably even as far back as Python 2.6.

**Comment by sky-chen** [comment]
So far it seems to be working well for our internal project, but I haven't run through a test either. But if you encounter any problem, I'll happy to help.

**Comment by exhuma** [comment]
Good to know. I'm currently waiting to get a hand on header files form the guys in our company who installed the service. My last try gave me problems as they are Windows headers.

The guy who should have the Linux headers is currently on holiday. Waiting for his return.

In the meantime: did you run into any trouble compiling the extension? Just su I can mentally prepare for whatever happens when I get the headers ^_^

**Comment by sky-chen** [comment]
So far, no. Not sure about Windows though, never try it under Windows.

**Comment by Rollmops** [comment]
Hey,

we recently stumbled over this great package as we were searching for a possibility to send and receive messages from and to mqs queues in Python.
Unfortunately we are using Python3 and so we are not able to use this great package (at least from Pypi at the moment).

Are there any plans to officially release the current trunk with including the Python3-Port. The version from pypi (1.5.4) is only for Python2

Greetings!

**Comment by exhuma** [comment]
As an update for my last message:

We have currently abandoned this type of message queues. I got some new header files in the meantime, but I was still unable to compile. I was missing dependencies which are not officially available in the Ubuntu repositories. Given that we have a fairly strict policy about 3rd party packages on our servers, this was a blocker. :(

**Comment by dsuch** [comment]
Hello,

all of our effort now is directed towards Zato - our main product and project - it's an API integration platform in Python that makes use of PyMQI in supporting WebSphere MQ, including seamless integration with JMS applications.

* https://zato.io/docs/progguide/examples/jms-wmq.html
* https://zato.io/docs/web-admin/channels/jms-wmq.html
* https://zato.io/docs/web-admin/outgoing/jms-wmq.html

We will eventually make Zato support Python 3.x and that will mean porting all of its dependencies if required, including PyMQI.

However, there is no timeline for it and if you now require PyMQI to work with Python 3.x I encourage you to connect with me on dsuch@zato.io to discuss the terms of a commercial contract under which this can be done and released in a new PyMQI version.

Thanks!

**Comment by dsuch** [comment]
Closing in favour of #60.
