### ISSUE TITLE
Connect to qmgr with user and password issue

### ISSUE THREAD

**Issue by xodat2** [dsuch/pymqi#130]
Hello,
I'm trying to connect to qmgr as a different user.

user = 'technical_user'
password = 'passwd'
qmgr.connect_with_options(queue_manager, cd, sco, user=user, password=password)

Error is: Reason 2035: FAILED: MQRC_NOT_AUTHORIZED

When I check logs it seems that it's trying to authenticate with my local pc user which is running a script:

`12/09/2019 11:21:46 - Process(3252.1715) User(MQMAdmin) Program(amqzlaa0.exe)   `
`                      Host(HOSTNAME) Installation(Installation1)            `
`                      VRMF(8.0.0.4) QMgr(qmgr)                                  `
`                                                                                `
`AMQ8077: Entity 'MY_PC_USER' has insufficient authority to access object        `
`'qmgr'.                                                                         `
`                                                                                `
`EXPLANATION:                                                                    `
`The specified entity is not authorized to access the required object. The       `
`following requested permissions are unauthorized: connect                       `
`ACTION:                                                                         `
`Ensure that the correct level of authority has been set for this entity against `
`the required object, or ensure that the entity is a member of a privileged      `
`group.                                                                          `
`----- amqzfubn.c : 518 -------------------------------------------------------- `
`12/09/2019 11:21:46 - Process(2140.1363) User(MQMAdmin) Program(amqrmppa.exe)   `
`                      Host(HOSTNAME) Installation(Installation1)            `
`                      VRMF(8.0.0.4) QMgr(qmgr)                                  `
`                                                                                `
`AMQ9557: Queue Manager User ID initialization failed for 'technical_user'.      `
`                                                                                `
`EXPLANATION:                                                                    `
`The call to initialize the User ID 'technical_user' failed with CompCode 2 and  `
`Reason 2035.                                                                    `
`ACTION:                                                                         `
`Correct the error and try again.                                                `
`----- cmqxrsrv.c : 2321 ------------------------------------------------------- `

I've tried using libs from mq server 8.0.0.6 , 8.0.0.11 and mq client 8.0.0.9
My pymqi version is 1.9.2

I'm able to connect to qmgr using mq explorer with technical_user

![image](https://user-images.githubusercontent.com/42867205/64772361-c0c8dd00-d550-11e9-889e-8ca4307b73a1.png)

![image](https://user-images.githubusercontent.com/42867205/64773248-4f8a2980-d552-11e9-8de4-acfe5868bcba.png)

**Comment by xodat2** [comment]
Hello,
I've managed to solve it with workaround,
I just simply right click -> run as other user -> technical_user

**Comment by JoshMcMQ** [comment]
Change ADOPTCTX to YES on the queue manager to actually fix it.

**Comment by xodat2** [comment]
Hello Josh,
It fixed the issue, thank you very much!
