### ISSUE TITLE
Problem to install pymqi

### ISSUE THREAD

**Issue by rafaelrosa** [dsuch/pymqi#131]
Hello friends,

I am trying to install pymqi via pip, but I am facing a problem.

The version of Python I am using is Python 3.6.8.

The problem is: 
```
>  pip3 install pymqi

Collecting pymqi
  Using cached https://files.pythonhosted.org/packages/15/d9/b5babbd3f296b47a9d8bca417ca185ede9e8780ce4ca6b66bbf2dd1b7880/pymqi-1.9.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/rafael/project/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jkhuv2oy/pymqi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jkhuv2oy/pymqi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-jkhuv2oy/pymqi/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jkhuv2oy/pymqi/setup.py", line 156, in <module>
        raise Exception('MQ libraries could not be found')
    Exception: MQ libraries could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tried as sudo, but I got same error. Another friend tested the command "pip3 install pymqi" and got the same error too.

Could you help me, please?

Regards,

Rafael.

**Comment by JoshMcMQ** [comment]
You either need a mq client installed or you need to extract the
redistributable mq client.   If using the redist client or not seeing the
installed client as the primary on unix you need to set LD_LIBRARY_PATH to
point to the correct libraries.

Google MQC91 for download links for both types of clients.

**Comment by rafaelrosa** [comment]
Hello Josh,

Yes, I read about the client in other pages.

But I already have a dedicated queue server (in my machine, I am using a IBM MQ Docker image).

I would like just to connect to the queue, because the idea is to make a Docker image with my python app and the dependencies.

Even in this scenario, do I need the client? Because I saw some clients with GUI, but my app is backend only.

Regards.

**Comment by dsuch** [comment]
@rafaelrosa - In email, I asked you to look up past issues in GitHub. All of what you are inquiring about has been discussed in the past and everything that @JoshMcMQ says is correct. 

I am closing the ticket, there is nothing more that can be added here.
