### ISSUE TITLE
Message descriptor format while browse messages

### ISSUE THREAD

**Issue by rohitjain31** [dsuch/pymqi#132]
I am trying to fetch message Id while browsing messages from a queue.
in message descriptor, i am getting below values

![image](https://user-images.githubusercontent.com/14266765/66543905-48a40600-eb54-11e9-8062-c5d69983ea87.png)

not sure, why i am getting MsgId and CorrelId in this format and how to convert this to relevant format.
Could you please help me out with this?

**Comment by rohitjain31** [comment]
I was trying to convert bytes to string and got confused. Converting byte to hex resolved that.
Thanks.

**Comment by JoshMcMQ** [comment]
While the first portion of queue manager generated ids can be translated to ASCII characters if originating on unix/windows or EBCDIC if originating on mainframe, the rest of id is just unique bytes.  No character conversion is done by MQ on these fields.
