### ISSUE TITLE
Set a custom header on an MQ message

### ISSUE THREAD

**Issue by supercao** [dsuch/pymqi#134]
Hi all,
Now I need to put the msg with custom header, like as Java below:
MQMessage mqMessage = new MQMessage();
MqMessage.format = CMQC.MQFMT_STRING;
# custom header:
msg.setStringProperty("MyStringProperty", "My Year Of Birth");
For this issue, how should to do?
Thanks for you guys help!

**Comment by SeyfSV** [comment]
Hi,
Check this:
```
qmgr = pymqi.connect('', CHANNEL_NAME, CONN_INFO)

messageHandle_put = pymqi.MessageHandle(qmgr)
messageHandle_put.properties.set(b'MyStringProperty', 'My Year Of Birth')  # Property name should be byte string

pmo = pymqi.PMO(Version=pymqi.CMQC.MQPMO_VERSION_3)  # Version 3 required for setting properties
pmo.OriginalMsgHandle = messageHandle_put.msg_handle

queue_put = pymqi.Queue(qmgr, QUEUE_NAME, pymqi.CMQC.MQOO_OUTPUT)
queue_put.put(b'', None, pmo)

queue_put.close()
qmgr.disconnect()
```
Also you can check code in `tests/test_message_property.py`

**Comment by supercao** [comment]
Hi SeyfSV,
Thanks for yr help! It works well!
