### ISSUE TITLE
Publish new release to PyPI

### ISSUE THREAD

**Issue by paulpozicheun** [dsuch/pymqi#139]
Hello,

On PyPI, last release 1.9.2 was published on March 12, 2019
https://pypi.org/project/pymqi/

This project has evolved a lot since then.

Would it be possible to publish a new release.

Thanks a lot.

Kind Regards,

P.Pozicheun

**Comment by dsuch** [comment]
Yes, this is a good idea - I am waiting on #133 and once this is confirmed, I will release a new version.

**Comment by dsuch** [comment]
This is done, version 1.9.3 has been now released.

**Comment by paulpozicheun** [comment]
Thanks a lot for this new release
I'm gonna use it soon
