### ISSUE TITLE
Pymqi recognizes linux machine username instead of costume username

### ISSUE THREAD

**Issue by liorpk** [dsuch/pymqi#140]
Hi everyone,

I'm trying to use pymqi to connect to a QMGR in client mode, however according to IBM MQ's application logs, the application thinks I'm trying to connect with 'root', which is the centos user I'm trying to connect from, instead of the username I provided as variable.
This is the code I'm trying to execute:

`import pymqi

queue_manager = '****'
channel = '****'
host = '****'
port = '1414'
conn_info = '%s(%s)' % (host, port)

user = 'myusername'
password = 'mypassword'

qmgr = pymqi.connect(queue_manager, channel, conn_info, user, password)

qmgr.disconnect()`

According to the application log, I'm trying to login as 'root', and not as 'myusername'.
If anyone can assist with this issue, it will be much appreciated.
Thank you!

**Comment by JoshMcMQ** [comment]
What version of IBM MQ is the queue manager you connect to? 

What error is logged in the queue manager's  AMQERR01.LOG?

**Comment by liorpk** [comment]
Hi @JoshMcMQ, thanks for your reply.
IBM MQ version: 9.1.0.0.

Error from log:

"Queue Manager User ID initialization failed for 'root'.  

The call to initialize the User ID 'root' failed with CompCode 2 and Reason 2035. If an MQCSP block was used, the User ID in the MQCSP block was '***@***'.  

Correct the error and try again."

**Comment by JoshMcMQ** [comment]
Check the following:
1. `DIS QMGR CONNAUTH`
2. `DIS AUTHINFO(ValueDisplayedInQmgrCONNAUTH) ADOPTCTX`

If `CONNAUTH` is blank or `ADOPTCTX` is `NO` then the behavior is as expected.

1. If `CONNAUTH` is blank then CONNAUTH is disabled and MQ will ignore the MQCSP which contains `myusername` and `mypassword`.
2. If `ADOPTCTX` is `NO` then MQ will only authenticate the MQCSP user but will not adopt the user's context for further authorization checks. 

I will also note there there are a number of defects fixed since 9.1.0.0 came out, I would recommend you update to the latest maintenance which is 9.1.0.4.

**Comment by liorpk** [comment]
Thanks @JoshMcMQ 

When running `DIS QMGR CONNAUTH`, it is indeed blank.
How can I enable it?

**Comment by JoshMcMQ** [comment]
Is this just a stand alone test queue manager or does it have other apps connecting to it

**Comment by liorpk** [comment]
It has other apps connecting to it.

**Comment by JoshMcMQ** [comment]
Does it have other apps connecting to SVRCONN channels?

**Comment by liorpk** [comment]
Yes, to the same channel I am trying to connect to as a matter of fact.

**Comment by JoshMcMQ** [comment]
Is the queue manager on windows? 

Does you run `REFRESH  SECURITY  TYPE(CONNAUTH)` or restart the queue manager after updating the `QMGR CONNAUTH` attribute?

**Comment by liorpk** [comment]
Yes, it is on windows, and I refresh the auth service via MQ explorer ("Refresh Authorization Service" & "Refresh Connection Authentication").

**Comment by JoshMcMQ** [comment]
Is `myusername@mypcname` the value you pass as `user = 'myusername'`

**Comment by liorpk** [comment]
No, I pass this as user = 'myusername@mypcname'

**Comment by liorpk** [comment]
@JoshMcMQ , you know what, this was the issue. I changed it to `user = 'myusername' ` and it is now finally working!!!!
Thank you so much Josh for your help!!! I really appreciate it!

**Comment by JoshMcMQ** [comment]
Note that CONNAUTH config will always require **ANY** password sent be valid,  with CONNAUTH disabled any password including an invalid password would be ignored.

**Comment by JoshMcMQ** [comment]
@liorpk ok to close?

**Comment by liorpk** [comment]
Yes, thank you very much!
