### ISSUE TITLE
Problems running sample code with pymqi 1.9.3 and MQ 9.1.3 libs

### ISSUE THREAD

**Issue by mrpilgrim** [dsuch/pymqi#142]
Hi,
Just trying pymqi for the first time. I installed on my machine via pip using the latest MQ libs, V9.1.3 and python 3.7.3
I can run the "Connecting in client mode" sample code successfully so pymqi appears to be working correctly. However, when I run the "How to display channels" code I get the following error:
`Traceback (most recent call last):
  File "mqtest.py", line 23, in <module>
    response = pcf.MQCMD_INQUIRE_CHANNEL(args)
  File "/home/simon/pymqi/lib/python3.7/site-packages/pymqi/__init__.py", line 2504, in __call__
    rv = pymqe.mqaiExecute(qm_handle, CMQCFC.__dict__[self.__name], *args)
pymqe.error: Value 'SYSTEM.*' for key 3501 is not a long, bytes nor a pymqi.ByteString instance`

Am I doing something wrong ?

**Comment by dsuch** [comment]
PyMQI generally works with bytes objects - it mimics the lower level MQ APIs in that.

What if you provide b'SYSTEM.*' on input?

**Comment by JoshMcMQ** [comment]
@dsuch, I would agree that this should be updated:

```
prefix = "SYSTEM.*"
```

It should be:

```
prefix = b'SYSTEM.*'
```

I have sample code running with pymqi 1.9.2 and Python 3.7 and I had to pass in for example:

```
cd.ChannelName= b'TEST.CHL'
```

Does that mean with Python 3.7 all the examples need to be updated to have sample strings cast as byte strings?

**Comment by dsuch** [comment]
That could be done but probably the better way would be to auto-encode Unicode objects to bytes ones. 

The only caveat is that we would have to assume what encoding to use. UTF-8 will be probably safe for most cases but people still do use other encodings. This is a local encoding, the one uses in his or her editor, nothing to do with MQ really.

Thinking aloud about it, perhaps the default encoding in such cases could be simply an attribute of QueueManager objects then - defaulting to UTF-8 but customizable by users?

**Comment by JoshMcMQ** [comment]
Can it be done in a way to continue to work with code already passing in byte strings?

**Comment by dsuch** [comment]
Yes, if someone provides a bytes object on input then it will be used as is.

**Comment by JoshMcMQ** [comment]
That sounds like a good solution, it allows people to override the default encoding to use for simple strings or provide there own byte encoded strings as the wish, but will allow most people to pass in a simple strings without the need to worry about the encoding.

I think you opened https://github.com/dsuch/pymqi/issues/95 to track the same idea back in March.

**Comment by mrpilgrim** [comment]
Just to confirm that it now works following Dariusz's suggestion.

I think it would be worthwhile adding something in the documentation outlining that these are byte objects. The code could be changed as well since Python 2 has a pseudo-type so the b' format works .

**Comment by dsuch** [comment]
Thanks @mrpilgrim - per the discussion above, I think we will just make it possible to provide Unicode objects on input.

@JoshMcMQ - you are right, let us close this ticket in favour of the other one.
