### ISSUE TITLE
SystemError returned by pymqe_MQINQMP when property is not available

### ISSUE THREAD

**Issue by paulpozicheun** [dsuch/pymqi#146]
Hello there,

I'm trying to retrieve a property from a message, accepting the fact that property doesn't exists
```python
try:
    retry_counter = get_msg_h.properties.get(b"RetryCounter")
except pymqi.MQMIError as e:
    # Error is accepted when property doesn't exist, otherwise raise the exception
    if not (e.comp == pymqi.CMQC.MQCC_FAILED and e.reason == pymqi.CMQC.MQRC_PROPERTY_NOT_AVAILABLE):
    raise
```

This code was working fine with release 1.9.2 but fails badly in release 1.9.3
```SystemError: <built-in function MQINQMP> returned NULL without setting an error```

Problem comes from method pymqe_MQINQMP() when call to MQINQMP() fails, the property_type is not set and returned value is NULL
https://github.com/dsuch/pymqi/blob/master/code/pymqi/pymqe.c#L1308

We are then getting a system error instead of being able to treat the error contained in comp_code and comp_reason.

Why not act as before when property_type is unknown :
```C
default:
    #if PY_MAJOR_VERSION==2
      rv = Py_BuildValue("(s#lll)",
    #else
      rv = Py_BuildValue("(y#lll)",
    #endif
    (char*)value,
    (long)data_length,
    (long)comp_code, (long)comp_reason);
    break;
```
and let the upper layer deal with the error ?

Thanks a lot for your help on this.

Kind regards,

Paul

**Comment by JoshMcMQ** [comment]
@SeyfSV can you review the changes you made to see if this can be addressed while keeping the same level of new functionality?

**Comment by SeyfSV** [comment]
Hi @paulpozicheun,

It is strange because there is the test `test_message_properties_nonexist` in `code/tests/test_message_property.py` that pass successfully.
Can you run it?
Can you provide some info about your environment?

**Comment by paulpozicheun** [comment]
Hello @SeyfSV , thanks for your answer

No need to run the tests.
In your test ```test_message_properties_nonexist```, you are checking that property does not exist but with property type ```pymqi.CMQC.MQTYPE_NULL``` which is part of your switch/case.

If you do the same with property type ```pymqi.CMQC.MQTYPE_AS_SET``` (which is the answer I got from MQINQMP() method), you will have the same error as me.

Tell me if you need some more info.

**Comment by paulpozicheun** [comment]
@SeyfSV, I found a workaround for this issue.

If I initialize the property type with the expected one, then MQINQMP() is not modifying it and your code is doing the conversion of the returned value
```retry_counter = get_msg_h.properties.get(b"RetryCounter", property_type=pymqi.CMQC.MQTYPE_INT32)```

To me, remains a problem if 
* the property type has not been declared when property is created in MQ server
* the property type is not given in the arguments of pymqe_MQINQMP() method
You then have a usage of un-initialized variable.

Kind regards,
Paul

**Comment by SeyfSV** [comment]
@paulpozicheun, you right, issue occurs because `MQTYPE_AS_SET` is not in switch/case and `property_type` does not changed because error `MQRC_PROPERTY_NOT_AVAILABLE` occurs.
Please, try this version 32e6d236d245b10e167f3381d040bbe07b445abd. I hope it solve all problems.

**Comment by dsuch** [comment]
Hello @SeyfSV - could you please contact me via email? Mine is pymqi at m.zato.io. Thanks.

**Comment by paulpozicheun** [comment]
Thanks @SeyfSV , I will use it asap as to me it will solve the issue.
For the moment, the workaround works fine for me.
Feel free to close this issue when you want it.

**Comment by paulpozicheun** [comment]
Sorry, mis-click.

**Comment by SeyfSV** [comment]
Changes commited b69aa78e6d072df3a4b2137199960327463fd7fb to branch `gh146-mqtype_as_set`
