### ISSUE TITLE
Python 3 style string found but not allowed here | Auto-convert parameters to bytes Issue

### ISSUE THREAD

**Issue by nileshlamjane** [dsuch/pymqi#152]
Same as [https://github.com/dsuch/pymqi/issues/95]

pymqi 1.9.3 on Python 3.7.3

Sample used from Documentation
Error:
```
Traceback (most recent call last):
  File "C:\SOAStack\ESB\Tools\Reprocessing\src\test.py", line 14, in <module>
    queue.put(message)
  File "C:\Python37-32\lib\site-packages\pymqi\__init__.py", line 1710, in put
    check_not_py3str(msg)  # Python 3 bytes check
  File "C:\Python37-32\lib\site-packages\pymqi\__init__.py", line 144, in check_not_py3str
    raise TypeError("Python 3 style string found but not allowed here: '{0}'. Convert to bytes.".format(var))
TypeError: Python 3 style string found but not allowed here: 'Hello from Python!'. Convert to bytes.
```

**Comment by SeyfSV** [comment]
Hi @nileshlamjane 
Prepend 'Hello from Python!' with **b**: b'Hello from Python!'
It's should be byte string:
> TypeError: Python 3 style string found but not allowed here: 'Hello from Python!'. Convert to bytes.

**Comment by nileshlamjane** [comment]
Well, i believe this part to convert to byte is done in pymqi package as part of fix for issue 95.

**Comment by dsuch** [comment]
I think uou are right @nileshlamjane - I will have a look. Thanks.

**Comment by dsuch** [comment]
It turns out that the auto-encoding to bytes part is implemented only for PCF commands rather than everywhere in the codebase.

@SeyfSV - would you have time to implement it if I told you what was needed?

Essentially, it is about placing calls to **ensure_bytes** in crucial places and making sure that **QueueManage.default_encoding** is employed there.

@nileshlamjane - for now, the correct approach is what @SeyfSV says but ultimately, yes, this will happen automatically.

**Comment by SeyfSV** [comment]
Hi,
Yes, I have some time.
Am i right, that replacing `ensure_not_unicode(value)` to `value = ensure_bytes(value, 'utf-8')` would be enough?

**Comment by dsuch** [comment]
Yes, that is the idea but instead of hardcoding it to utf-8, self.default_encoding should be given on input to ensure_bytes.

**Comment by SeyfSV** [comment]
I am not sure that we should convert all unicode strings.
For example, message body representation depends on CodedCharSetId field, and if we want to convert body we should use CodedCharSetId value for choosing encoding. 
And another case is message property name - its name can be converted with encode('utf-8').
As result every other cases should be checked carefully.

**Comment by dsuch** [comment]
You are right to a degree but the purpose of this auto-conversion is to let people use both Unicode and string objects when they do not care about MQ-level CodedCharSetId or similar things.

E.g. someone has a simple XML file, all ASCII, and we reject it now because it is a Unicode object rather than bytes.

In other words, if someone wants to encode a Unicode object using a particular encoding, they are free to do it. But many people just want to send things and be done with it.

In this way we deal with a common case while still leaving room for people to encode data themselves.

**Comment by SeyfSV** [comment]
Ok, should we explicitly set CodedCharSetId to 1208?

**Comment by dsuch** [comment]
I am not sure which place in the code you mean? This topic started in the context of put operations, are we still discussing the same subject?

**Comment by SeyfSV** [comment]
Yes, I am about put method.
If we want to put utf-8 message to queue we should have MQMD.CodedCharSetId = 1208.
Also I found this thing:
> Character data in MQMD and the other MQ data structures that are parameters on calls must be in the character set of the queue manager. This is defined by the queue manager's CodedCharSetId attribute

It's means, that we can not encode parameters value with utf-8 if queue manager's CodedCharSetId attribute not 1208.
You propose to use `self.default_encoding` for encoding, but it can be differ than queue manager's CodedCharSetId.
As workaround we can inquire it's value during connection to QMGR.

**Comment by dsuch** [comment]
Yes, in that case, it makes sense to set MQMD.CodedCharSetId to 1208 if default encoding is UTF-8.

Something like in QueueManager.__init__:

```python
self.default_encoding = default_encoding
if self.default_encoding.replace('-','').lower() == 'utf8':
  self.default_charset_id = 1208
else:
  self.default_charset_id = SOME_CONSTANT_DEFINED_BY_MQ
```

Then, the value of self.default_chaset_id would be used in MQMD unless it was overwritten by users from the default value.

As for interrogating the queue manager, sounds nice but I would not do it actually, there are many environments that forbid any such inquiries, allowing clients only to put or get to and from selected objects.

**Comment by SeyfSV** [comment]
I have new questions :) :
* should we support python 2.7?
* early we consider about put method and we decided to encode message to utf-8. What about get method and decoding received bytes to utf-8 (it is about someone with XML)? What encoding should we use, should we use encoding from MQMD header?
* what about non-unicde (non utf-8) py files? should we support it? (Python 2.7, Python 3.x)

**Comment by dsuch** [comment]
Yes, we are likely to support Python 2.7 for many years ahead.

I would support UTF-8 only and only in put operations, nothing else, while still letting programmers use other encodings, in put or other operations, like it is the case today.

**Comment by SeyfSV** [comment]
Finally I got this code:
```
        if not isinstance(msg, bytes):
            if (
                (sys.version_info >= (3,) and isinstance(msg, str))  # Python 3 string is unicode
                or
                (sys.version_info < (3,) and isinstance(msg, unicode)) # Python 2.7 string can be unicode
              ):  
                msg = msg.encode('utf-8')
                m_desc.CodedCharSetId = 1208
                m_desc.Format = CMQC.MQFMT_STRING
            else: 
                error_message = 'Message type is {0}. Convert to bytes.'
                raise TypeError(error_message.format(type(msg))) 
``` 
I checked it with Python 2.7 and 3.7 and putting strings in different encodings (unicode and national), bytes and object.
Now I plan to add tests to cover all this cases.
@nileshlamjane and all, please, check this branch with your code.

**Comment by dsuch** [comment]
Looks good. I would only add module-level objects to represent whether it is Python 3 or 2 and make use of them in this and other code, e.g.

```
is_py2 = sys.version_info.major == 2
is_py3 = sys.version_info.major == 3
```

And then:

```
if (is_py3 and isinstance(msg, str)) or (is_py2 and isinstance(msg, unicode)):
  ...
```

**Comment by SeyfSV** [comment]
This is not good, because you have to change it when Python 4 comes up.

**Comment by SeyfSV** [comment]
@dsuch, I propose to limit changes for this issue to payload conversion.
For futher investigation I need a case, that does not work in current pymqi state.

**Comment by dsuch** [comment]
Yes, I agree that it should be limited to payload only but I thought that what the ticket's only scope?

**Comment by SeyfSV** [comment]
Issue - yes, discussion - no. 
You mention `ensure_bytes` function, that commonly used for properties encoding, and I did not change it. I fixed only put and put1 function.

**Comment by dsuch** [comment]
Alright @SeyfSV - we can start with put and put1 for now only. Thanks.

**Comment by dsuch** [comment]
Hi @SeyfSV - now that PR #161 is merged, I think a new minor release is in order?

**Comment by dsuch** [comment]
@SeyfSV - I pushed a few commits in preparation of the 1.10 release. Can you please run all the tests on your end to confirm that everything works as expected? Thanks.

**Comment by SeyfSV** [comment]
Checked with Python 2.7, 3.6 and 3.7 - works as expected.

**Comment by dsuch** [comment]
Hello,

I have just uploaded PyMQI 1.10 to PyPI. 

It will automatically convert Unicode objects to bytes, as in the usage examples.

@nileshlamjane - please take a look at it.

@SeyfSV - thanks again for your assistance.

**Comment by dsuch** [comment]
For reference - I added [a usage example](https://dsuch.github.io/pymqi/examples.html#sending-unicode-data-vs-bytes) along with explanation of how to specify one's own default bytes encoding and CCSID.

**Comment by SeyfSV** [comment]
@dsuch close?

**Comment by dsuch** [comment]
Thanks, yes.

**Comment by akhiilkasare** [comment]
How can we solve this issue

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\ADMINI~1\AppData\Local\Temp\2/ipykernel_3112/3203162512.py in <module>
     26 
     27 qmgr = pymqi.QueueManager(None)
---> 28 qmgr.connect_with_options(queue_manager, cd, sco)
     29 
     30 put_queue = pymqi.Queue(qmgr, queue_name)

c:\python37\lib\site-packages\pymqi\__init__.py in connect_with_options(self, name, *args, **kwargs)
   1608                 cd.Version = CMQC.MQCD_VERSION_7
   1609 
-> 1610             cd = cd.pack()
   1611         else:
   1612             cd = None

c:\python37\lib\site-packages\pymqi\__init__.py in pack(self)
    307                     args.append(x)
    308             else:
--> 309                 ensure_not_unicode(v)  # Python 3 bytes check
    310                 args.append(v)
    311 

c:\python37\lib\site-packages\pymqi\__init__.py in ensure_not_unicode(value)
    175     if is_unicode(value):
    176         msg = 'Python 3 style string (unicode) found but not allowed here: `{0}`. Convert to bytes.'
--> 177         raise TypeError(msg.format(value))
    178 
    179 def ensure_bytes(s, encoding='ascii'):

TypeError: Python 3 style string (unicode) found but not allowed here: `10.94.135.xxx(73xx)`. Convert to bytes.
