### ISSUE TITLE
Import pymqi -> Symbol not found: _MQBACK

### ISSUE THREAD

**Issue by alephnot0** [dsuch/pymqi#154]
I am getting this build error on `import pymqi` on OSX High Sierra.

```
ImportError: dlopen(/Users/{}/homebrew/lib/python3.8/site-packages/pymqi/pymqe.cpython-38-darwin.so, 2): Symbol not found: _MQBACK
  Referenced from: /Users/{}/homebrew/lib/python3.8/site-packages/pymqi/pymqe.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/{}/homebrew/lib/python3.8/site-packages/pymqi/pymqe.cpython-38-darwin.so
```

Setup information, libraries from IBM's website:

```
➜  mqm pwd
/opt/mqm
➜  mqm ls
README.Client gskit8        java          lib64         msg           swidtag
bin           inc           lib           licenses      samp
➜  mqm echo $LD_LIBRARY_PATH
/opt/mqm/lib64
```

I have also tried reinstalling pymqi, setting DYLD_LIBRARY_PATH, reinstalling python, and upgrading python.

I understand that support is not offered for OSX, but I would appreciate a point in the right direction if you are able to.

There also seems to be a backup method to import pymqe already written in.  If there are any instructions on using that as a workaround, please let me know.

**Comment by dsuch** [comment]
Hello @alephnot0,

I will not be able to help you out with OS X but I am curious about the backup method to import pymqe? Can you tell me what you mean?

Thanks.

**Comment by alephnot0** [comment]
Simply this: https://github.com/dsuch/pymqi/blob/master/code/pymqi/__init__.py#L126-L129

It seems to be hinting that I should be able to use a local dependency myself.

**Comment by dsuch** [comment]
Ah, I see. No, this is a different story. Many years ago PyMQI, instead of being a Python package, was just a group of Python modules and this import is part of an effort to preserve backward-compatibility with various such installations.

It is not that there is no support for OS X - some users here do have the system and may be able to assist you but I just cannot do it personally, that is all.

**Comment by alephnot0** [comment]
Understood, thanks for your time regardless.

**Comment by chughts** [comment]
I use pymqi on Mac (High Sierra and Catalina), with Python 3.7.3, and inside virtualenv environments.  

You show that you have set `$LD_LIBRARY_PATH`, but it should be `$DYLD_LIBRARY_PATH` on a Mac. 

You are going to have to rebuild, but when you `pip install pymqi` make sure that you are not fetching from a local cache, as this will have the incorrectly built `.so` file. I think this becomes `pip --no-cache-dir install pymqi`

**Comment by alephnot0** [comment]
@chughts Thank you, this has now been resolved for me.  I believe that I was re-installing pymqi, but with the cached version.  `--no-cache-dir` was exactly what I needed.

**Comment by SeyfSV** [comment]
Hi @alephnot0, can we close issue?
