### ISSUE TITLE
Unable to connect to the PYMQI Client facing FAILED: MQRC_ENVIRONMENT_ERROR

### ISSUE THREAD

**Issue by alekhya1492** [dsuch/pymqi#155]
am getting the below error while connecting to IBM MQ using library pymqi. ''' Its a clustered MQ channel

Traceback (most recent call last):
  File "postToQueue.py", line 432, in <module>
    qmgr = pymqi.connect(queue_manager, channel, conn_info)
  File "C:\Python\lib\site-packages\pymqi\__init__.py", line 2608, in connect
    qmgr.connect_tcp_client(queue_manager or '', CD(), channel, conn_info, user, password)
  File "C:\Python\lib\site-packages\pymqi\__init__.py", line 1441, in connect_tcp_client
    self.connect_with_options(name, cd, user=user, password=password)
  File "C:\Python\lib\site-packages\pymqi\__init__.py", line 1423, in connect_with_options
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2012: FAILED: MQRC_ENVIRONMENT_ERROR'
''' Please see my code below.

queue_manager = 'quename here' 
channel = 'channel name here' 
host ='host-name here' port = '2333' queue_name = 'queue name here'
conn_info = '%s(%s)' % (host, port) print(conn_info) qmgr =
pymqi.connect(queue_manager, channel, conn_info) queue =
pymqi.Queue(qmgr, queue_name) queue.put(message) print("message sent")
queue.close() qmgr.disconnect() message = 'my message here'
Getting error at the line below

qmgr = pymqi.connect(queue_manager, channel, conn_info)

Added the IBM client to scripts folder as well , using Windows 10 , Python 3.8.1 and IBM Client 9.1 windows client installation image, Below is the log 

| Data Path         :- C:\Python\Scripts\IBM                                  |
| Installation Path :- C:\Python
| Major Errorcode   :- xecF_E_UNEXPECTED_SYSTEM_RC                            |
| Minor Errorcode   :- OK                                                     |
| Probe Type        :- INCORROUT                                              |
| Probe Severity    :- 2                                                      |
| Probe Description :- AMQ6090: MQM could not display the text for error      |
|   536895781.                                                                |
| FDCSequenceNumber :- 0                                                      |
| Comment1          :- WinNT error 1082155270 from Open ccsid.tbl.

**Comment by JoshMcMQ** [comment]
See my comments to your [StackOverflow question](https://stackoverflow.com/questions/59956406/unable-to-connect-to-the-pymqi-client-facing-failed-mqrc-environment-error).

**Comment by SeyfSV** [comment]
Hi @alekhya1492,
Thank you for question, but it is not related to pymqi. SO is better place for it.
I will close it and try to help on SO.
