### ISSUE TITLE
Support with statement for QueueManager and Queue objects

### ISSUE THREAD

**Issue by molnargab** [dsuch/pymqi#160]
`QueueManager` and `Queue` may leak resources.

Consider `queue.put` or another operation throwing an exception, `queue.close` or `qmgr.disconnect` may not be called till garbage collection occurs:
```
    qmgr = pymqi.connect(queue_manager, channel, conn_info)

    queue = pymqi.Queue(qmgr, queue_name)
    queue.put(message)
    queue.close()

    qmgr.disconnect()
```

Adding support for [context managers](https://www.python.org/dev/peps/pep-0343/) (i.e. `with` statement) would avoid this issue: the connection would be open whenever the block is entered, and closed whenever exited (be it the normal or the exceptional case).

This would support code, like the below, where the queue is closed and the queue manager is disconnected upon leaving the block:
```
    with pymqi.connect(queue_manager, channel, conn_info) as qmgr,
          pymqi.Queue(qmgr, queue_name) as queue:
        queue.put(message)
```

**Comment by SeyfSV** [comment]
Hi @molnargab,
I am not the owner, but I think that `pymqi` is just a proxy for calling C functions. Please, look this owner [comment](https://github.com/dsuch/pymqi/issues/104#issuecomment-497815566):

> As for PyMQI - I like the fact that it is low-level because it does not impose any particular programming model to its users but on the other hand, IBM docs are written by humans too.

You are not alone in your wish. You can take a look at this project: [pymqiwm](https://github.com/alekhya1492/pymqiwm).

**Comment by dsuch** [comment]
Hello @molnargab - I like the idea and it makes sense to have something like that.

The question is, seeing as the pymqiwm project, that @SeyfSV linked to, already has this feature, I just wonder if there is anything that PyMQI can do on top of that?

**Comment by Skyler-Altol** [comment]
It should be noted that pymqiwm's main page is listed as archived and is read-only. Am uncertain if someone else has taken up management of it under the new fork listed above, or if it's just that particular user's copy of it.

**Comment by dsuch** [comment]
Mass-closing old tickets.
