### ISSUE TITLE
How do I post an XML request to the pymqi queue?

### ISSUE THREAD

**Issue by Aakaash897** [dsuch/pymqi#162]
I am trying to post a request to one of the queues via pymqi. This requires me to post an XML request. Since the queue.put() takes in data in the form of bytes. I was wondering if there was a workaround for this.

**Comment by JoshMcMQ** [comment]
You can still pass in text, just make sure the md ccsid matches the encoding of the bytes you pass.

**Comment by Aakaash897** [comment]
@JoshMcMQ How can I make sure the ccsid matches?? Because the XML file is have is not a typical xml. doesn not contain the <?XML Version........> tag. Just few tags and the required data

**Comment by JoshMcMQ** [comment]
Look at https://github.com/dsuch/pymqi/issues/152 for more info.   You can try that pull or just replicate what it does in your code.

**Comment by Aakaash897** [comment]
@JoshMcMQ I did give it a try but using the following code. 

```
md = pymqi.MD()
md.CodedCharSetId = 1208
md.Format = CMQC.MQFMT_STRING
```
I end up with this error.

> TypeError: a bytes-like object is required, not '_io.TextIOWrapper'

**Comment by JoshMcMQ** [comment]
Add the b like `b'string'`

**Comment by dsuch** [comment]
Hello @Aakaash897 - your question has almost nothing to do with PyMQI, instead, this is a Python usage question that requires you to understand how to work with bytes on various levels - Python, XML and, eventually, MQ.

Please post it on StackOverflow where at least someone will earn 'reputation' for answering something that is mostly to do with Python.

I am closing this ticket - feel free to reopen though, provided that  you have a specific question about PyMQI rather than general Python ones.

**Comment by dsuch** [comment]
Hi @Aakaash897 - coincidentally, a new version of PyMQI was released today. It is possible that it will solve your case if you still need assistance. Regards.

**Comment by Aakaash897** [comment]
@dsuch Yes, It was a python encoding issue which seems to be ok now after 'byte-conversion'.
Only issue is that, the message that is sent seems to be of '0' length or size after it is posted. 

I have converted to bytes before sending.

**Comment by dsuch** [comment]
@Aakaash897 - it is good to hear that you have it working as far as the bytes / Unicode go.

However, if you would like to discuss the other part of it, the message's size being 0, please open a new ticket.

Please also include a self-contained sample, something that can be executed as-is, in addition to an explanation of what you were expecting.

Thanks.

**Comment by Aakaash897** [comment]
@dsuch Thanks a ton really sir.
