### ISSUE TITLE
__init__() got an unexpected keyword argument 'ccsid'

### ISSUE THREAD

**Issue by leonjza** [dsuch/pymqi#168]
It looks like version 1.10 that was just released introduced a bug when connecting to a queue manager.

The exception bubbles up to:

```python
  File "/usr/local/lib/python3.8/dist-packages/pymqi/__init__.py", line 2457, in connect
    qmgr = QueueManager(None, disconnect_on_exit, bytes_encoding=bytes_encoding, ccsid=default_ccsid)
TypeError: __init__() got an unexpected keyword argument 'ccsid'
```

It seems like `ccsid` is passed from [here](https://github.com/dsuch/pymqi/blob/9a02ee7337fe5cc2a59e5473ad45e2233af8aac9/code/pymqi/__init__.py#L2457) to the `QueuManager` class [here](https://github.com/dsuch/pymqi/blob/9a02ee7337fe5cc2a59e5473ad45e2233af8aac9/code/pymqi/__init__.py#L1239), but the class does not have `ccsid` as a kwarg. I guess the same will happen [here](https://github.com/dsuch/pymqi/blob/9a02ee7337fe5cc2a59e5473ad45e2233af8aac9/code/pymqi/__init__.py#L2462) too.

**Comment by leonjza** [comment]
Looks like this was introduced in this commit: https://github.com/dsuch/pymqi/commit/e30e1fbc9a678725c9a32f38f0320f586d80289c

**Comment by dsuch** [comment]
Hi @leonjza - thanks for the PR, I will release 1.10.1 shortly to include it.

**Comment by dsuch** [comment]
Thanks again @leonjza - v. 1.10.1 is out now and it includes your PR.

**Comment by leonjza** [comment]
Thanks for the quick response!
