### ISSUE TITLE
Changes needed for Websphere MQ 8.0

### ISSUE THREAD

**Issue by webe3** [dsuch/pymqi#17]
Websphere MQ 8.0 adds a new field in MQCD.  This requires changes in several pymqi files.  I have made those changes in my local copy so that pymqi works with MQ 8.0.  I don't see a way to attach the new files in the bug report.  Let me know if you want me to put the new files somewhere.

**Comment by Bbouch** [comment]
I was trying to make similar changes myself this week, but got tripped up somewhere. Would you be willing to send your updates to me at brian@earlyMaine.org?  I'm working on a tight deadline and can't seem to determine where I went wrong in my changes.

**Comment by dsuch** [comment]
Hello everyone - I understand it won't help you immediately but I'll be most likely working on MQ 8.0 support within two months.

@webe3 - if you'd like to attach code on GitHub it is easiest to do it using https://gist.github.com - cheers!

**Comment by dsuch** [comment]
I'm setting off to work on MQ 8.0 support. If there is anything you'd like to share @webe3 @Bbouch please post it to https://gist.github.com - thanks a lot!

**Comment by webe3** [comment]
On Mon, 2015-08-03 at 08:14 -0700, Dariusz Suchojad wrote:
> Hello everyone - I understand it won't help you immediately but I'll
> be most likely working on MQ 8.0 support within two months.
> 
> @webe3 - if you'd like to attach code on GitHub it is easiest to do it
> using https://gist.github.com - cheers!
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

I created a gist.  I have not used gist before.  I will have to say, I
am not a fan of gist.  I was expecting the usual attach a file by
browsing and uploading.  From what I could tell, that functionality did
not exist.  So, I cut and pasted the snippets that I changed.  Cutting
and pasting did not work very well either.  I don't know how the gist
works and how you are supposed to find it.  It seems like a very awkward
process.  Anyhow, let me know if you need anything.

Brent

**Comment by dsuch** [comment]
Brent, I don't like the lack of uploads either, true that.

I couldn't find your gist anywhere - you can send everything to me by email dsuch@zato.io and I'll upload it to gist myself, referencing it here in the ticket later on.

Thanks.

**Comment by dsuch** [comment]
PyMQI 1.5 has just been released and it contains everything that is needed to connect to MQ 8.0, thanks everyone!
