### ISSUE TITLE
pymqi does not allow to specify CertificateLabel

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#170]
When I use this code:
```
sco = pymqi.SCO(Version=pymqi.CMQC.MQSCO_VERSION_5,
                KeyRepository=key_repo_location,
                CertificateLabel=b'client')
```

I get:
```
Traceback (most recent call last):
  File "test_ssl.py", line 17, in <module>
    CertificateLabel=b'client')
  File "<path>/pymqi/code/pymqi/__init__.py", line 988, in __init__
    super(SCO, self).__init__(tuple(opts), **kw)
  File "<path>/pymqi/code/pymqi/__init__.py", line 269, in __init__
    self.set(**kw)
  File "<path>/pymqi/code/pymqi/__init__.py", line 321, in set
    getattr(self, str(i))
AttributeError: 'SCO' object has no attribute 'CertificateLabel'
```

**Comment by salapat11** [comment]
CertificateLabel is an option in CD.  

cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
cd.ChannelName = ''
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
cd.CertificateLabel = ''

sco = pymqi.SCO()
sco.KeyRepository = key_repo_location

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, user=user, password=password, cd=cd, sco=sco)

**Comment by SeyfSV** [comment]
This issue just for referencing in commit
I know how to fix:) But I need some time to create test case for unit testing.
If someone needs this features now, I'll commit fix to master.

**Comment by salapat11** [comment]
I realized, so removed my comments :)

**Comment by SeyfSV** [comment]
Hi @dsuch , can you review changes.
I did some changes in pymqe.c and I think you should know about that.

**Comment by dsuch** [comment]
Hi @SeyfSV - do you mean this commit?

**Comment by dsuch** [comment]
https://github.com/dsuch/pymqi/commit/ba31e47215ead5dcbac3cbc9421059e9759dada4

**Comment by SeyfSV** [comment]
Yes
