### ISSUE TITLE
Fetch put time, put date headers from message

### ISSUE THREAD

**Issue by salapat11** [dsuch/pymqi#171]
Any examples for fetching headers from a message?

**Comment by dsuch** [comment]
Hi @salapat11,

is there any particular reason for the ill manners?

Saying at least hello and explaining in code what you mean along with a sample of what you have done so far yourself would go a long way.

**Comment by salapat11** [comment]
Hello @dsuch, Sorry about that.  I am trying to browse messages from a queue using the below example.  

queue = pymqi.Queue(qmgr, queueName,
                        pymqi.CMQC.MQOO_FAIL_IF_QUIESCING
                        | pymqi.CMQC.MQOO_INPUT_SHARED
                        | pymqi.CMQC.MQOO_BROWSE)

    gmo = pymqi.GMO()
    gmo.Options = pymqi.CMQC.MQGMO_BROWSE_NEXT
    
    for i in range(numMessages):
        md = pymqi.MD()
        message = queue.get(None, md, gmo)
        print(message)

I tried "get" to fetch the message but also need the message headers like PutTime and PutDate.

**Comment by dsuch** [comment]
Do you mean PutTime and PutDate from MQMD?

If so, then note that you are resetting it in your loop whereas you should rather re-use it, as in the example below.

Then, you can just get the current message's (the one from the current loop) via md.PutTime and md.PutDate.

https://dsuch.github.io/pymqi/examples.html#how-to-wait-for-multiple-messages

**Comment by salapat11** [comment]
Thank you, @dsuch.  I was able to get it from "md".

**Comment by dsuch** [comment]
Please share your code for the benefit of other users in the future and close the ticket if it is no longer needed. Thanks.

**Comment by salapat11** [comment]
Sure.  I used the code below to fetch MQMD headers -

```
queue = pymqi.Queue(qmgr, queueName,
                    pymqi.CMQC.MQOO_FAIL_IF_QUIESCING
                    | pymqi.CMQC.MQOO_INPUT_SHARED
                    | pymqi.CMQC.MQOO_BROWSE)

gmo = pymqi.GMO()
gmo.Options = pymqi.CMQC.MQGMO_BROWSE_NEXT

messages = []
for i in range(numMessages):
    md = pymqi.MD()
    message = queue.get(None, md, gmo)
    print(message)
    print(md.PutDate)
    print(md.PutTime)
    print(md.UserIdentifier)
    print(md.PutApplName)
    messages.append(message)

queue.close()
qmgr.disconnect()
```
