### ISSUE TITLE
Can I set JMS NamedProperties and message descriptor encoding in pymqi?

### ISSUE THREAD

**Issue by Aakaash897** [dsuch/pymqi#172]
I am trying to set the encode type to 273 (IBM standard) instead of 576 (Current Encoding standard)

Also, I would like to set JMS Named Properties.
```
md = pymqi.MD()
md.Persistence = 1
md.CodedCharSetId = 1208
md.Format = CMQC.MQFMT_STRING
md.encoding = '273'

queue.put(doc,md)
```

**md.encoding = 273** doesnt seem to work. 
I'm working on a windows system and PyCharm IDE

**Comment by dsuch** [comment]
You have a typo, it should be md.Encoding instead of md.encoding.

Also, realise that no one knows what you mean by 'doesnt seem to work' and that no one will be able to assist you unless post self-contained samples, ready to use, in addition to any kind of errors, exceptions and other diagnostic messages that you receive.

**Comment by Aakaash897** [comment]
md.Encoding* Sorry

I am basically trying to post a XML request to a queue using **put()** statement. 
Before doing so, am encoding it (converting to bytes).

The issues here is that, after I post the message, I can see that the message contains 'zero' data or is zero in size according to the WebSphere MQ Explorer. 
Also, the Queue is based on a UNIX server which requires the encoding type to be of 273 (IBM I suppose). 
The current encoding standard is 576 by default. 

Upon trying to manually edit to 273, the encoding remains to be 576

The image attached will give you an idea. To the left is what I have posted and to the right is what is supposed to be.

![image](https://user-images.githubusercontent.com/39468678/74687740-3b062900-51a3-11ea-9154-f9efdf1faa1e.png)

**Comment by SeyfSV** [comment]
Hi @Aakaash897, 
If it means, I checked putting message with encoding 273 - it's work as expected.
![image](https://user-images.githubusercontenis steel t.com/25712100/75916355-4034ca80-5e69-11ea-89eb-898fd78c598d.png)
If you need additional info, please, provide simple snippet, that reproduces issue, and pymqi version (commit) that you use.

**Comment by SeyfSV** [comment]
@Aakaash897 , please, reopen issue, if you have other questions.
