### ISSUE TITLE
installation on AIX

### ISSUE THREAD

**Issue by kai-uwe-rommel** [dsuch/pymqi#175]
I am trying to install on an AIX system.
I have python (obviously) and pip installed.
But "pip install pymqi" fails because it tries to compile the native code with IBM C compiler.
It tries to execute xlr_r and fails.
Is it possible to compile with gcc on AIX?
We do not have an IBM XL-C/C++ license but gcc is free ...

**Comment by dsuch** [comment]
Hi @kai-uwe-rommel,

can you please post here the exact commands that you execute and the full output?

Also, can you indicate what PyMQI version you are using?

Thanks.

**Comment by dsuch** [comment]
One more note - it appears that someone asked a similar question here on StackOverflow:

https://stackoverflow.com/questions/5376514/how-do-i-force-python-pymqi-1-2-to-use-my-gcc-compiler-when-i-build-it

The answer looks to be:

```
The setup.py build command has the following two options

  --compiler (-c)    specify the compiler type
  --help-compiler    list available compilers

Use those to specify the compiler which you want to use.
```

**Comment by kai-uwe-rommel** [comment]
Shortly after my posting I found I can simply set the CC envronment variable ...
I do now have to provider other prerequisites ... will test during the next couple of days.

I was using simply "pip install pymqi" e.g. that will pull the newest version (1.10.x).
I'll come back with exact error messages should gcc fail as well.

**Comment by dsuch** [comment]
That sounds good but can you also post that information while using xlr? I would like to understand what was going on.

**Comment by kai-uwe-rommel** [comment]
Sure. It was simply not finding the (default) C compiler:

`root@ryker:/root # pip install pymqi
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pymqi
  Using cached pymqi-1.10.1.tar.gz (70 kB)
Building wheels for collected packages: pymqi
  Building wheel for pymqi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-XY8Yvw
       cwd: /tmp/pip-install-pS7JmF/pymqi/
  Complete output (20 lines):
  Building PyMQI client mode 32bits
  Using library_dirs:`['/usr/mqm/lib']`, include:`['/usr/mqm/inc']`, libraries:`['mqic_r']`
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.aix-7.1-2.7
  creating build/lib.aix-7.1-2.7/pymqi
  copying pymqi/__init__.py -> build/lib.aix-7.1-2.7/pymqi
  copying pymqi/CMQC.py -> build/lib.aix-7.1-2.7/pymqi
  copying pymqi/CMQCFC.py -> build/lib.aix-7.1-2.7/pymqi
  copying pymqi/CMQXC.py -> build/lib.aix-7.1-2.7/pymqi
  copying pymqi/CMQZC.py -> build/lib.aix-7.1-2.7/pymqi
  running build_ext
  building 'pymqi.pymqe' extension
  creating build/temp.aix-7.1-2.7
  creating build/temp.aix-7.1-2.7/pymqi
  /opt/IBM/xlc/13.1.3/bin/xlc_r -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -q64 -qbitfields=signed -qmaxmem=70000 -qalloca -bmaxdata:0x80000000 -Wl,-brtl -q32 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DNDEBUG -O2 -DPYQMI_BINDINGS_MODE_BUILD=0 -I/usr/mqm/inc -I/opt/freeware/include/python2.7 -c pymqi/pymqe.c -o build/temp.aix-7.1-2.7/pymqi/pymqe.o
  unable to execute '/opt/IBM/xlc/13.1.3/bin/xlc_r': No such file or directory
  error: command '/opt/IBM/xlc/13.1.3/bin/xlc_r' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pymqi
  Running setup.py clean for pymqi
Failed to build pymqi
Installing collected packages: pymqi
    Running setup.py install for pymqi ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c3QNW4/install-record.txt --single-version-externally-managed --compile --install-headers /opt/freeware/include/python2.7/pymqi
         cwd: /tmp/pip-install-pS7JmF/pymqi/
    Complete output (20 lines):
    Building PyMQI client mode 32bits
    Using library_dirs:`['/usr/mqm/lib']`, include:`['/usr/mqm/inc']`, libraries:`['mqic_r']`
    running install
    running build
    running build_py
    creating build
    creating build/lib.aix-7.1-2.7
    creating build/lib.aix-7.1-2.7/pymqi
    copying pymqi/__init__.py -> build/lib.aix-7.1-2.7/pymqi
    copying pymqi/CMQC.py -> build/lib.aix-7.1-2.7/pymqi
    copying pymqi/CMQCFC.py -> build/lib.aix-7.1-2.7/pymqi
    copying pymqi/CMQXC.py -> build/lib.aix-7.1-2.7/pymqi
    copying pymqi/CMQZC.py -> build/lib.aix-7.1-2.7/pymqi
    running build_ext
    building 'pymqi.pymqe' extension
    creating build/temp.aix-7.1-2.7
    creating build/temp.aix-7.1-2.7/pymqi
    /opt/IBM/xlc/13.1.3/bin/xlc_r -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -q64 -qbitfields=signed -qmaxmem=70000 -qalloca -bmaxdata:0x80000000 -Wl,-brtl -q32 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DNDEBUG -O2 -DPYQMI_BINDINGS_MODE_BUILD=0 -I/usr/mqm/inc -I/opt/freeware/include/python2.7 -c pymqi/pymqe.c -o build/temp.aix-7.1-2.7/pymqi/pymqe.o
    unable to execute '/opt/IBM/xlc/13.1.3/bin/xlc_r': No such file or directory
    error: command '/opt/IBM/xlc/13.1.3/bin/xlc_r' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pS7JmF/pymqi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c3QNW4/install-record.txt --single-version-externally-managed --compile --install-headers /opt/freeware/include/python2.7/pymqi Check the logs for full command output.
root@ryker:/root #
`

**Comment by kai-uwe-rommel** [comment]
CC was not defined so it was pulling some default CC information from somewhere ...

**Comment by SeyfSV** [comment]
@kai-uwe-rommel , can we close issue?

**Comment by kai-uwe-rommel** [comment]
Somehow the issue/task got lower priority and has not yet again been worked on ...
So much other work to do. I can close the ticket issue for now.
And come back later should I work on this again.
Sorry.
