### ISSUE TITLE
struct.error: argument for 's' must be a bytes object

### ISSUE THREAD

**Issue by leonjza** [dsuch/pymqi#176]
Not 100% sure how to debug this one, but I suspect it may be related to python 3 and strings/bytes usage. I am using the following code to try and connect to a queue manager:

```python
cd = pymqi.CD()
cd.ChannelName = config.mqchannel.encode()
cd.ConnectionName = f'{config.mqhost}({config.mqport})'.encode(),
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP

connect_options = pymqi.CMQC.MQCNO_HANDLE_SHARE_BLOCK

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(
    config.mqqmname.encode(),
    user=config.mqusername,
    password=config.mqpassword,
    cd=cd,
    opts=connect_options
)
```

Resulting in an error with the relevant parts here:

```
 Traceback (most recent call last):

[...]

   File "/processor/router/parsers/xxx.py", line 92, in xxx
     qmgr.connect_with_options(
   File "/usr/local/lib/python3.8/dist-packages/pymqi/__init__.py", line 1337, in connect_with_options
     cd = cd.pack()
   File "/usr/local/lib/python3.8/dist-packages/pymqi/__init__.py", line 294, in pack
     return struct.pack(*args)
 struct.error: argument for 's' must be a bytes object
```

Any hints to debug? I have tried a few variations of `encode()` on different string values with no luck.

**Comment by JoshMcMQ** [comment]
Which pymqi version?

**Comment by dsuch** [comment]
Hello @leonjza,

yes, knowing the PyMQI version will be helpful.

Also, in the line above, was that a bad copy/paste or do you really have a trailing comma there which turns the right-hand side into a tuple that you assign to cd.ConnectionName?

> cd.ConnectionName = f'{config.mqhost}({config.mqport})'.encode(),

**Comment by leonjza** [comment]
Well this is embarrassing. The trailing comma was the culprit. Apologies and thanks for the response!
