### ISSUE TITLE
Issues with pusing to alias queue

### ISSUE THREAD

**Issue by seemsindie** [dsuch/pymqi#178]
Hello, I am trying to put the message to the queue using this code:

```
property_name = b"test_name"
property_value = "test value"

qmgr =qmgr = pymqi.connect(queue_manager, channel, conn_info)

put_msg_h = pymqi.MessageHandle(qmgr)
put_msg_h.properties.set(property_name, property_value) # Default type is CMQC.MQTYPE_STRING

pmo = pymqi.PMO(Version=pymqi.CMQC.MQPMO_VERSION_3) # PMO v3 is required properties
pmo.OriginalMsgHandle = put_msg_h.msg_handle

put_md = pymqi.MD(Version=pymqi.CMQC.MQMD_CURRENT_VERSION)

put_queue = pymqi.Queue(qmgr, queue_name)
put_queue.put(b'', put_md, pmo)

put_queue.close()
qmgr.disconnect()
```

When I am pushing this to the local queue everything works fine. I get the message in the queue. But when I switch `queue_name` and try to put the message to the alias queue(that is referencing the same local queue that was working) I don't get the message in the queue and I am also not getting any errors from python.

Do you guys have any idea what is happening, it looks to me like I need to set some flag somewhere but I am not sure what?

Thanks

**Comment by SeyfSV** [comment]
Hello, I think this is not pymqi issue.
Can you put a message to alias queue with MQ Explorer, amqsput or others tools?

**Comment by seemsindie** [comment]
Hmm, using MQ Explorer I was able to put test message to alias queue and it went to the correct local.

I am using the same queue and queue manager the MQ explorer uses in "put test message" dialog. Using amqsput and exporting `export MQSERVER='localhost(1414)'` I got

`./amqsput QUEUE.NAME QM.NAME`
```
Sample AMQSPUT0 start
MQCONNX ended with reason code 2058
```

I also ran this command(found it somewhere on the internet :) ) `./amqssslc -m 'QM.NAME' -c 'QUEUE.NAME' -x 'localhost(1414)'` and got these results

```
Sample AMQSSSLC start
Connecting to queue manager QM.NAME                                         
Using the server connection channel QUEUE.NAME
on connection name localhost(1414).
No SSL configuration specified.
Connection established to queue manager QM.NAME                                         
Sample AMQSSSLC end
```

**Comment by SeyfSV** [comment]
I checked putting to alias queue - it works.
Please, check client and queue manager logs and DLQ.

**Comment by seemsindie** [comment]
Thanks, man, I guess it's something about how I did set up queues and topics... Thanks a lot.
