### ISSUE TITLE
How to query queue metadata

### ISSUE THREAD

**Issue by immanuelsavio** [dsuch/pymqi#179]
I want to query the queue's metadata like the alive status(bool), queue depth(int), late updated etc like this

{"QueueName":"Q1","QueueManagerName":QM1","QueueDepth":0,"InProc":0,"OutProc":0,"LPUTTIME":"01.47.56","LPUTDATE":"2020-03-17","LGETTIME":"01.48.22","LGETDATE":"2020-03-17"}

Thanks in advance

**Comment by SeyfSV** [comment]
Have you read documentation: https://dsuch.github.io/pymqi/examples.html#how-to-display-queues ?

**Comment by immanuelsavio** [comment]
I have tried it. If I use CMQC.MQIA_CURRENT_Q_DEPTH I get MQRC_SELECTOR_NOT_FOR_TYPE error. How to resolve it

**Comment by dsuch** [comment]
Hello @immanuelsavio,

please start by reading this article:

https://opensource.com/life/16/10/how-ask-technical-questions

Please make sure you that read it all thoroughly and that you apply all the recommendations and suggestions the author provided.

Thanks.

**Comment by immanuelsavio** [comment]
> Hello @immanuelsavio,
> 
> please start by reading this article:
> 
> https://opensource.com/life/16/10/how-ask-technical-questions
> 
> Please make sure you that read it all thoroughly and that you apply all the recommendations and suggestions the author provided.
> 
> Thanks.

Sorry about that. I wanted to get the metadata of the remote MQ. To get the queue depth I tried using the following piece of code

`       queue_manager = 'QM1'
        channel = 'channel1'
        host = 'H1'
        port = '1412'
        conn_info = '%s(%s)' % (host, port)

        qmgr = pymqi.connect(queue_manager, channel, conn_info)
        queue = pymqi.Queue(qmgr, qc.mqName[0])
        depth = queue.inquire(pymqi.CMQC.MQIA_CURRENT_Q_DEPTH)
`
I get the following error 

`MQI Error. Comp: 1, Reason 2068: WARNING: MQRC_SELECTOR_NOT_FOR_TYPE`

Can you please help.

**Comment by JoshMcMQ** [comment]
You cannot inquire depth of a model queue,  only a local queue.

**Comment by immanuelsavio** [comment]
Ok thanks a lot @JoshMcMQ.

**Comment by immanuelsavio** [comment]
It is a live queue. I have hidden the credentials. I wanted the Parameter to inquire the queue depth.

**Comment by JoshMcMQ** [comment]
You have `pymqi.CMQC.MQQT_MODEL`, it is not possible to a model queue.

**Comment by immanuelsavio** [comment]
I get that @JoshMcMQ. But what is the parameter to send in the args for queue depth in a local queue

**Comment by JoshMcMQ** [comment]
I would guess something like `CMQC.MQQT_LOCAL`.

**Comment by JoshMcMQ** [comment]
Not sure if this would work? 

```python
import logging

import pymqi

logging.basicConfig(level=logging.INFO)

qmgr = pymqi.connect(queue_manager, channel, conn_info)

       attrs = {
            pymqi.CMQC.MQCA_Q_NAME : '*',
            pymqi.CMQC.MQIA_Q_TYPE : pymqi.CMQC.MQQT_LOCAL,
            pymqi.CMQCFC.MQIACF_Q_ATTRS : [pymqi. pymqi.CMQC.MQCA_Q_NAME, CMQC.MQIA_CURRENT_Q_DEPTH]
            }
pcf = pymqi.PCFExecute(qmgr)
results = pcf.MQCMD_INQUIRE_Q(attrs)
pcf.disconnect

logging.info('Result is %s', result)
```

**Comment by immanuelsavio** [comment]
I have a specific queue which I want to retrieve info of. I tried `pymqi.CMQC.MQQT_LOCAL` also. So I went with the following approach.
```
attrs = {
            pymqi.CMQC.MQCA_Q_NAME : 'Q1', 
            pymqi.CMQC.MQIA_Q_TYPE : pymqi.CMQC.MQQT_ALL,
            pymqi.CMQCFC.MQIACF_Q_ATTRS : [pymqi. pymqi.CMQC.MQCA_Q_NAME, CMQC.MQIA_CURRENT_Q_DEPTH]
            }
results = pcf.MQCMD_INQUIRE_Q(attrs)
```

and I'm getting this error. I'm hiding the queue name for confidentiality.

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-11-04dee6a157a4> in <module>
----> 1 results = pcf.MQCMD_INQUIRE_Q(attrs)

~\AppData\Local\Continuum\anaconda3\envs\Dell_Project\lib\site-packages\pymqi\__init__.py in __call__(self, *args)
   2502             qm_handle = self.__pcf.getHandle()
   2503         if len(args) > 0:
-> 2504             rv = pymqe.mqaiExecute(qm_handle, CMQCFC.__dict__[self.__name], *args)
   2505         else:
   2506             rv = pymqe.mqaiExecute(qm_handle, CMQCFC.__dict__[self.__name], {}, [])

error: Value 'Q1' for key 2016 is not a long, bytes nor a pymqi.ByteString instance
```

**Comment by JoshMcMQ** [comment]
Probably need something like `b'Q1'` ?

**Comment by immanuelsavio** [comment]
Yeah, that fixed it. Thanks a lot, @JoshMcMQ and thanks for the guide Mr @dsuch. This really helped.
