### ISSUE TITLE
AMQ9627 when use sco.CertificateLabel and os user does not match certificate label user

### ISSUE THREAD

**Issue by DennyD17** [dsuch/pymqi#181]
This issue created instead of closed https://github.com/dsuch/pymqi/issues/87

Hello! 

My MQ client version is 9.0.0.3-IBM-MQC-LinuxX64
Applications works in container, orchestra is Openshift 3.0.

 **Cert reqs was created by the following command:**
`runmqckm -certreq -create -db od99usr.kdb -pw pw -label ibmwebspheremqod99usr -dn dn -size 2048 -file od99usr.csr -sig_alg SHA256WithRSA
`

**Part of code from my application:**
```
ssl_cipher_spec = 'TLS_RSA_WITH_AES_128_CBC_SHA256'
# MQ
cd = pymqi.CD()
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
cd.CertificateLabel = "ibmwebspheremqod99usr"
# SCO
sco = pymqi.SCO()
sco.CertificateLabel = "ibmwebspheremqod99usr"
sco.KeyRepository = key_repo_location

```

**Whoaim from container:**

```
whoami
whoami: cannot find name for user ID 1007400000

```
**when I trying to connect I get the following python error:**

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__

    return self.run(*args, **kwargs)

  File "/code/base/tasks.py", line 22, in get_create_incident_results

    mq = MQConnection()

  File "/code/base/mq.py", line 39, in __init__

    self.qmgr.connect_with_options(queue_manager, cd, sco)

  File "/usr/local/lib64/python3.6/site-packages/pymqi/__init__.py", line 1412, in connectWithOptions

    raise MQMIError(rv[1], rv[2])

pymqi.MQMIError: MQI Error. Comp: 2, Reason 2381: FAILED: MQRC_KEY_REPOSITORY_ERROR
```

In /var/mqm/errors/*log I have:

```
----- amqxfdcx.c : 891 --------------------------------------------------------
04/21/2020 03:27:36 PM - Process(37.1) User(UNKNOWN) Program(celery)
                    Host(sdsa-47-4rgwt) Installation(Installation1)
                    VRMF(9.0.0.3) QMgr(.)
 
AMQ9627: The path and stem name for the SSL key repository have not been
specified.
 
EXPLANATION:
The directory path and file stem name for the SSL key repository have not been
specified. On a MQ client system there is no default location for this file.
SSL connectivity is therefore impossible as this file cannot be accessed.
ACTION:
Use the MQSSLKEYR environment variable or MQCONNX API call to specify the
directory path and file stem name for the SSL key repository.

```

Can you explain me where is my mistake?
I also tried to change 
sco.CertificateLabel to "od99usr"
remove and add cd.CertificateLabel
but get the same error =(

> Hi @DennyD17,
> 
> MQ finds the certificate in the keystore to use when connecting by default based on the cert label. As a default it will attempt to find a cert with a label of `ibmwebspheremq<username in lowercase>`. So if you run as a user `mquser` it would look for `ibmwebspheremqmquser`, if you run as a user `denis` it will look for `ibmwebspheremqdenis`.
> 
> You can use the `runmqakm` command supplied with MQ client v7.1 and later to rename the cert label to the value required.
> 
> If you are using v8.0 or later you can specify the `sco.CertificateLabel = "ibmwebspheremqmquser"`. This way the key store would work for either user.
> 
> For much more detail about the how MQ interacts with the cert label please review the following IBM Technote: [Specifying the userid in the SSL certificate label for an MQ client](https://www-01.ibm.com/support/docview.wss?uid=swg21245474)
> 
> Please mark this as closed if this resolves your problem or let me know if you have further questions.

_Originally posted by @DennyD17 in https://github.com/dsuch/pymqi/issues/87#issuecomment-617159813_

**Comment by DennyD17** [comment]
```
cd.CertificateLabel = "ibmwebspheremqod99usr"
sco = pymqi.SCO(Version=pymqi.CMQC.MQSCO_VERSION_5,
                KeyRepository=key_repo_location)

```
and

`oc set env dc/proj MQCERTLABL=ibmwebspheremqod99usr 
`

fix my problem

**Comment by SeyfSV** [comment]
Hi Denis, I am glad to hear, that you fixed it.
Does it work without env variable? If no, please, leave issue open for further investigation.

**Comment by DennyD17** [comment]
No, It works only with env variable.

**Comment by JoshMcMQ** [comment]
Setting ENV variable `MQCERTLABL=ibmwebspheremqod99usr` and `cd.CertificateLabel = "ibmwebspheremqod99usr"` should not both be needed, likely the second one is what is in use. If you had to specify Version=pymqi.CMQC.MQSCO_VERSION_5 you may not be using the latest pymqi version 1.10.1. See these pymqi issues: 170 and 141. I think the issue with MQSCO Version needing to be set manually to 5 is corrected in the latest version.

**Comment by SeyfSV** [comment]
Some [info](https://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.sec.doc/q014340_.htm) about Certificate Label usage...

**Comment by DennyD17** [comment]
> Setting ENV variable `MQCERTLABL=ibmwebspheremqod99usr` and `cd.CertificateLabel = "ibmwebspheremqod99usr"` should not both be needed, likely the second one is what is in use. If you had to specify Version=pymqi.CMQC.MQSCO_VERSION_5 you may not be using the latest pymqi version 1.10.1. See these pymqi issues: 170 and 141. I think the issue with MQSCO Version needing to be set manually to 5 is corrected in the latest version.

Now I use only env variable, other solutions don't work

**Comment by JoshMcMQ** [comment]
Which version of pymqi are you using?

**Comment by SeyfSV** [comment]
@DennyD17 
MQCD.CertificateLabel requires MQCD_VERSION_11.
Please, add line:
`cd.Version = pymqi.CMQXC.MQCD_VERSION_11`

Also you can use MQSCO.CertificateLabel (MQSCO_VERSION_5 required), but this is not in the master branch. It was fixed in #170, but not merged yet.

**Comment by JoshMcMQ** [comment]
As reported [here](https://stackoverflow.com/questions/61348357/py3mqi-amq9627-when-use-sco-certificatelabel-and-os-user-does-not-match-certifi/61363684?noredirect=1#comment108665817_61363684) [py3mqi 1.6.0](https://pypi.org/project/py3mqi/) is in use. I suggested they try pymqi 1.10.1.

**Comment by SeyfSV** [comment]
Oh, I missed that.
@DennyD17 , do you use released version as suggested?

**Comment by DennyD17** [comment]
There are no 1.10 version in my organization pypi mirror, the last available version is 1.9.3

**Comment by JoshMcMQ** [comment]
I think this issue should be closed as you are not even using this pymqi, you are using py3mqi which is abandoned as far as I can tell.

**Comment by dsuch** [comment]
Hello everyone,

@DennyD17 - if you are not using PyMQI then yes, I am closing this ticket. This repository is for PyMQI only.

To let you better understand the current situation - a few years ago getting PyMQI to work was not one of anyone's priorities, including myself.

There was a person who forked PyMQI under the name of py3mqi and added support for Python 3 in that fork. That fork has nothing to do with PyMQI other than the fact that PyMQI was the foundation upon py3mqi was created.

Ultimately, we added support for Python 3 to PyMQI but apparently, py3mqi still exists. Which is fine by me, this is open-source software so everyone is free whatever they want to.

However, you opened a ticket in a GitHub repository for PyMQI, not for py3mqi. Hence, you can move it to a repository for py3mqi or start to use PyMQI. 

Until you use PyMQI in versions that other people indicated, this ticket will be closed.

Thank you.
