### ISSUE TITLE
How to pass multiple argument for creating channel?

### ISSUE THREAD

**Issue by sudarshanaks** [dsuch/pymqi#182]
Hi Team,

I'm trying to implement following command using python pymqi but I'm not fining equivalent code to do that.
DEFINE CHL(TO.QMGR1) CHLTYPE(CLUSRCVR) CONNAME('LOCALHOST(1515)') CLUSTER(CLUSTER_NAME)

**Comment by SeyfSV** [comment]
[How to define a channel](https://github.com/dsuch/pymqi/blob/master/docs/examples.rst#how-to-define-a-channel)
Please, search examples and read documentation before posting issues.
