### ISSUE TITLE
Using PYMQI to get queue depth of Clustered queue

### ISSUE THREAD

**Issue by Honeybee427** [dsuch/pymqi#183]
Hi, Using PYMQI to get the queue depth of local queues. It works great. Yet when try to do the same with a clustered queue I get below error:
 **pymqi.MQMIError: MQI Error. Comp: 1, Reason 2068: WARNING: MQRC_SELECTOR_NOT_FOR_TYPE**
Tried opening queue with MQOO_SET and MQOO_BROWSE but it did not seem to work.
Does anybody have an example?
Thanks

**Comment by JoshMcMQ** [comment]
Must open for input.

**Comment by Honeybee427** [comment]
Thank you for the response. I am a bit green with MQ. Since I am connecting from my PC to these remote queue managers, does your response mean that in the case of a clustered queue I need to run the python script on the server that contains the LOCAL instance of the clustered queue?

**Comment by Honeybee427** [comment]
Thank you for the response. I am a bit green with MQ. Since I am connecting from my PC to these remote queue managers, does your response mean that in the case of a clustered queue I need to run the python script on the server that contains the LOCAL instance of the clustered queue?

**Comment by Honeybee427** [comment]
One more question if I may. How can I determine the QLOCAL instance of a clustered queue?
Thanks

**Comment by JoshMcMQ** [comment]
The script does not need to run on the same server as the queue manager with the local queue but it does need to connect to the queue manger with the local queue.

**Comment by SeyfSV** [comment]
@Honeybee427 can issue be closed?

**Comment by Honeybee427** [comment]
Yes
