### ISSUE TITLE
MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

### ISSUE THREAD

**Issue by lpaf** [dsuch/pymqi#185]
Hello everyone,

I am aware that this issue has already been raised for several times, yet even after going through all possible solutions, I still cannot resolve this issue.

I am using python3.6 with pymqi version 1.10.1, to connect to an IBM MQ version 9.1.0.0.
I am trying to connect in a client mode, using SSL, to a SVRCON channel (I have verified that it is indeed a SVRCON channel), but getting the below error:

> ```   
> qmgr.connect_with_options(queue_manager, cd, sco)
>   File "/usr/local/lib64/python3.6/site-packages/pymqi/__init__.py", line 1347, in connect_with_options
>     raise MQMIError(rv[1], rv[2])
> pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR
> ```

This is my python code: 

```
import logging
import pymqi

logging.basicConfig(level=logging.INFO)

queue_manager = '*****'
channel = '***.CHANNEL'
host = '*.*.*.*'
port = '1414'
queue_name = '*****'
conn_info = '%s(%s)' % (host, port)
ssl_cipher_spec = 'TLS_RSA_WITH_AES_256_CBC_SHA256'
key_repo_location = '/tmp/...***.../key'
message = 'Hello from Python!'

cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
#cd.SSLCipherSpec = "TLS_RSA_WITH_AES_256_CBC_SHA256"


sco = pymqi.SCO()
sco.KeyRepository = key_repo_location

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, cd, sco)
#qmgr.connect_with_options(queue_manager [, opts=cnoopts][ ,cd=mqcd][ ,sco=mqsco])

put_queue = pymqi.Queue(qmgr, queue_name)
put_queue.put(message)

get_queue = pymqi.Queue(qmgr, queue_name)
logging.info('Here is the message again: [%s]' % get_queue.get())

put_queue.close()
get_queue.close()
qmgr.disconnect()
```

These are the channel's details:

> 
>     AMQ8414I: Display Channel details.
>       CHANNEL(***.CHANNEL) CHLTYPE(SVRCONN)
>       SSLCAUTH(REQUIRED)   SSLCIPH(TLS_RSA_WITH_AES_256_CBC_SHA256)

I would really appreciate any kind of assistance with this issue, thank you very much!

**Comment by JoshMcMQ** [comment]
What do you see on the `AMQERR01.LOG` on both the client and the queue manager?

**Comment by lpaf** [comment]
Hi @JoshMcMQ,

On the QMGR I cannot even see the attempts, so I guess something is wrong with the code.
This is the only thing I see in `AMQERR01.LOG` on the client side:

```
`----- amqcgska.c : 1045 -------------------------------------------------------
05/18/2020 06:45:50 AM - Process(3761.1) User(centos) Program(connectWithSSL.)
                    Host(ip-**-*-*-*.ec2.internal) Installation(Installation1)
                    VRMF(9.0.0.8) QMgr(.)
                   
AMQ6174: The dynamically loadable shared library
'/opt/mqm/gskit8/lib64/libgsk8sys_64.so' was not found. The system returned
error number '2' and error message 'No such file or directory'.

EXPLANATION:
This message applies to UNIX systems. The shared library
'/opt/mqm/gskit8/lib64/libgsk8sys_64.so' was not found.
ACTION:
Check that the file exists, and is either fully qualified or is in the
appropriate director, also check the file access permissions.
-------------------------------------------------------------------------------
05/18/2020 06:45:50 AM - Process(3761.1) User(centos) Program(connectWithSSL.)
                    Host(ip-*-*-*-*.ec2.internal) Installation(Installation1)
                    VRMF(9.0.0.8) QMgr(.)
                   
AMQ9220: The GSKit communications program could not be loaded.

EXPLANATION:
The attempt to load the GSKit library or procedure
'/opt/mqm/gskit8/lib64/libgsk8sys_64.so' failed with error code 24948.
ACTION:
Either the library must be installed on the system or the environment changed
to allow the program to locate it.`
```

**Comment by JoshMcMQ** [comment]
You are missing the gskit package.   I recommend the Redist client,  it comes as a simple tar.gz that you just unzip and set LD_LIBRARY_PATH.

**Comment by lpaf** [comment]
Thank you very much @JoshMcMQ! I downloaded the redist client package and looks like it resolved the issue! Much appreciated!
