### ISSUE TITLE
Missing PCF commands for CHLAUTH records

### ISSUE THREAD

**Issue by JochemGit** [dsuch/pymqi#187]
Hello, this is just a question. I check using pymqi for MQ configuration with PCF commands.
Some tests with different mq objects work as expected and pretty well.

Now I want to check displaying and setting of channel authentication records. This is done with the commands `MQCMD_INQUIRE_CHLAUTH_RECS` and `MQCMD_SET_CHLAUTH_REC`. 

I cannot find these commands in `CMQCFC.py`. Aren't these commands supported? Why not?

Thank you in advance for a response!

**Comment by SeyfSV** [comment]
Hi @JochemGit ,
Please check version from this [branch](https://github.com/dsuch/pymqi/tree/gh92-move-from-mqai)
And yes, release version has some issues with PCF.
Which platform do you use? We need someone who can approve new version work on platforms, that does not support MQAI.

**Comment by JochemGit** [comment]
Hi,
I cannot find it in this branch either.
I work on linux (currently ubuntu, but mostly suse) and with MQ 9.

Is it planned to add the support of channel authentication records?

**Comment by JochemGit** [comment]
I found it now in this [branch](https://github.com/dsuch/pymqi/tree/gh170-sco-certificate-label). Were you talking about this one?
Might it work? Should I test this version?

**Comment by SeyfSV** [comment]
Yes, try it.
Code does not know about object type (queue or channel authentication records), these are just function's parameters.

I am sorry for wrong link. Provided branch has some enhancements to PCF, but does not have required constants.
At this moment constants are added manually and only when they are needed by someone.

If you miss some constant feel free to add it and create pull request.

**Comment by SeyfSV** [comment]
@JochemGit , branch with required commands merged to master

**Comment by JochemGit** [comment]
These are good news. :) Then I test the master tomorrow.

**Comment by JochemGit** [comment]
Until now everything works pretty well with the new version.

Sometimes it is hard to look all the time where to find the constants (CMQC.py or CMQCFC.py). I know, this is because of the c sources of MQ, but in python the disadvantage is, that I have to use the namespace pymqi.CMQC.<constant>.

Thank you very much for your help!

**Comment by dsuch** [comment]
@JochemGit - this is an apt observation indeed. Would you like to send in a pull request with a new module called const.py that would have code such as this for each CMQC*.py file?

```python
from CMQC import *
```

That would let one do something like ```from pymqi.const import SOME_NAME``` without having to figure out where it came from originally.

The names are guaranteed to be unique given that they are meant to be included from headers files on the C level.

**Comment by JochemGit** [comment]
Until now I am not familiar with pull requests. I see, what I can do.

**Comment by JochemGit** [comment]
I opened a pull request.
