### ISSUE TITLE
Subscription Filter 

### ISSUE THREAD

**Issue by alephnot0** [dsuch/pymqi#189]
I am trying to get a single subscription by the sub_id.  This would correspond to the mqsc command `DIS SUB SUBID(123)`.  During my testing, one of the things I have been attempting to use is a Filter.  Here is a snippet of what I am trying to do:

```
...
        args = {
                pymqi.CMQCFC.MQCACF_SUB_NAME: '*'.encode('utf-8')
            }

        id_filter = pymqi.Filter(pymqi.CMQCFC.MQBACF_SUB_ID).equal(subscription.encode())

        try:
            pcf = pymqi.PCFExecute(qmgr)
            subscription = pcf.MQCMD_INQUIRE_SUBSCRIPTION(args, [id_filter])
```

This snippet throws the following error from [here](https://github.com/dsuch/pymqi/blob/4420ff0318b78662109334cd915e992e439fbf7a/code/pymqi/__init__.py#L2291)

`pymqi.Error: selector [7016] is of an unsupported type (neither integer nor a string attribute). Send details to http://packages.python.org/pymqi/support-consulting-contact.html`

This link returns a 301, so at minimum, it seems as though this link should be updated.  I opened #188 to point to a better location.

The subscriber ID is a generated byte array, which is mixed utf-8 and hex content.  Is it possible with this library to filter by a byte array value?

**Comment by dsuch** [comment]
Hello,

the exception looks to be raised because the input to Filter is expected to be one of filters in the range between MQIA_FIRST and MQIA_LAST or MQCA_FIRST and MQCA_LAST - please have a look at the source code where the 'if' branches are.

However, I have never used this feature so I am not sure myself, whether the if conditions are too restrictive or is it that you provide invalid input.

Another thought - I wonder why you are providing a list with [id_filter] rather than id_filter itself on input to MQCMD_INQUIRE_SUBSCRIPTION?

**Comment by SeyfSV** [comment]
Hi @alephnot0, 
Please, check IBM [docs](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q088040_.htm)
Inquire Subscription does not have filter attributes. Try to use:
```
        args = {
                pymqi.CMQCFC.MQCACF_SUB_NAME: subscription.encode('utf-8')
            }
```

**Comment by alephnot0** [comment]
Thanks for the comments.  @SeyfSV I agree that this is what the IBM docs say.  I am trying to replicate a mqsc command of `DIS SUB SUBID(123)`.

```
args = {
                pymqi.CMQCFC.MQBACF_SUB_ID: '123'.encode('utf-8')
            }

        try:
            pcf = pymqi.PCFExecute(qmgr)
            subscription = pcf.MQCMD_INQUIRE_SUBSCRIPTION(args)
```

I have been playing around with the SUB_ID that is being sent.  I would expect that some sort of `subscription not found error` would be thrown, but instead I am getting: `pymqi.MQMIError: MQI Error. Comp: 2, Reason 2321: FAILED: MQRC_PARAMETER_MISSING` as long as I do not have MQCACF_SUB_NAME defined as an argument.

**Comment by alephnot0** [comment]
@dsuch the only reason I am providing a list to the pcf.MQCMD_INQUIRE_SUBSCRIPTION call is that that is what is done for inquiring messages.  I can attempt to send in only a singular list as an input, but if @SeyfSV 's comment is correct around filter attributes not being applicable for subscriptions, then I assume that it will not make a difference.

**Comment by dsuch** [comment]
@alephnot0 Sure, like I said, I have never really used this functionality so I may be wrong indeed.

@jjjw420 I think it was you who added subscription objects to PyMQI?

**Comment by SeyfSV** [comment]
@alephnot0 , if you get `MQRC_PARAMETER_MISSING` then try to use `pymqi.ByteString('123')` instead of `'123'.encode('utf-8')`.
MQBACF_SUB_ID is a ByteString attribute, and it does not 'eat' bytes

**Comment by alephnot0** [comment]
@SeyfSV and @dsuch again, thank you for the input.  I was still either getting a MQRC_PARAMETER_MISSING or a message telling me that the byte string was too long.  The message telling me that the byte string was too long was confusing to me as I was inputting the SUB_ID that I was given through a DIS SUB(*) type call.

I found a workaround for my own situation, so I will not be continuing to debug this situation.  In an attempt to give something to the next person who comes along with this issue... Our user flow consists of doing a DIS SUB(*) -> letting the user select the SUB_ID  that they want -> doing a DIS SUB SUB_ID(_) on that SUB_ID.  I will simply be retaining all attributes from the first DIS SUB(*) command and displaying them at a later time.

I am closing this issue, but I would still recommend looking at PR #188 as I do believe the link needs an update.

**Comment by dsuch** [comment]
Thanks @alephnot0 - the PR is merged now.

**Comment by SeyfSV** [comment]
Hi @alephnot0,
Look this, please:
```
    def test_gh189(self):
        args = {
                pymqi.CMQCFC.MQCACF_SUB_NAME: '*'.encode('utf-8'),
                pymqi.CMQCFC.MQIACF_SUB_ATTRS: [pymqi.CMQCFC.MQBACF_SUB_ID]
            }

        pcf = pymqi.PCFExecute(self.qmgr)
        subscriptions = pcf.MQCMD_INQUIRE_SUBSCRIPTION(args)

        print('\nSubscriptions:')
        for subscription in subscriptions:
            print('{}: {}'.format(subscription[pymqi.CMQCFC.MQBACF_SUB_ID], subscription[pymqi.CMQCFC.MQCACF_SUB_NAME]))

        args = {
                pymqi.CMQCFC.MQBACF_SUB_ID: pymqi.ByteString(subscriptions[0][pymqi.CMQCFC.MQBACF_SUB_ID]),
                pymqi.CMQCFC.MQIACF_SUB_ATTRS: [pymqi.CMQCFC.MQIACF_ALL]
            }

        print('\nGet subscription info by id for first subscription')
        subscriptions = pcf.MQCMD_INQUIRE_SUBSCRIPTION(args)
        for subscription in subscriptions:
            for item in subscription:
                print('{}:{}'.format(item, subscription[item]))
```
Output:
```
Subscriptions:
b'AMQ MQTEST      \xb6O\xcf^\x07\x1ez!': b'MQTEST SYSTEM.BROKER.INTER.BROKER.COMMUNICATIONS 414D51590101000000000000000000000000000000000000 SYSTEM.BROKER.ADMIN.STREAM MQ/MQTEST                                          /StreamSupport'
b'AMQ MQTEST      \xb4O\xcf^\x06a\xd2\x14': b'SYSTEM.DEFAULT.SUB'

Get subscription info by id for first subscription
7016:b'AMQ MQTEST      \xb6O\xcf^\x07\x1ez!'
3152:b'MQTEST SYSTEM.BROKER.INTER.BROKER.COMMUNICATIONS 414D51590101000000000000000000000000000000000000 SYSTEM.BROKER.ADMIN.STREAM MQ/MQTEST                                          /StreamSupport'
2094:b'SYSTEM.BROKER.ADMIN.STREAM/MQ/MQTEST                                          /StreamSupport'
2092:b'SYSTEM.BROKER.ADMIN.STREAM                      '
262:0
3154:b'SYSTEM.BROKER.INTER.BROKER.COMMUNICATIONS       '
3153:b'MQTEST                                          '
3135:b''
3160:b''
1321:0
3159:b''
7010:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
7015:b'AMQY\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
1273:2
1274:1
1244:-1
1271:1
1283:-3
1280:2
1275:1
1307:1
1289:1
1277:1
1288:1
3156:b'mqm         '
2004:b'2020-05-28'
2005:b'05:44:22'
2027:b'2020-05-28'
2028:b'05:44:22'
```

**Comment by alephnot0** [comment]
@SeyfSV, thank you! That method worked perfectly.  I like the convention of using github issue numbers for naming tests.  This type of example was what I needed.

**Comment by jjjw420** [comment]
Nice example!
