### ISSUE TITLE
INQUIRE_CONNECTION filters causing core dump

### ISSUE THREAD

**Issue by colross** [dsuch/pymqi#190]
I hope someone can help here. I seem to be running into an issue with filters on INQUIRE_CONNECTION. In my script, I am using the following:

CONNECTION_SEARCH={MQBACF_GENERIC_CONNECTION_ID:pymqi.ByteString(b''),MQIACF_CONNECTION_ATTRS:MQIACF_ALL,MQIACF_CONN_INFO_TYPE:MQIACF_CONN_INFO_ALL}

CHANNEL_FILTER=pymqi.Filter(MQIA_APPL_TYPE).equal(MQAT_USER)

My pcf is as follows (simplified):
response = pcf.MQCMD_INQUIRE_CONNECTION(CONNECTION_SEARCH,[CHANNEL_FILTER])

Without the channel filter, all is well, however when I add in the channel filter, depending on where I set the "CHANNEL_FILTER" variable, I get different results. Here are some of them:

Traceback (most recent call last):
  File "ibmmq.py", line 662, in <module>
    print("%s - %s"%(CHANNEL_FILTER,MQ))
  File "/usr/local/lib/python3.8/site-packages/pymqi/__init__.py", line 2242, in __repr__
    return msg % (self.__class__.__name__, hex(id(self)), self.selector, self.value, self.operator)
AttributeError: 'IntegerFilter' object has no attribute 'selector'
Aborted (core dumped)

  File "ibmmq.py", line 662, in <module>
    response = pcf.MQCMD_INQUIRE_CONNECTION(MQINFO[MQ]['CONNECTION_SEARCH'],[MQINFO[MQ]['CHANNEL_FILTER']])
  File "/usr/local/lib/python3.8/site-packages/pymqi/__init__.py", line 2358, in __call__
    rv = pymqe.mqaiExecute(qm_handle, CMQCFC.__dict__[self.__name], args_dict, filters)
pymqe.error: 'filter_selector' object is NULL.
Aborted (core dumped)

I printed out the value of 'CONNECTION_SEARCH' before it was called in one instance, and noticed that it seems to be getting overwritten (not by me - this is only set in one place):
HERE2
HERE - QMZ
<IntegerFilter at 0x7f1dc994f880 1:25:2>
HERE2
HERE - QMY
<IntegerFilter at 0x7f1dc994fa00 1:25:2>
HERE2
HERE - QMA
<requests.adapters.HTTPAdapter object at 0x7f1dc994f580> <------ Not correct

When I tried to force it back to the correct value, I get:
free(): invalid pointer
Aborted (core dumped)

I have tried with python3.6, 3.7 and 3.8 using:
9.1.0.5-IBM-MQC-Redist-LinuxX64 and 9.1.5.0-IBM-MQC-Redist-LinuxX64

pymqi version 1.10.1

Any thoughts?

**Comment by SeyfSV** [comment]
Hi @colross ,
Which pymqi version do you use?

**Comment by SeyfSV** [comment]
Hi @colross ,
I reproduced `pymqe.error: 'filter_selector' object is NULL.` error. It occurs when CHANNEL_FILTER is None or any other wrong value. Something like:
```
results = pcf.MQCMD_INQUIRE_CONNECTION(attrs, [None])
```
This error `pymqe.error: 'filter_selector' object is NULL.` occurs because you try to print non-initialised `IntegerFilter` object.
`selector` attribute initializing occurs in `IntegerFilter.__init()__` method.

**Comment by colross** [comment]
Thanks SeyfSV - this is true - the real question is why it is blank? The variable gets set at the beginning of the script and never changed.

When I print out the value of the filter, however, it changes through the iterations.
<IntegerFilter at 0x7f1dc994fa00 1:25:2> <----- Correct
<requests.adapters.HTTPAdapter object at 0x7f1dc994f580> <------ Not correct

This seems to be an underlying C issue, especially as resetting that variable seems to result in:
free(): invalid pointer
Aborted (core dumped)

**Comment by SeyfSV** [comment]
Are you sure, that your application does not use threads?
I had some similar issue when I wrote REST App with MQ backend.

I will close issue, because it does not related to pymqi.

I recommend you to create question on stackoverflow.com, there are more people and I hope someone will help you with your code.

**Comment by colross** [comment]
I am not using threads. The only way I can get it to work is if I don't use any filtering on pymqi.

**Comment by SeyfSV** [comment]
I checked with this snippet, that was added to `code/tests/test_pcf.py`:
```
    def test_connections(self):
        attrs = {
            pymqi.CMQCFC.MQBACF_GENERIC_CONNECTION_ID: pymqi.ByteString(''),
            pymqi.CMQCFC.MQIACF_CONN_INFO_TYPE: pymqi.CMQCFC.MQIACF_CONN_INFO_CONN,
            pymqi.CMQCFC.MQIACF_CONNECTION_ATTRS: pymqi.CMQCFC.MQIACF_ALL
        }
        pcf = pymqi.PCFExecute(self.qmgr)

        fltr = pymqi.Filter(pymqi.CMQC.MQIA_APPL_TYPE).equal(pymqi.CMQC.MQAT_USER)

        results = pcf.MQCMD_INQUIRE_CONNECTION(attrs, [fltr])
        pcf.disconnect
        print(results)
```
![image](https://user-images.githubusercontent.com/25712100/83163878-36430080-a114-11ea-8479-9482b4541724.png)

**Comment by colross** [comment]
I have this exact same issue when doing both inquire queue and inquire conn only when I am using a filter. For other people who may run into similar, I have it working now - the only way I can get it working is to create the variable, use it and immediately delete it:
ALTER_DATE=pymqi.Filter(MQCA_ALTERATION_DATE).greater(tmpdate)
response = pcf.MQCMD_INQUIRE_Q(MQINFO[MQ]['QUEUE_SEARCH'],[ALTER_DATE])
del ALTER_DATE

**Comment by SeyfSV** [comment]
I hope this will answer to question: https://stackoverflow.com/questions/575196/why-can-a-function-modify-some-arguments-as-perceived-by-the-caller-but-not-oth

**Comment by colross** [comment]
Thanks @SeyfSV I guess I would expect if it were as simple as a python variable being overwritten, it would cause an handleable exception and not a python core dump that suggests that there is a pointer issue in the C code.
free(): invalid pointer
Aborted (core dumped)

Anyway - appreciate your time. As mentioned, I worked around it by deleting and resetting my variable in each iteration.
