### ISSUE TITLE
Waiting for lots of data with MQCMD_INQUIRE_Q

### ISSUE THREAD

**Issue by colross** [dsuch/pymqi#191]
Hi - I hope this is the correct place to ask a question. If not, I apologize.
I have a queue manager with 8000 queues on it. I want to pull down all queue info, however, there seems to be a 300 second timeout for me to get the data, after which I catch an exception:
WARNING: MQRC_NO_MSG_AVAILABLE

I am using pcf.MQCMD_INQUIRE_Q({MQCA_Q_NAME:MQ_QNAME,MQIACF_CLUSTER_INFO:1,MQIACF_Q_ATTRS:MQIACF_ALL})
If found pymqi.GMO() which has a wait interval that I could set, however, it is unclear to me where/how I specify this. The only place I see it specified is getting data off a queue using queue.get.
What would be the best way for me to extend the 300 second timeout?

Thanks for your assistance.

Cheers
Colin

**Comment by SeyfSV** [comment]
Hi @colross,
Current release does not allow to set wait interval.
pymqi uses MQAI [mqExecute](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q089310_.htm) cal ([link to code in master](https://github.com/dsuch/pymqi/blob/e23b190ad309e4bfb176999f71601525d66e1664/code/pymqi/pymqe.c#L1620))
```
mqExecute((MQHCONN) lQmgrHandle, (MQLONG) lCmdCode, MQHB_NONE, adminBag, responseBag, MQHO_NONE, MQHO_NONE, &compCode, &compReason);
```
Third parameter is OptionsBag, it can be used for setting wait interval, and it is MQHB_NONE.
If you wish you can modify pymqi and propose PR.

Also we have another new [branch](https://github.com/dsuch/pymqi/tree/gh92-move-from-mqai), that does not use MQAI at all. Some  [info](https://github.com/dsuch/pymqi/issues/92).
Today I added `response_wait_interval` attribute to `PCFExecute`. I hope you can use it without any changes in your code.

**Comment by colross** [comment]
@SeyfSV - thanks you. Will take a look. Much appreciated!

**Comment by SeyfSV** [comment]
Hi, @colross, what about question? Can we close it?
