### ISSUE TITLE
Passing Corelation ID in Hex Format

### ISSUE THREAD

**Issue by AravindPillai** [dsuch/pymqi#192]
I recently inherited a testing framework using PYMQI to put a message on IBM Websphere Queue. I fixed most of the code i need by going through this link

https://dsuch.github.io/pymqi/examples.html#how-to-correlate-request-and-response-messages-using-correlationid

The only pending issue is the format of correlation ID. I tried quite a few options but MQ is converting the correlation ID Into byte array (seems IBM MQ default setting) before throwing it on the Q. All my downstream systems are looking for a HEX value and is breaking.

I am stuck on this for a few days now. Is there a way to force the correlation ID in message properties?.

Please let me know

Regards Aravind

**Comment by JoshMcMQ** [comment]
See my response on SO.

**Comment by apillai-incomm** [comment]
Thanks a lot. Updated the question.

**Comment by dsuch** [comment]
Hello, can you share a link to StackOverflow in case it is needed in the future? Thanks.

**Comment by JoshMcMQ** [comment]
Edited with the link.

**Comment by AravindPillai** [comment]
Hi All,

Sorry for the delay, i went forward and updated the question with more details. Please let me know.

Regards
Aravind

**Comment by SeyfSV** [comment]
@AravindPillai I close this issue, because I think it is not related to pymqi.
Don't worry, you see that we try to help you on SO

**Comment by apillai-incomm** [comment]
@SeyfSV Yes thanks a lot. I resolved my issue, i will post it as an Answer on SO. But you guyz gave me the right direction and the Team was able to change queue configurations and was able to fix. Ultimately thanks for all the guidance.
