### ISSUE TITLE
Problem with MQCMD_SET_AUTH_REC // Parameters ok?

### ISSUE THREAD

**Issue by JochemGit** [dsuch/pymqi#193]
I try to set an authentication record.

With MQSC the statement is
`SET AUTHREC PROFILE('LQ*') OBJTYPE(QUEUE) GROUP('ssh') AUTHADD(BROWSE, INQ, GET, PUT)`

And this works.
With PCF and pymqi I fail. I prepare the follwing dict:
`{3067: 'LQ*', 1016: 1, 3066: ['ssh'], 1116: [2, 10, 9, 11]}`

Beautified:
```
MQCACF_AUTH_PROFILE_NAME: LQ*
MQIACF_OBJECT_TYPE: MQOT_Q
MQCACF_GROUP_ENTITY_NAMES: ['ssh']
MQIACF_AUTH_ADD_AUTHS [
  MQAUTH_BROWSE
  MQAUTH_INQUIRE
  MQAUTH_INPUT
  MQAUTH_OUTPUT
]
```

After I execute the function MQCMD_SET_AUTH_REC() I get the following error and reason code:
```
Traceback (most recent call last):
  File "./queue.py", line 256, in <module>
    setAuthorityRecord(mymqobjectAuth, pcf)
  File "./queue.py", line 180, in setAuthorityRecord
    pcf.MQCMD_SET_AUTH_REC(cmdArgs2)
  File "/usr/local/lib/python3.6/dist-packages/pymqi-1.10.1-py3.6-linux-x86_64.egg/pymqi/__init__.py", line 2365, in __call__
    raise MQMIError(rv[-2], rv[-1])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2324: FAILED: MQRC_INQUIRY_COMMAND_ERROR
```

Any idea, what the problem is? Thank you for your help!

**Comment by SeyfSV** [comment]
Hi @JochemGit,
current [version](https://github.com/dsuch/pymqi/blob/e23b190ad309e4bfb176999f71601525d66e1664/code/pymqi/pymqe.c#L1568) supports only lists with Long type values.
As result `MQCACF_GROUP_ENTITY_NAMES: ['ssh']` couldn't be processed.

You can use newer version from this [branch](https://github.com/dsuch/pymqi/tree/gh92-move-from-mqai). More info about it in #92: https://github.com/dsuch/pymqi/issues/92#issuecomment-599189251
It's more C-like, but allow to use any PCF commands and parameters. 
```
        attrs = []
        attrs.append(pymqi.CFST(Parameter=pymqi.CMQCFC.MQCACF_AUTH_PROFILE_NAME,
                                String=b'LQ*'))
        attrs.append(pymqi.CFIN(Parameter=pymqi.CMQCFC.MQIACF_OBJECT_TYPE,
                                Value=pymqi.CMQC.MQOT_Q))
        attrs.append(pymqi.CFSL(Parameter=pymqi.CMQCFC.MQCACF_GROUP_ENTITY_NAMES,
                                Strings=[b'ssh']))
        attrs.append(pymqi.CFIL(Parameter=pymqi.CMQCFC.MQIACF_AUTH_ADD_AUTHS,
                                Values=[pymqi.CMQCFC.MQAUTH_OUTPUT, pymqi.CMQCFC.MQAUTH_INPUT]))

        pcf = pymqi.PCFExecute(self.qmgr)
        results = pcf.MQCMD_SET_AUTH_REC(attrs)

```
New version is backward compatible, you can use new style only if something does not work.
It has not documentation in this moment, because we need someone who approve it usability.

**Comment by JochemGit** [comment]
Thank you for your help!

I implemented it for `MQCMD_SET_AUTH_REC` and `MQCMD_DELETE_AUTH_REC`. It works pretty well.

What do you think, when can it be merged to the master branch? Are there still tests to do?

**Comment by SeyfSV** [comment]
@dsuch , what do you think about merging?

**Comment by dsuch** [comment]
Hi @SeyfSV,

these days, my IBM MQ needs are mostly limited to simple put and get calls from higher-level applications so I leave it up to you and @JoshMcMQ - I am confident you are able to improve the current situation with PCF.

For sure, the usage of MQAI will need to go one day so this looks like a good opportunity to do it.

**Comment by SeyfSV** [comment]
@dsuch , OK.
@JochemGit, If you are not against it, you will be a tester :). As soon you say OK, it works well for all your needs, I will merge it to master.

**Comment by JochemGit** [comment]
@SeyfSV Of course I can support you, as far as my time frame allows it.
But for saying the branch can be merged to the master, I need to know about the differences (new features) of the branch. I guess the master should be stable. ;)
Until now I tested, what you know about (authentication records and response_wait_interval).

**Comment by SeyfSV** [comment]
@JochemGit , don't worry :). I do not hope, that you will test all [changes](https://github.com/dsuch/pymqi/issues/92#issuecomment-599189251), I just hope, that you will use something, that not covered by tests, and will report to me for fixing it.

**Comment by SeyfSV** [comment]
@JochemGit , let's close this issue, because it is solved.

**Comment by JochemGit** [comment]
@SeyfSV I close this issue. But something that worked ealier does not work anymore, so I open a new one. ;)

**Comment by SeyfSV** [comment]
@JochemGit New version released!
