### ISSUE TITLE
Problem with MQCMD_INQUIRE_Q in branch gh92-move-from-mqai

### ISSUE THREAD

**Issue by JochemGit** [dsuch/pymqi#195]
This worked last time I tried it with the master, but now I get an error.

`{2016: 'SYSTEM.DEFAULT.ALIAS.QUEUE', 1002: 1009}`

```
MQCA_Q_NAME: SYSTEM.DEFAULT.ALIAS.QUEUE
MQIACF_Q_ATTRS: MQIACF_ALL
```

Output:
```
Traceback (most recent call last):
  File "./genericPCF.py", line 112, in <module>
    res = pcf.MQCMD_INQUIRE_Q(args_dis_q)
  File "/usr/local/lib/python3.6/dist-packages/pymqi-1.10.1-py3.6-linux-x86_64.egg/pymqi/__init__.py", line 2675, in __call__
    res, control = self.__pcf.unpack(message)
  File "/usr/local/lib/python3.6/dist-packages/pymqi-1.10.1-py3.6-linux-x86_64.egg/pymqi/__init__.py", line 2810, in unpack
    raise MQMIError(mqcfh.CompCode, mqcfh.Reason)
pymqi.MQMIError: MQI Error. Comp: 2, Reason 3014: FAILED: MQRCCF_CFIN_PARM_ID_ERROR

```

**Comment by JochemGit** [comment]
I guess, it happens, when I use MQIACF_ALL to see all parameters.

**Comment by JochemGit** [comment]
Well, I guess the problem was in my code. I did not use a list there.
Is it possible, the code from the master branch is more fault-tolerant?
I like the new behaviour.

**Comment by SeyfSV** [comment]
No, it is not fault-tolerant.
MQAI does not have lists at all, if you need list you should put items one by one to the Bag, or just one, in your case. MQAI know that 1002 parameter should be a list, and create right PCF with MQCFIL structure.
I will add this workaround, but looping through all attributes in CMQCFC is not good, imho.
```
                        for item in CMQCFC.__dict__:
                            if (item[:7] == 'MQIACF_'
                                and item[-6:] == '_ATTRS'
                                and CMQCFC.__dict__[item] == key):
                                    is_list = True
                                    break
                        if not is_list:
                            parameter = CFIN(Parameter=key,
                                            Value=value)
                        else:
                            parameter = CFIL(Parameter=key,
                                            Values=[value])
```
Using single value in attribute that should be a list is error or mistake. But new behaviour can broke programs.

**Comment by dsuch** [comment]
Hi @SeyfSV - I have not looked into the implementation but is it possible to make it not break backward compatibility? I cannot recall a single case of doing it, it has practically never happened.

Some time ago I received a question from people using PyMQI and Python 2.1 embedded in their systems back in the times of Windows 2000 and, in this context, relatively recent versions of PyMQI were coping just fine with it all.

Naturally, this is an extreme example but I am just saying that it is really important not to break anything. Is that possible in this case?

**Comment by SeyfSV** [comment]
@JochemGit , please, check behaviour with your "problem" code.

**Comment by JochemGit** [comment]
Yes, the behaviour is the old one again. 

```
args_dis_q = {pymqi.CMQC.MQCA_Q_NAME: 'SYSTEM.DEFAULT.ALIAS.QUEUE',
              pymqi.CMQCFC.MQIACF_Q_ATTRS: pymqi.CMQCFC.MQIACF_ALL}
```

and

```
args_dis_q = {pymqi.CMQC.MQCA_Q_NAME: None,
              pymqi.CMQCFC.MQIACF_Q_ATTRS: [pymqi.CMQCFC.MQIACF_ALL]}
```

work the same way now.

Still, when this is not the recommended way anymore to use pymqi, it would be good, if the [Examples](https://dsuch.github.io/pymqi/examples.html#how-to-display-queues) would be updated accordingly. This was my starting point with pymqi.

**Comment by SeyfSV** [comment]
@JochemGit, please, take a look on this: https://stackoverflow.com/questions/62250844/ibm-mq-pcf-parameters-order
I think you should know about this issue.
I have some idea about workaround, but I hope that someone give me other ideas about issue.

I created new issue #197 about examples.

Lets close this issue.

**Comment by JoshMcMQ** [comment]
@chughts @oljarast see the above SO post, can you take this as a internal defect to resolve vs someone reporting via a customer opened case?
