### ISSUE TITLE
IBM MQ Topic Publish Error

### ISSUE THREAD

**Issue by agamjajoo** [dsuch/pymqi#196]
Hi, I am trying to use the below sample to publish a message on the topic

From: https://dsuch.github.io/pymqi/examples.html
Python 2.7
OS - Windows Server 2012

How to publish messages on topics
Code:

```python
import pymqi

queue_manager = 'QM1'
channel = 'DEV.APP.SVRCONN'
host = '127.0.0.1'
port = '1414'
topic_string = '/currency/rate/EUR/USD'
msg = '1.3961'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.QueueManager(None)
qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)

topic = pymqi.Topic(qmgr, topic_string=topic_string)
topic.open(open_opts=pymqi.CMQC.MQOO_OUTPUT)
topic.pub(msg)
topic.close()

qmgr.disconnect()
```

I've replaced the queue_manager, channel, host, port and topic_string as per available IBM_MQ instance available with me. 
When running the above code, I get 

```
Traceback (most recent call last):
  File "D:/dev/publish_topic.py", line 31, in <module>
    qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)
**TypeError: connect_tcp_client() takes exactly 7 arguments (5 given)**
```

I've tried running other examples, from https://dsuch.github.io/pymqi/examples.html, get and put operations. They are working fine.

**Comment by agamjajoo** [comment]
I've tried this again on Py3mqi, received a better message this time. connect_tcp-client also requires user and password. Now, I am using a non-ssl channel to connect to the queue manager, there is no user and password defined in this case.

qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)
TypeError: connectTCPClient() missing 2 required positional arguments: 'user' and 'password'

**Comment by JoshMcMQ** [comment]
Are you using pymqi or py3mqi?  If the former which version?

**Comment by dsuch** [comment]
Hi @agamjajoo - py3mqi is a completely unrelated piece of software that unfortunately has a similar name. PyMQI has nothing to do with it. I am just saying it in case you are actually using py3mqi instead of PyMQI.

**Comment by agamjajoo** [comment]
First of all, thanks to both for quick response.
@JoshMcMQ - On Python 2.7, I am trying with pymqi==1.8.0
On Python3 (3.7.7), I am trying with py3mqi==1.6.0. 
But I think the later isn't valid anymore as @dsuch said, py3mqi is unrelated. I got this idea from from one of the stackoverflow thread, that py3mqi is the module to be used when trying with python3 : https://stackoverflow.com/questions/45514331/ibm-mq-python3-module

**Comment by JoshMcMQ** [comment]
Pymqi has had python 3 support since 1.8, you should try the latest version 1.10.1 and see if you have the same problem.

**Comment by agamjajoo** [comment]
@JoshMcMQ : I've further tried with pymqi==1.10.1
Got the below exception asking for user and password. As referenced earlier, my channel is a non-ssl setup, so doesn't have a user and password that I can use. 

    qmgr = qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)
TypeError: connect_tcp_client() missing 2 required positional arguments: 'user' and 'password'

Process finished with exit code 1

**Comment by dsuch** [comment]
@agamjajoo Please always post a full traceback rather than the error message only. Thanks.

**Comment by agamjajoo** [comment]
Yes @SeyfSV , I tried passing None as user and password but it gave the below exception.

E:\Users\..\..\..\Python37\python.exe D:/../../pub.py
Traceback (most recent call last):
  File " D:/../../pub.py ", line 14, in <module>
    qmgr = qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info, user, password)
  File " E:\Users\..\..\..\Python37\lib\site-packages\pymqi\__init__.py", line 1374, in connect_tcp_client
    self.connect_with_options(name, **kwargs)
  File " E:\Users\..\..\..\Python37\lib\site-packages\pymqi\__init__.py", line 1344, in connect_with_options
    rv = pymqe.MQCONNX(name, options, cd, user_password, sco.pack())
pymqe.error: MQSCO wrong size. Given: 560, expected 544

Process finished with exit code 1

**Comment by agamjajoo** [comment]
> @agamjajoo Please always post a full traceback rather than the error message only. Thanks.

@dsuch Sure, I am new to github and python, will keep this in mind going forward, thank you for advice.

**Comment by SeyfSV** [comment]
@agamjajoo , please, provide MQ version from environment you run python (Server or Client).
I think you have pymqe library compiled with older MQ version (not definitely):

What can be done:
* try to reinstall pymqi in current environment
* try version from master branch - MQSCO size checking removed in 4420ff0318b78662109334cd915e992e439fbf7a

**Comment by agamjajoo** [comment]
@SeyfSV , I had MQ Client version 7.0.1.6, I've installed pymqi==1.10.1 recently so thought yes, it's a possibility that pymqe library could be complied with older MQ version, tried the below steps:
1. Uninstalled pymqi
2. Uninstalled MQ Client 7 
3. Installed MQ client 8 
4. Installed pymqi ==1.10.1

Unfortunately, I am getting a different exception since then,
```
E:\Users......\Python37\python.exe D:/../../pub_topic.py
D:/../../pub_topic.py
Traceback (most recent call last):
  File "D:/../../pub_topic.py", line 17, in <module>
    topic.open(open_opts=pymqi.CMQC.MQOO_OUTPUT)
  File "C:\Users\..\..\Python37\lib\site-packages\pymqi\__init__.py", line 1957, in open
    self.__real_open()
  File "C:\Users\..\..\Python37\lib\site-packages\pymqi\__init__.py", line 1852, in __real_open
    rv = pymqe.MQOPEN(self.__queue_manager.getHandle(),
AttributeError: 'NoneType' object has no attribute 'getHandle'

Process finished with exit code 1
```

**Comment by JoshMcMQ** [comment]
Glad it is working for you.   7.0 went out of support almost 5 years ago (2015-09-30).  Even 8.0 which you just upgraded to was end of support 2020-04-30.  Anyone in the future that reads this should try upgrading to a supported level of IBM MQ if they are using an older version.

**Comment by agamjajoo** [comment]
Closing the issue.
