### ISSUE TITLE
2035 MQRC_NOT_AUTHORIZED error when connecting to IBM MQ

### ISSUE THREAD

**Issue by mpotashnik** [dsuch/pymqi#209]
I attempting to connect IBM MQ as follows

queuemanager = pymqi.connect(qm, ch, conn, uid, pwd)

connect method fails with 2035 MQRC_NOT_AUTHORIZED

**Comment by JoshMcMQ** [comment]
This is not pymqi issue,  this is a general IBM MQ issue.   This means authorization error and you will need to check the queue manager's AMQERR01.LOG for more specific details. 

Please read the past issues that mention 2035 for more information [here](https://github.com/dsuch/pymqi/search?q=2035&type=Issues).
