### ISSUE TITLE
Improve unit testing

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#210]
- [ ] Add binding mode testing

- [ ] Add 32-bit testing: install (windows, linux, mac?) and unit (linux)
  * x86 windows install tests was added in e12f6abd5cf4cec8e8c7d754e917c3e1f46d0121
  * actions/setup-python does not have x86 versions for ubuntu and macos runners. Maybe python should be installed manually.

- [ ] Add tests for checking pymqi constants with ones from C header files.
        Maybe some converter script should be created, as h2py.

What should be done when it might be possible 

- [ ] Add unit testing for Mac
	Unit testing uses ibmcom/mq docker image (MQ Server).
	At that moment (Jun 2020) Mac runner does not have docker.

- [ ] Add unit testing for Windows
	Unit testing uses ibmcom/mq image (MQ Server). It is linux images.
	At that moment (Jun 2020) Windows runner does not allow to run linux containers.

- [ ] Add install testing for python 2.7 on Windows
	At that moment (Jun 2020) Windows github runner does not have required libraries for building python 2.7 modules:

	> error: Microsoft Visual C++ 9.0 is required

	Installing this modules require additional work

More info in #159 and #163

**Comment by dsuch** [comment]
Mass-closing old tickets.
