### ISSUE TITLE
PCF usage of v1.11 is not fully backward compatible for Python before 3.7

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#211]
v1.10 and early are based on MQAI and use dictionary for setting PCF parameters.
Order of parameters has restrictions, and that order controlled by MQAI is this case.
In v1.11 MQAI was replaced with raw PCF, and order of parameters defined in dictionary is not persistent for Python before 3.7.
> Additionally, CPython 3.6+ uses a new implementation of dictionaries, which makes them appear sorted by insertion order (though you can only rely on this behavior in Python 3.7+).

This issue should be fixed only if someone get it.

**Comment by dsuch** [comment]
I am fine as it is but I just want to confirm - why can you not use OrderedDict instances that are built in from Python 2.7 onwwards?

**Comment by SeyfSV** [comment]
IMHO: It should be used outside of pymqi. pymqi only receives dictionary (dict or OrderedDict) as parameter for PCFExecute methods.

**Comment by dsuch** [comment]
I see, thanks.

**Comment by dsuch** [comment]
Mass-closing old tickets.
