### ISSUE TITLE
Add filter parameters unpack to PCF

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#219]
PCF message can [contain](https://github.com/dsuch/pymqi/issues/204#issuecomment-653715935) filter parameters in it.

**Comment by SeyfSV** [comment]
In reply to https://github.com/dsuch/pymqi/issues/204#issuecomment-653715935

14 is MQCFT_STRING_FILTER, can other filters occur in EVENT message?
I just added this for CFSF and commit it to branch gh219-pcf-unpack-filters
```
            elif parameter_type == CMQCFC.MQCFT_STRING_FILTER:
                parameter = CFSF()
                parameter.unpack(message[cursor:cursor + CMQCFC.MQCFSF_STRUC_LENGTH_FIXED])
                value = [parameter.Operator, parameter.FilterValue]
```
What do you think about output value - list with two items?

**Comment by Skyler-Altol** [comment]
Honestly I'm not 100% certain what can occur in these messages so I won't comment on the output values as I'm unqualified to do so. I've been taking a more... "trial and error" approach with this, basically throwing PCFExecute.unpack() at everything and seeing what sticks and what doesn't in the hopes of finding any edge cases like this one.
