### ISSUE TITLE
Running pymqi test-suite using 'nosetest' returns errors

### ISSUE THREAD

**Issue by rkluger** [dsuch/pymqi#22]
Hi Dariusz, 
sorry must provide my terminal output running the test-suite inline (Uploading a file failed)
>>>
test_h2py (test_h2py.Testh2py)
Test that modules generated automatically by h2py have no unwanted duplicate entries. ... FAIL
test_add_folder (test_rfh2.TestRFH2)
Test the addition of a XML folder. ... ok
test_buffer_too_short_for_complete_rfh2_exception (test_rfh2.TestRFH2)
Test exception occurs when buffer is too short for complete RFH2. ... ok
test_buffer_too_short_for_default_rfh2_exception (test_rfh2.TestRFH2)
Test exception occurs when buffer is too short for default RFH2. ... ok
test_encoding_on_pack_big_endian (test_rfh2.TestRFH2)
Test that pack() creates numeric fields with correct encoding. Big endian Test. ... ok
test_encoding_on_pack_small_endian (test_rfh2.TestRFH2)
Test that pack() creates numeric fields with correct encoding. Small endian Test. ... ok
test_folder_not_well_formed_exception_on_add (test_rfh2.TestRFH2)
Test exception when adding a not well formed XML folder. ... FAIL
test_folder_not_well_formed_exception_on_parse (test_rfh2.TestRFH2)
Test exception when parsing a message that contains not well formed XML folder. ... ok
test_incorrect_strucid_exception (test_rfh2.TestRFH2)
Test exception that occurs if StrucId is incorrect. ... ok
test_parse_default_rfh2 (test_rfh2.TestRFH2)
Test parsing of default RFH2 only. ... ok
test_parse_rfh2 (test_rfh2.TestRFH2)
Test that a known correct 3rd party message parses correctly. ... ok
test_parse_rfh2_with_correct_encoding (test_rfh2.TestRFH2)
Parse known correct message with it's correct encoding. ... ok
test_parse_rfh2_with_incorrect_encoding (test_rfh2.TestRFH2)
Parse known correct message with it's incorrect encoding. ... ok
test_rfh2_create (test_rfh2.TestRFH2)
Test the creation of a brand new RFH2.  Compare the resulting byte array against identical known correct message. ... ok
test_rfh2_pack (test_rfh2.TestRFH2)
Test pack() by comparing output of pack() against original message. ... ok

======================================================================
FAIL: test_h2py (test_h2py.Testh2py)
Test that modules generated automatically by h2py have no unwanted duplicate entries.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_h2py.py", line 56, in test_h2py
    self.fail(msg)
AssertionError:
MQCD_LENGTH_10 is defined 2 times in <module 'pymqi.CMQXC' from '/var/tmp/pymqi_evaluation/pymqi-venv/lib64/python2.7/site-packages/pymqi/CMQXC.pyc'>
MQCD_LENGTH_11 is defined 2 times in <module 'pymqi.CMQXC' from '/var/tmp/pymqi_evaluation/pymqi-venv/lib64/python2.7/site-packages/pymqi/CMQXC.pyc'>

======================================================================
FAIL: test_folder_not_well_formed_exception_on_add (test_rfh2.TestRFH2)
Test exception when adding a not well formed XML folder.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2.py", line 251, in test_folder_not_well_formed_exception_on_add
    self.assertEqual(str(e), "PYMQI Error: RFH2 - XML Folder not well formed. Exception: Opening and ending tag mismatch: b line 1 and a, line 1, column 12", "Not XML Folder not well formed on exception (add_folder)?." )
AssertionError: Not XML Folder not well formed on exception (add_folder)?.

----------------------------------------------------------------------
Ran 15 tests in 0.020s

FAILED (failures=2)
test_get_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Use get_rfh2 to get a known correct 3rd party message containing Multiples RFH2 headers. ... ERROR
test_get_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Use get_rfh2 to get a known correct 3rd party message that contains a single RFH2 header. ... ERROR
test_put_get_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new RFH2 message containing multiple RFH2 headers with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message. ... ERROR
test_put_get_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new rfh2 with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message. ... ERROR
test_put_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new RFH2 message containing multiple RFH2 headers and use get to get it from the queue.  Compare it against know correct message. ... ERROR
test_put_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new rfh2 and use get to get it from the queue.  Compare it against know correct message. ... ERROR

======================================================================
ERROR: test_get_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Use get_rfh2 to get a known correct 3rd party message containing Multiples RFH2 headers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: test_get_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Use get_rfh2 to get a known correct 3rd party message that contains a single RFH2 header.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: test_put_get_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new RFH2 message containing multiple RFH2 headers with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: test_put_get_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new rfh2 with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: test_put_rfh2_multiple (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new RFH2 message containing multiple RFH2 headers and use get to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: test_put_rfh2_single (test_rfh2_put_get.TestRFH2PutGet)
Create and put a new rfh2 and use get to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=6)
.F.E.......F........EEEEEE
======================================================================
ERROR: Connecting without user credentials provided should not succeed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_mq80.py", line 75, in test_connect_without_credentials
    raise Exception('Excepted for the test to fail without user credentials')
Exception: Excepted for the test to fail without user credentials

======================================================================
ERROR: Use get_rfh2 to get a known correct 3rd party message containing Multiples RFH2 headers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: Use get_rfh2 to get a known correct 3rd party message that contains a single RFH2 header.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: Create and put a new RFH2 message containing multiple RFH2 headers with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: Create and put a new rfh2 with put_rfh2 and use get_rfh2 to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: Create and put a new RFH2 message containing multiple RFH2 headers and use get to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
ERROR: Create and put a new rfh2 and use get to get it from the queue.  Compare it against know correct message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2_put_get.py", line 48, in setUp
    raise e
TypeError: connectTCPClient() takes exactly 7 arguments (5 given)

======================================================================
FAIL: Test that modules generated automatically by h2py have no unwanted duplicate entries.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_h2py.py", line 56, in test_h2py
    self.fail(msg)
AssertionError:
MQCD_LENGTH_10 is defined 2 times in <module 'pymqi.CMQXC' from '/var/tmp/pymqi_evaluation/pymqi-venv/lib64/python2.7/site-packages/pymqi/CMQXC.pyc'>
MQCD_LENGTH_11 is defined 2 times in <module 'pymqi.CMQXC' from '/var/tmp/pymqi_evaluation/pymqi-venv/lib64/python2.7/site-packages/pymqi/CMQXC.pyc'>

======================================================================
FAIL: Test exception when adding a not well formed XML folder.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/pymqi_evaluation/pymqi.git/trunk/code/tests/test_rfh2.py", line 251, in test_folder_not_well_formed_exception_on_add
    self.assertEqual(str(e), "PYMQI Error: RFH2 - XML Folder not well formed. Exception: Opening and ending tag mismatch: b line 1 and a, line 1, column 12", "Not XML Folder not well formed on exception (add_folder)?." )
AssertionError: Not XML Folder not well formed on exception (add_folder)?.

----------------------------------------------------------------------
Ran 26 tests in 0.120s

FAILED (errors=7, failures=2)

<<<

**Comment by hjoukl** [comment]
This issue gets fixed by #23.
