### ISSUE TITLE
PYMQI on IBM iSeries

### ISSUE THREAD

**Issue by Honeybee427** [dsuch/pymqi#222]
We have an IBM iSeries machine in our shop with MQ and python installed.
What would it take to use PYMQI on this server?

Thanks

**Comment by dsuch** [comment]
Hello @Honeybee427,

PyMQI is a Python package, here are details of how to install one:

https://packaging.python.org/tutorials/installing-packages/

**Comment by JoshMcMQ** [comment]
You may need to add in the iSeries scientific compiler info,  but it should work.

**Comment by Honeybee427** [comment]
Thanks for the response.

Python is farily new to the iSeries of I am guessing that the proper compiler is missing.
I tried PIP and it failed with 
****_-bash-4.4$  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall                                                                              -O2 -g -maix64 -O2 -g -maix64 -DPYQMI_BINDINGS_MODE_BUILD=0 -I/usr/mqm/inc -I/Q                                                                             OpenSys/pkgs/include/python3.6m -c code/pymqi/pymqe.c -o build/t_emp.os400-powerp                                                                             c64-3.6/code/pymqi/pymqe.o
-bash: gcc: command not found_**_**

Is it possible to use the iSeries C compiler to complete this install.

**Comment by dsuch** [comment]
Hello @Honeybee427 - I am not sure why you closed the ticket? If you resolved it, please share your solution with other people. Thanks.

**Comment by Honeybee427** [comment]
Whoops, closed it by accident.

**Comment by JoshMcMQ** [comment]
@Honeybee427 I mentioned in my comment: You may need to add in the iSeries scientific compiler info, but it should work.

**Comment by atulk0** [comment]
@Honeybee427 you can use IBM i using the ILE C++ compiler. 

IBM ILE C++ for IBM i is a native compiler for C++ programs. You can refer the IBM knowledge center for more details.

[https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzarf/sc09481602.htm](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzarf/sc09481602.htm)

**Comment by Honeybee427** [comment]
I was able to install the gcc-aix compiler. Now when I run PIP, it fails with 
   _gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -g -maix64 -O2 -g -maix64 -DPYQMI_BINDINGS_MODE_BUILD=0 -I/usr/mqm/inc -I/QOpenSys/pkgs/include/python3.6m -c code/pymqi/pymqe.c -o build/temp.os400-powerpc64-3.6/code/pymqi/pymqe.o
    code/pymqi/pymqe.c:78:18: fatal error: cmqc.h: No such file or directory
     #include <cmqc.h>_
I have the MQ header files but this server is an iSeries and MQ and the files are in a different library on the server. How can I determine where the compiler is looking for the MQ header files?

**Comment by atulk0** [comment]
@Honeybee427, is QCXXN library there in your library list?

**Comment by Honeybee427** [comment]
Thanks atulk0, Currently I am trying to get the PIP program to do the install.
I copied my iSereis H file to /usr/mqm/inc and ran the PIP install.
It has progressed to the following point:
 _gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -g -maix64 -O2 -g -maix64 -DPYQMI_BINDINGS_MODE_BUILD=0 -I/usr/mqm/inc -I/QOpenSys/pkgs/include/python3.6m -c code/pymqi/pymqe.c -o build/temp.os400-powerpc64-3.6/code/pymqi/pymqe.o
    /QOpenSys/pkgs/lib/python3.6/config-3.6m/ld_so_aix gcc -pthread -bI:/QOpenSys/pkgs/lib/python3.6/config-3.6m/python.exp -Wl,-blibpath:/QOpenSys/pkgs/lib:/QOpenSys/usr/lib build/temp.os400-powerpc64-3.6/code/pymqi/pymqe.o -L/usr/mqm/lib64 -L/QOpenSys/pkgs/lib -lmqic_r -o build/lib.os400-powerpc64-3.6/pymqi/pymqe.so
    collect2: fatal error: library libmqic_r not found_
I do not think this is going to work. Even though I have an environment that runs AIX commands, I do not have the AIX MQ package. I have the ISeries MQ package. I will try a bit more but I may not be worth the investment.

**Comment by atulk0** [comment]
@Honeybee427 PYMQI just needs MQ client which can be downloaded for free from IBM [https://www.ibm.com/support/pages/mqc91-ibm-mq-clients.](https://www.ibm.com/support/pages/mqc91-ibm-mq-clients) . However you need to have appropriate privileges on the machine. IBM ships XLC compilers for AIX. However, you can setup gcc on AIX as well, but it could be a little tricky.

Regarding the error, fatal error: library libmqic_r not found can be resolved on Linux/Unix system by exporting the environment variable "LD_LIBRARY_PATH". As I said I don't know much about AS/400 systems but there is some kind of bind that needs to be done. You can refer the IBM [documentation ](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q030460_.htm) for the same. It is something like:

CRTPGM PGM(MYLIB/IMQWRLD) MODULE(MYLIB/IMQWRLD) +
BNDSRVPGM(QMQM/IMQB23I4 QMQM/IMQS23I4)

CRTPGM PGM(MYLIB/IMQWRLD) MODULE(MYLIB/IMQWRLD) +
BNDSRVPGM(QMQM/IMQB23I4[_R] QMQM/IMQS23I4[_R])

**Comment by kadler** [comment]
The version of Python we ship on IBM i runs in PASE (an AIX emulation layer). MQ on i does not ship any shared libraries or development files for use within PASE, though. :(

It's _possible_ a shared library wrapper around the ILE service programs could be created using [_ILELOAD](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/pase__ileload.htm), [_ILESYM](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/pase__ilesym.htm), and [_ILECALL](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/pase__ilecall.htm), but that could be quite an undertaking.

**Comment by dsuch** [comment]
Please pardon my ignorance but I have never worked with System i directly, and as this topic re-surfaces once in a while, I would like to confirm one thing with you.

When talking about i, AS/400 and AIX, in what way can it be compared to other architectures?

Is it akin to IBM Z, in the sense of the hardware architecture where the native system is z/OS but z/Linux can also be used?

In this case, i would be Z, AS/400 would be z/OS and AIX would map to z/Linux? Is that a correct comparison?

Thanks.

**Comment by kadler** [comment]
In terms of hardware, it basically goes: AS/400 -> iSeries -> System i -> Power Systems
In terms of OS: OS/400 -> i5/OS -> IBM i

The original hardware was a custom 48-bit CISC  architecture but switched to 64-bit POWER in the 90s. Since the 2000s, these systems can run both AIX and Linux as well. The equivalent pSeries SKUs could not run IBM i due to firmware lockouts, even if they contained the exact same hardware though. Since 2008, the hardware has been completely unified as [Power Systems](https://en.wikipedia.org/wiki/IBM_Power_Systems), lifting that limitation. So yes, it's similar to Z nowadays, where you buy a piece of hardware and can run any OS on it. 

One wrinkle with IBM i in regards to hardware architecture is that the OS essentially runs inside a virtual machine targeting a hypothetical CPU architecture. "MI" machine instructions are converted to PPC instructions by lower levels of the OS when the program is loaded (and cached for later use). These layers are pretty tightly coupled, so there's no way to run different OSes on this architecture/VM. In addition, there's PASE, which is an AIX runtime environment that runs _inside_ IBM i. It provides AIX user-space libraries and commands and implements the AIX system call interface (basically WSL1, but AIX on top of IBM i instead of Linux on Windows).

**Comment by dsuch** [comment]
@kadler Thanks for the explanation, everything is much clearer now.

**Comment by Honeybee427** [comment]
I would like to thank everybody for their input into this issue. From what I can gather this undertaking is beyond my skill set. With that said I am goint to try to install and run the software on a windows 2012 server.

**Comment by albertvaka** [comment]
> The version of Python we ship on IBM i runs in PASE (an AIX emulation layer). MQ on i does not ship any shared libraries or development files for use within PASE, though. :(

@kadler do you mean that `cmqc.h` and `cmqxc.h` (required by `pymqi`'s C code) are not going to be available on IMB i? I'm also interested in using `pymqi` there :)

**Comment by kadler** [comment]
@albertvaka correct. The MQ libraries are only shipped as service programs and the header files that are shipped are tailored to the ILE environment in source physical file members.

If you'd like to see PASE support for IBM MQ, you should open an RFE. As a workaround for now, you could use [itoolkit](https://github.com/IBM/python-itoolkit) to call the ILE APIs through XMLSERVICE (though that might be tricky to get right all the structure layouts. Alternatively, you could write a simpler API which calls the MQ APIs and call _that_ from itoolkit.

**Comment by albertvaka** [comment]
I don't even know where to start from with itoolkit 😅 I ran the example on the site and the output is a long string that contains a table (formatted with spaces). Is the output of that example meant to be so little machine-readable? This is my first time touching anything IBM i, so I would appreciate any pointer on where to start RTFM... I might want to start querying something simpler than IBM MQ, though :)
