### ISSUE TITLE
PCFExecute.stringify_keys not mapping all values to appropriate keys

### ISSUE THREAD

**Issue by Skyler-Altol** [dsuch/pymqi#227]
After calling stringify_keys() on an unpacked message pulled from the SYSTEM.ADMIN.ACCOUNTING.QUEUE, I got this output:

(venv) C:\Users\Skyler\Desktop\MonitoringTest>python Pull.py
{'MQCA_Q_MGR_NAME': b'JavaTest                                        ', 2711: b'2020-09-12\x00\x00', 2712: b'17.27.55', 2707: b'2020-09-12\x00\x00', 2708: b'17.28.25', 'MQIA_COMMAND_LEVEL': 920, 7006: b'AMQCJavaTest    !u\\_\x01u\xb9"', 1079: 28, 3024: b'es\\IBM\\MQ\\bin64\\amqpcsea.exe', 1024: 5472, 1025: 1, 3025: b'MUSR_MQADMIN', 2703: b'2020-09-12\x00\x00', 2704: b'17.13.37', 733: [0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 751: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 709: [0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 757: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 735: [328, 0], 754: 0, 734: [1, 0], 755: 0, 748: [342980, 0], 722: [21, 0], 725: 0, 747: [1656, 0], 705: [0, 0], 708: 0, 745: [0, 0], 710: 0, 711: 0, 704: 0, 727: [0, 336, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0], 752: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 744: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 753: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 764: [0, 0, 0], 765: [0, 0, 0], 766: 0, 786: [0, 0], 787: [0, 0], 788: 0, 767: 0, 768: 0, 769: [0, 0, 0, 0], 770: 0, 771: [0, 0, 0, 0], 772: 0, 773: 0, 774: 0, 779: [0, 0], 780: 0, 781: [0, 0], 782: 0, 783: [0, 0]}

As you can see, some of the values were converted, but the vast majority were not. It appears the missing values are located in CMQCFC rather than in CMQC, and stringify_keys' comments state the following:

"""stringifyKeys(rawDict)
        Return a copy of rawDict with its keys converted to string
        mnemonics, as defined in CMQC. """

If we could add the additional constants from CMQCFC, that'd be very helpful.

**Comment by Skyler-Altol** [comment]
After making a quick alteration to the stringify keys method and telling it to use any constant from CMQCFC starting with MQ, the resultant output is now this:

`
{'MQCA_Q_MGR_NAME': b'JavaTest                                        ', 2711: b'2020-09-12\x00\x00', 2712: b'17.28.25', 2707: b'2020-09-12\x00\x00', 2708: b'17.28.55', 'MQSYSP_STATUS_PREMOUNT': 920, 7006: b'AMQCJavaTest    !u\\_\x01u\xb9"', 'MQIACF_SEQUENCE_NUMBER': 29, 3024: b'es\\IBM\\MQ\\bin64\\amqpcsea.exe', 'MQREGO_NON_PERSISTENT': 5472, 'MQIACF_THREAD_ID': 1, 3025: b'MUSR_MQADMIN', 2703: b'2020-09-12\x00\x00', 2704: b'17.13.37', 'MQIAMO_OPENS': [0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_OPENS_FAILED': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_CLOSES': [0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_CLOSES_FAILED': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_PUTS': [222, 0], 'MQIAMO_PUTS_FAILED': 0, 'MQIAMO_PUT1S': [1, 0], 'MQIAMO_PUT1S_FAILED': 0, 'MQIAMO64_PUT_BYTES': [231844, 0], 'MQIAMO_GETS': [16, 0], 'MQIAMO_GETS_FAILED': 0, 'MQIAMO64_GET_BYTES': [1264, 0], 'MQIAMO_BROWSES': [0, 0], 'MQIAMO_BROWSES_FAILED': 0, 'MQIAMO64_BROWSE_BYTES': [0, 0], 'MQIAMO_COMMITS': 0, 'MQIAMO_COMMITS_FAILED': 0, 'MQIAMO_BACKOUTS': 0, 'MQIAMO_INQS': [0, 224, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_INQS_FAILED': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_SETS': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_SETS_FAILED': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'MQIAMO_SUBS_DUR': [0, 0, 0], 'MQIAMO_SUBS_NDUR': [0, 0, 0], 'MQIAMO_SUBS_FAILED': 0, 'MQIAMO_UNSUBS_DUR': [0, 0], 'MQIAMO_UNSUBS_NDUR': [0, 0], 'MQIAMO_LAST_USED': 0, 'MQIAMO_SUBRQS': 0, 'MQIAMO_SUBRQS_FAILED': 0, 'MQIAMO_CBS': [0, 0, 0, 0], 'MQIAMO_CBS_FAILED': 0, 'MQIAMO_CTLS': [0, 0, 0, 0], 'MQIAMO_CTLS_FAILED': 0, 'MQIAMO_STATS': 0, 'MQIAMO_STATS_FAILED': 0, 'MQIAMO_TOPIC_PUTS': [0, 0], 'MQIAMO_TOPIC_PUTS_FAILED': 0, 'MQIAMO_TOPIC_PUT1S': [0, 0], 'MQIAMO_TOPIC_PUT1S_FAILED': 0, 'MQIAMO64_TOPIC_PUT_BYTES': [0, 0]}
`

Which is massively better. only a couple of values were missed there. 2711, 7006, 2704, 3025, 2703, among others probably. It also appears that some of these constants don't even appear in PyMQI anywhere. 2711 is not in any of our constant files.

**Comment by Skyler-Altol** [comment]
@dsuch why are so many constants missing from PyMQI? If I was to further cross check the shipped docs, I'm willing to bet I'd find a lot more constants, especially in relation to MQ's new monitoring topic $SYS/MQ.

**Comment by dsuch** [comment]
Hi @Skyler-Altol - the constants were initially generated from C header files (cmqc.h etc.) using a script that apparently is gone now. But it was just a simple script that would parse a header file and turn anything found into a Python constant in CMQC.py etc.

It was probably done once some 10 years ago and that sufficed for most purposes. If anyone needed anything more they just added the constants themselves and the conscientious among them sent a PR to PyMQI too.

In other words, keeping the header files and the generated Python files in sync is a manual job. As I do not work with MQ that much as I used to, short of the typical put/get applications, I do not really have time to make it any better. 

But let us see - we would probably need that script again and then it should somehow run after each new MQ release? That should suffice? Still, I do not see a way to automate it short of sending yourself a reminder once a calendar quarter or so.

In your case, we added a new **const.py** file some time ago to make all the constants available in one place  - I wonder if you can make stringify_keys pull everything from that place instead of individually from CMQC.py and friends?

**Comment by Skyler-Altol** [comment]
The generation of the constants could be taken from the constants defined in the classes in the jar file for JMS. Given that java code in its raw form is really just strings, we can manipulate the lines to remove the "public static final int" bit, and get back the name and the associated integer value.

I'll look into building something for you guys that will handle this since I'm rapidly learning what all these constants are, and where they can be found as part of a project to fully automate a suite of tests related to MQ security.

**Comment by Skyler-Altol** [comment]
Also @dsuch there's a problem with combining all the constants into one place. These constants are **not** unique across classes. As we saw above, the constant 31 appears in two different classes, and I doubt this is an isolated case. But... if we could check the formatting of a given message, we might be able to create a dictionary and map each message type to specific classes. Eg accounting messages would reference CMQCFC.

**Comment by dsuch** [comment]
Hm, @Skyler-Altol - the .jar files are likely covered by a proprietary license. If it were open-source, I would be fine with it, but it is not, so I would really not like to think about any licensing issues here. The .h files are openly available - could you try to look at it instead?

**Comment by Skyler-Altol** [comment]
I attempted to locate the .h files in a server installation of MQ and could not. If you can point me to where they're located, I'll gladly pull the constants out of them.

**Comment by dsuch** [comment]
Re: duplicates, this could actually mean using .h files would be preferable because, hopefully, given the simplicity of C, there should be no such situations with headers.

**Comment by Skyler-Altol** [comment]
An example of duplicates within C has already been shown above, specifically in relation to MQIA_COMMAND_LEVEL and MQSYSP_STATUS_PREMOUNT. One is in CQMC, the other is in CQMCFC.

**Comment by dsuch** [comment]
I think the headers will not be included unless you install the client MQ package too. That should give you files such as:

```
/opt/mqm/inc/cmqbc.h
/opt/mqm/inc/cmqc.h
/opt/mqm/inc/cmqcfc.h
/opt/mqm/inc/cmqec.h
/opt/mqm/inc/cmqpsc.h
/opt/mqm/inc/cmqstrc.h
/opt/mqm/inc/cmqxc.h
/opt/mqm/inc/cmqzc.h
```

**Comment by Skyler-Altol** [comment]
I have a container spun up with the MQ client installed, will check it.

**Comment by dsuch** [comment]
Alright, but MQIA_COMMAND_LEVEL and MQSYSP_STATUS_PREMOUNT are different keys (names) so this should not be an issue unless there is a piece of code assuming that all constants are different values? Is **stringify_keys** assuming it?

(My apologies if I did not understand it earlier).

**Comment by Skyler-Altol** [comment]
No worries, basically the problem is, if you have a message like this: (I've cut out a lot of values to make it easier to read)

{2015: b'JavaTest                                        ', 2711: b'2020-09-12\x00\x00', 2712: b'17.28.55', 2707: b'2020-09-12\x00\x00', 2708: b'17.29.25', 31: 920, 7006: b'AMQCJavaTest    !u\\_\x01u\xb9"', 1079: 30, 3024: b'es\\IBM\\MQ\\bin64\\amqpcsea.exe', 1024: 5472, 1025: 1, 3025: b'MUSR_MQADMIN', 2703: b'2020-09-12\x00\x00', 2704: b'17.13.37'}

And all the constants are imported into the main namespace, how do we go backwards from 31 to the key name? There are multiple potentials here, and that's the issue. Going forwards from key -> value is easy, going backwards from value -> key as stringify_keys() is trying to do, is much harder when everything is imported simultaneously.

**Comment by Skyler-Altol** [comment]
I've obtained the header files. I'll look at writing a python script that converts these constants to python code.

**Comment by Skyler-Altol** [comment]
Oh for god sake IBM. Even within CMQCFC, there's *three* keys with the value 31. So now we're not just dealing with other classes, we're dealing with just *this* class.

#define MQCMD_START_CHANNEL_LISTENER   31
#define MQRQ_FAILOVER_NOT_PERMITTED    31
#define MQSYSP_STATUS_PREMOUNT         31

**Comment by JoshMcMQ** [comment]
amqsevt is a C sample from IBM that parses those messages, check to see how they do it.

**Comment by Skyler-Altol** [comment]
Truth be told lads, I've swapped to using Java and am leveraging JMS instead. Which lets me do this:

```
MQCA_Q_MGR_NAME
JavaTest                                        
MQCAMO_START_DATE
2020-09-12
MQCAMO_START_TIME
17.34.33
MQCAMO_END_DATE
2020-09-12
MQCAMO_END_TIME
17.34.33
MQIA_COMMAND_LEVEL
920
MQBACF_CONNECTION_ID
414d51434a617661546573742020202021755c5f01c2b922
MQIACF_SEQUENCE_NUMBER
0
MQCACF_APPL_NAME
s\Python\Python37\python.exe
MQIAMO_MONITOR_KB/MQIACF_PROCESS_ID
6232
MQIACF_THREAD_ID
109
MQCACF_USER_IDENTIFIER
admin       
MQCAMO_CONN_DATE
2020-09-12
MQCAMO_CONN_TIME
17.34.33
MQCACH_CONNECTION_NAME
192.168.72.1                                                                                                                                                                                                                                                            
MQCACH_CHANNEL_NAME
PYTHON.BYPASS       
MQCACH_REMOTE_PRODUCT
MQCC
MQCACH_REMOTE_VERSION
09010200
MQCAMO_DISC_DATE
2020-09-12
MQCAMO_DISC_TIME
17.34.33
MQIAMO_DISC_TYPE
0
MQIAMO_OPENS
0 1 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_OPENS_FAILED
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_CLOSES
0 1 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_CLOSES_FAILED
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_PUTS
0 0
MQIAMO_PUTS_FAILED
0
MQIAMO_PUT1S
0 0
MQIAMO_PUT1S_FAILED
0
MQIAMO64_PUT_BYTES
0 0 
MQIAMO_GETS
1 0
MQIAMO_GETS_FAILED
0
MQIAMO64_GET_BYTES
2176 0 
MQIAMO_BROWSES
0 0
MQIAMO_BROWSES_FAILED
0
MQIAMO64_BROWSE_BYTES
0 0 
MQIAMO_COMMITS
0
MQIAMO_COMMITS_FAILED
0
MQIAMO_BACKOUTS
0
MQIAMO_INQS
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_INQS_FAILED
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_SETS
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_SETS_FAILED
0 0 0 0 0 0 0 0 0 0 0 0 0
MQIAMO_SUBS_DUR
0 0 0
MQIAMO_SUBS_NDUR
0 0 0
MQIAMO_SUBS_FAILED
0
MQIAMO_UNSUBS_DUR
0 0
MQIAMO_UNSUBS_NDUR
0 0
MQIAMO_UNSUBS_FAILED
0
MQIAMO_SUBRQS
0
MQIAMO_SUBRQS_FAILED
0
MQIAMO_CBS
0 0 0 0
MQIAMO_CBS_FAILED
0
MQIAMO_CTLS
0 0 0 0
MQIAMO_CTLS_FAILED
0
MQIAMO_STATS
0
MQIAMO_STATS_FAILED
0
MQIAMO_TOPIC_PUTS
0 0
MQIAMO_TOPIC_PUTS_FAILED
0
MQIAMO_TOPIC_PUT1S
0 0
MQIAMO_TOPIC_PUT1S_FAILED
0
MQIAMO64_TOPIC_PUT_BYTES
0 0 
```

**Comment by dsuch** [comment]
Good for you @Skyler-Altol although I cannot see how Java would work around the same issue given that it needs to support the same constants as C and Python do.

At any rate, I will close the ticket unless someone wants to reopen it one day with a suggestion on how to deal with values mapping to multiple keys. Thanks.

**Comment by Skyler-Altol** [comment]
@dsuch I may look into how Java is somehow pulling this off, because basically all I'm doing is converting the downloaded message to MQMessage, and from there the MQMessage is passed to the constructor of PCFMessage. For some reason, PCFMessage seems to be able to identify what all the constants are. I'll look more closely into that at a later date when I'm feeling curious.
