### ISSUE TITLE
version needs to be updated 

### ISSUE THREAD

**Issue by agkcn** [dsuch/pymqi#229]
line 143 __init__.py

it is set to __version__ = '1.11.0' for 1.12.0 release.

**Comment by dsuch** [comment]
Hello @agkcn,

I cannot find it anywhere, can you please clarify what you are checking exactly?

**Comment by agkcn** [comment]
https://github.com/dsuch/pymqi/blob/master/code/pymqi/__init__.py
__version__ = '1.11.0'

**Comment by dsuch** [comment]
Ah, I see. The package uploaded to PyPI was correct but I forgot to commit and push the update to GitHub, this is done now.

**Comment by SeyfSV** [comment]
Close?

**Comment by dsuch** [comment]
Yes, I am closing it.
