### ISSUE TITLE
Segmentation fault on AWS Lambda

### ISSUE THREAD

**Issue by ianrapha** [dsuch/pymqi#233]
Hello everybody.

This message is not an issue at all but it is more a way to discuss this the scenario. If the admins find that it is not useful please close this issue.

I am trying to use this library in a Lambda function with layer (Python 3.7) but I am receiving "Error: Runtime exited segmentation fault (core dumped)". The error occurs on connect() call.

I followed the steps to install PyMQI library locally (EC2 using Amazon Linux), create the Lambda function and layer.

1. Downloaded and unzipped the redist client into /opt/mqm/
2. Configured the EC2 LD_LIBRARY_PATH environment variable pointing to lib64 folder
3. sudo pip install pymqi
4. Added compiled library plus lib64 folder inside a zip
5. Created the lambda layer using this zip file
6. Created Lambda and environment variable LD_LIBRARY_PATH pointing to lib64 path inside container /opt

I tested using the code below
```
import pymqi

queue_manager = '***'
channel = '***'
host = '***'
port = '***'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info)
qmgr.disconnect()
```

Is there anybody who tried to do the same and achieved success?

Thanks people!

**Comment by dsuch** [comment]
Hello,

could you please reformat the code using backticks? Otherwise, it does not display too well in browsers.

As to the issue:

* Can you find out if it segfaults on the "import pymqi" line or later, when calling pymqi.connect
* Can you upload the core file somewhere for offline analysis

?

Thanks.

**Comment by dsuch** [comment]
One more thing, what do you mean here?

```
Configured the LD environment variable pointing to lib64 folder
```

What is the LD environment variable?

**Comment by JoshMcMQ** [comment]
`LD_LIBRARY_PATH` is a way to let the busy find the shared library files on Linux (maybe others) that are not in a standard location like `/usr/lib64`.  If a there is a full MQ client install that is also set as primary there will be symlinks from

**Comment by ianrapha** [comment]
Thanks @dsuch 

I added/fixed in the main post the LD environment variable information, code formatting and error location.
What is this core file? The PyMQI compiled library?

**Comment by dsuch** [comment]
Here is the description of what a core file is - https://en.wikipedia.org/wiki/Core_file - but I think it is all working now, I can see that @JoshMcMQ closed the ticket?

**Comment by JoshMcMQ** [comment]
Sorry but not sure how I closed it, must have been a stay finger press.

**Comment by ianrapha** [comment]
I am trying to obtain the core file, upload it and continue the discussion here.

**Comment by SeyfSV** [comment]
@ianrapha, do you have anything to add to the issue?

**Comment by ianrapha** [comment]
@SeyfSV No, I don't. I am closing this issue.
Thanks everybody for the help!
