### ISSUE TITLE
MQ Topic - Modification to example

### ISSUE THREAD

**Issue by agamjajoo** [dsuch/pymqi#243]
While trying the below example from https://dsuch.github.io/pymqi/examples.html to test connectivity for MQ Topic Connectivity -

```
import pymqi

queue_manager = 'QM1'
channel = 'DEV.APP.SVRCONN'
host = '127.0.0.1'
port = '1414'
topic_string = '/currency/rate/EUR/USD'
msg = '1.3961'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.QueueManager(None)
qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)

topic = pymqi.Topic(qmgr, topic_string=topic_string)
topic.open(open_opts=pymqi.CMQC.MQOO_OUTPUT)
topic.pub(msg)
topic.close()

qmgr.disconnect()
```
Below asks for 7 parameters - it looks for user and password.
```qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info)```

Do we think it would help to modify it to something like below?
```qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info, user = ' ', password = ' ')```

**Comment by dsuch** [comment]
Hi @agamjajoo,

it would be probably better to change the definition of connect_tcp_client and make both user and password paramaters default to None - can you send a pull request, please?

Thanks.

**Comment by agamjajoo** [comment]
@dsuch , you mean changing as below?
```def connect_tcp_client(self, name, cd, channel, conn_name, user, password):```
to 
```def connect_tcp_client(self, name, cd, channel, conn_name, user='None', password='None'):```
in /code/pymqi/__init__.py
