### ISSUE TITLE
No module named 'pymqe' on AWS lambda function

### ISSUE THREAD

**Issue by MrEzio** [dsuch/pymqi#245]
Hi, I wrote a code with the pymqi library on my local pc (ubuntu) on vs code in Python, and the message was sent successfully into the queue. I wanted then, to try the same thing on a lambda function with the same code. I made sure the handler was correct. The only problem is when I try to import the library by .zip on a layer. The zip contains the following inside the folder python:
opt 
pymqi      
pymqi-1.12.0.dist-info   

(I made pip3 install pymqi -t .  on the folder python and copy pasted what was in opt/mqm into it too). It says when I test, "No module named 'pymqe'. I had the same issue on my local python code in vs code and I fixed it by running the command :
(sudo /opt/mqm/bin/setmqinst -i -p /opt/mqm/)

Inside pymqi, the pymqe.py is present with pymqe.cpython-38-x86_64-linux-gnu.so
I'm really lost as to why it can't find the module, any help is greatly appreciated. I'm fairly new to lambda aws and pymqi so I don't really know what is missing.

**Comment by dsuch** [comment]
Hello @MrEzio,

My answer to you is similar to the one in #246 in that I have never used PyMQI under AWS Lambda and I will not be able to do it without a commercial support contract.

If you are interested, please contact pymqi@zato.io at any time.

Thanks.

**Comment by bronzzze** [comment]
@MrEzio If you find something please post resulution in this issue :)

**Comment by MrEzio** [comment]
Ok I think I found where the error comes from. I think it's when I set  the  enviroment variable LD_LIBRARY_PATH = /opt/mqm/lib64. To make sure, I wrote the code below to see what is inside the lib64 folder:
print(os.listdir(os.environ['LD_LIBRARY_PATH']))

but it gives me this error :
{
  "errorMessage": "[Errno 2] No such file or directory: '/opt/mqm/lib64'",
  "errorType": "FileNotFoundError",
  "stackTrace": [
    "  File \"/var/task/pymqi_lambda.py\", line 4, in lambda_handler\n    print(os.listdir(os.environ['LD_LIBRARY_PATH']))\n"
  ]
}

So the problem is most probably around how I'm setting the environement variable LD_LIBRARY_PATH. Still working on it.

**Comment by bronzzze** [comment]
@MrEzio your problem is because your path is now opt/python/opt/mqm/lib64. You have to zip 2 folders one is mqm other one is python. inside mqm is ibm installation in pyrhon folder are pymqi and pymqi-1.2.... As far as i know :).

**Comment by bronzzze** [comment]
You can check this with os.system("ls")

**Comment by MrEzio** [comment]
@bronzzze YUP! That did it! the error "no module pymqe found" is gone. For those wondering what was the problem, it was indeed the path I set for LD_LIBRARY_PATH in envrionement variables. My .zip had a python folder, that contained opt, pymqi and pymqi-1.12.0.dist-info.

Lambda function :
By setting /opt as the path, it showed me my python folder, then /opt/python showed me those 3 folders. All I had to do was to set the path : /opt/python/opt/mqm/lib64 and the error was gone.

Local pc:
Inside my opt, was mqm folder. I copy pasted using my terminal. I just put everything that was in /opt/mqm inside my /python/opt/mqm folder that I created.

**Comment by bronzzze** [comment]
Its weird because I have set all same. And its not working for me  I have no idea what could be wrong.

**Comment by MrEzio** [comment]
Can you tell me what is inside your pymqi folder?

**Comment by MrEzio** [comment]
@bronzzze You're right. It only works for me in python3.8. When I tried the same things on python3.6, it doesn't find the module.

**Comment by bronzzze** [comment]
@MrEzio I am using 3.8 python. BTW this is my pymqi direcotry 
![image](https://user-images.githubusercontent.com/10884035/105185296-a2a1c280-5b30-11eb-8dde-900acf728f81.png)

**Comment by MrEzio** [comment]
Yup there are a few things that are missing in your pymqi folder (the pymqe.py) and mqm, maybe because you're doing it on windows. Give me your personnal email, I'll send you the .zip that worked for me.

**Comment by bronzzze** [comment]
I installed it on linux and then scp it to windows. Can you send whole zip to jancek21@gmail.com :). I will delete this command after you get my mail so it wont be publish forever :)

**Comment by bronzzze** [comment]
It's weird why it didn't install this file pymqe.py. I did it with pip3 install pymqi

**Comment by MrEzio** [comment]
Yeah it's the same thing that happened with me when I installed it for python3.6. The pymqe.py wasn't there (sending you the zip in 1 minute)

**Comment by bronzzze** [comment]
Okay. I am 99% sure that I was using 3.8 (I was using ec2 amazon linux and I deleted it, so I will never know what python it is :)) Thank you I hope it will work

**Comment by MrEzio** [comment]
Yeah I hope it works for you! Just don't forget to set the version of your lambda function to python 3.8 and modify the path that I told you on the mail.

**Comment by bronzzze** [comment]
Today I won't be able to try it. I will report to you tommorow. Thank you :)

**Comment by bronzzze** [comment]
@MrEzio It's working :D. Thank you.

**Comment by MrEzio** [comment]
Glad to hear it! Don't forget to delete your email ;)

**Comment by bronzzze** [comment]
oh thank you :)

**Comment by MrEzio** [comment]
Alright, I'll just stay with 3.8. For anyone getting the error : MQRC_CONNEXION_BROKEN, it's because you didn't set the environment variable HOME to /tmp. So you have in total 2 important variables to set in the lambda :
LD_LIBRARY_PATH  to your lib64 folder inside mqm
HOME to /tmp.

Closing this, hope this will help anyone having the same problems!

**Comment by ravirajuv** [comment]
@MrEzio Can you share me the folder structure which you used in your lambda. I am also struggling with it.

**Comment by LeonVan01** [comment]
@MrEzio - I had the same folder structures like you had but still get the error "No module named 'pymqe' ".
pymqi.zip
python
   opt 
   pymqi
   pymqi-1.12.0.dist-info
   
Within opt folder , I have mqm and all the sub folders. Under pymqi I have 
![image](https://user-images.githubusercontent.com/104965507/166868808-bfa80f66-4ea5-4991-a4e5-e99d22c7c030.png)

The issue here is if the __init__.py moved outside the pymqi folder then I have the error "module 'pymqi' has no attribute 'connect', so all the modules are not registered. But leave it as it is , the error is there.
