### ISSUE TITLE
PyMQI in AWS lambda function

### ISSUE THREAD

**Issue by bronzzze** [dsuch/pymqi#246]
Hello, I have one problem with setting pymqi on AWS lambda functions. I get error:
 ```
[ERROR] ModuleNotFoundError: No module named 'pymqe'
Traceback (most recent call last):
 File "/var/task/lambda_function.py", line 9, in lambda_handler
```
Steps I did:
1. installed IBM MQ client on Ubuntu linux server and there I installed pymqi with pip install pymqi
2. I zipped MQ installation path (/opt/mqm) and pymqi in same zip file
3. uploaded this zip on AWS lambda layer
4. then I created new lambda function and add layer and wrote in function code "import pymqi"
5. In enviroment variables I added LD_LIBRARY_PATH = /opt/mqm/lib64

**Comment by dsuch** [comment]
Hello @bronzzze,

I have never used PyMQI under AWS Lambda and, as much as I would like to, I will not be able to do it without a commercial support contract - if you are interested, please contact pymqi@zato.io at any time.

Thanks.

**Comment by MrEzio** [comment]
Same problem I have. I contacted pymqi@zato.io, if I somehow solve this, I'll post back what I did to make it work. If anyone reading this already made it work, please help us :)

**Comment by bronzzze** [comment]
Oh sorry I didn't see you already opened this issue. Now there are 2 opened. I can close this one @dsuch ?

**Comment by dsuch** [comment]
Yes, please feel free to close it if it is no longer needed.

**Comment by anouar-zh** [comment]
I have the same issue but then in Azure functions. Any body who got this working in Azure?

**Comment by dsuch** [comment]
Hello everyone,

myself, I am not going to work on it unless it is part of sponsored work.

If you are interested, please feel free to contact me on dsuch@zato.io.

Regards.
