### ISSUE TITLE
MQRC_SSL_INITIALIZATION_ERROR & MQRC_KEY_REPOSITORY_ERROR (Key with password)

### ISSUE THREAD

**Issue by MrEzio** [dsuch/pymqi#247]
Hi! I'm trying to do an SSL type of connection, using pymqi. The only problem I have is that my key has a password (which I know), but I don't know how to make it known to the program. Here is my code, I'm only trying to establish a connection.
```
import pymqi
import logging
    
logging.basicConfig(level=logging.INFO)

queue_manager = 'QM1'
channel = b'...'
host = '...'
port = '...'
queue_name = '....'
conn_info = '%s(%s)' % (host, port)
conn_info = conn_info.encode('utf_8')
ssl_cipher_spec  = b'....'
key_repo_location = b'/home/...../Desktop/keys/client_test_01'

cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
    
sco = pymqi.SCO()
sco.KeyRepository = key_repo_location

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, cd, sco)

qmgr.disconnect()
```

**Comment by JoshMcMQ** [comment]
If you have a `kdb` file you may need to create a `sth` (stash) file to go with it using `runmqakm`.

**Comment by MrEzio** [comment]
My key is a `jks` file. Does it change anything?

**Comment by JoshMcMQ** [comment]
You can use a jks with pymqi, you could convert it.   I answered a similar question on stackoverflow recently.

**Comment by MrEzio** [comment]
If possible I would like to use the jks key, but with a password I don't know how to make the program read it. Saw the `runmqakm` on multiple forums, but it only works with kdb keys. Is converting it to a kdb key (if possible?) the only choice?

**Comment by JoshMcMQ** [comment]
Yes it is the only choice.   Do you ask the question on SO?

**Comment by JoshMcMQ** [comment]
That question was about node js but the answer is the same. 

https://stackoverflow.com/questions/65814977/how-to-use-keystore-to-connect-to-ssl-enabled-ibm-mq-using-nodejs/65817518#65817518

**Comment by MrEzio** [comment]
So I did what was said in the SO forum that you sent, but when I did the first line and I gave the password when it asked for the Source database password, I got this error :

`CTGSK3026W The key file "client_test_01.jks" does not exist or cannot be read.
CTGSK2017W An invalid database file type was encountered.
-Command usage-
-db                   Required
-pw | -stashed        Optional
-old_format | -type   Optional <cms | kdb | pkcs12 | p12>
-new_db | -target     Optional
-new_pw               Optional
-new_format           Optional <cms | kdb | pkcs12 | p12>
-preserve | -populate Optional
-expire               Optional
-strong               Optional
-stash                Optional
-v1stash              Optional
`

**Comment by JoshMcMQ** [comment]
What version of IBM MQ do you have installed and can you provide the exact command line?

**Comment by MrEzio** [comment]
I have the version 9.0.0.4 and this was my command line :
`runmqakm -keydb -convert -db client_test_01.jks -new_format kdb`

**Comment by JoshMcMQ** [comment]
Please review the answer again.  I had a critical typo in my original answer.   The command is `runmqckm` not `runmqakm`.

**Comment by MrEzio** [comment]
Yup, it created the files perfectly, but when I run I have a `MQRC_SSL_INITIALIZATION_ERROR`, saying that it didn't find a certificate for the queue manager. (Btw thank you for your help so far, I really appreciate it).

**Comment by JoshMcMQ** [comment]
The label needs to match `ibmwebspheremq<user id in lower case>`.  If it does not match you can change the label or you can specify a cert label to use with various methods.

1. Env variable
2. mqclient.ini
3. Programmatically
4. Maybe other ways.

**Comment by MrEzio** [comment]
Yeah, my cert label is ibmwebspheremqqm1. Weird why it doesn't work, I've seen that putting `Version=pymqi.CMQXC.MQCD_VERSION_11` next to pymqi.CD makes it work, but no luck in my case.

**Comment by JoshMcMQ** [comment]
Which pymqi version are you using?

**Comment by MrEzio** [comment]
Pymqi 1.12.0

**Comment by JoshMcMQ** [comment]
Instead try setting this ENV variable `MQCERTLABL=ibmwebspheremq<user>`

**Comment by MrEzio** [comment]
Error still persists :/

**Comment by JoshMcMQ** [comment]
What did the `AMQERR01.LOG` show?

**Comment by MrEzio** [comment]
`AMQ9642: No SSL or TLS certificate for channel 'CHANNEL.SVRCONN'.

EXPLANATION:
The channel 'CHANNEL.SVRCONN' did not supply a certificate to use during SSL
or TLS handshaking, but a certificate is required by the remote queue manager. 

The remote host is 'ec2-.-...-..-...(host)(port)'. 

The channel did not start.
ACTION:
Ensure that the key repository of the local queue manager or MQ client contains
a certificate which is associated with the queue manager or client. If you have
configured a certificate label, check that the certificate exists. 

Alternatively, if appropriate, change the remote channel definition so that its
SSLCAUTH attribute is set to OPTIONAL and it has no SSLPEER value set.`

**Comment by JoshMcMQ** [comment]
How did you set the variable? Have you tried the sample `amqssslc` to test a connection?

**Comment by MrEzio** [comment]
I tried setting it by terminal : `export MQCERTLABL=ibmwebspheremqqm1`. And no haven't tried the amqssslc, I honestly don't know how to use it to test the connection. (Sorry went to sleep by that time)

**Comment by MrEzio** [comment]
I see in this SO question : https://stackoverflow.com/questions/62416345/mqrc-ssl-initialization-error-with-pymqi-however-it-connects-successfully-with 
That he resolved his problem by indicating the `mqclient.ini` variable within the script. What does he mean by that?

**Comment by JoshMcMQ** [comment]
The last post does not seem related to your issue. 

`amqssslc -help` will provide usage.   Just fill in the details.

**Comment by MrEzio** [comment]
Hmm it seems like `amqssslc` isn't present in my `bin` folder. Should I install the redist client package?

**Comment by MrEzio** [comment]
I think the problem is in the certificate label. On the MQ manager, it's ibmwebspheremqqm1, but on my side (client side) I think it's different. Since it's ibmwebspheremq<user>, then it's definitely not the same, since my user is not qm1. How can I change my certificate label with ENV variable or Programmatically?

**Comment by JoshMcMQ** [comment]
`amqssslc` would be found in the `/opt/mqm/samp/bin`.

The point of the cert label is you need to set it to the value in your client key store, but the value of the queue manager.   The default it looks for is `ibmwebspheremq<user id in lower case>`.   As mentioned earlier you can change the label of the cert in the key store or tell mq the actual cert label using one of these methods:

1. Programmatically
2. Env variable
3. mqclient.ini

If you don't know what your label is you can use this command to list all the certs:

```
runmqakm -cert -list -db key.kdb -stashed
```

**Comment by MrEzio** [comment]
Yup, I have 2 of them.
```
Certificates found
* default, - personal, ! trusted, # secret key
!	qm1_signer
-	client
```

**Comment by JoshMcMQ** [comment]
So the cert label you want to point at is `client`.

**Comment by MrEzio** [comment]
YES! by adding `sco.CertificateLabel = 'client'.encode('utf_8')` it finally worked!!! Thank you so much @JoshMcMQ !!!

**Comment by JoshMcMQ** [comment]
Glad it is working. Feel free to vote my SO answer up :)

Also if you want to rename the cert in the kdb you can use this command:

```
runmqakm -cert -rename -db key.kdb -stashed -label client -new_label ibmwebspheremq<user id in lower case>
```

**Comment by MrEzio** [comment]
Thanks for the info! Don't have enough reputation to see the upvote, but I did give it. Again thank you so much!

**Comment by JoshMcMQ** [comment]
Thanks for trying.
