### ISSUE TITLE
MQCMD_INQUIRE_CONNECTION exception in 1.12.0 

### ISSUE THREAD

**Issue by colross** [dsuch/pymqi#250]
I am trying to do an MQCMD_INQUIRE_CONNECTION with MQBACF_GENERIC_CONNECTION_ID.
In the MQCMD_INQUIRE_CONNECTION I am setting {2007:pymqi.ByteString(b'')}
In 1.10.1 this works.
In 1.12.1, I crash in the following place:

```
Traceback (most recent call last):
  File "/Users/colin/.p2/pool/plugins/org.python.pydev.core_8.1.0.202012051215/pysrc/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pymqi/__init__.py", line 2696, in __call__
    String=value.value.encode(bytes_encoding))
AttributeError: 'bytes' object has no attribute 'encode'
```

It is not clear to me what the value.value.encode(bytes_encoding)) is attempting to encode, as value.value in this case is b'' which is already byte encoded. I tried changing so String=value.value (which is b'') but the MQCMD_INQUIRE_CONNECTION did not return any info, and if I attempt to pass a null string in {2007:''}, it does not work.
What am I doing wrong here?

**Comment by SeyfSV** [comment]
Hi @colross,

ByteString docstring says: 

> A simple wrapper around string values, suitable for passing into PyMQI calls wherever IBM's docs state a 'byte string' object should be passed in.

As result code waits for String in value parameter, not bytes (IMHO). @dsuch, what type should be used? 

Please, look for example in test:

```
    def test_mqcfbs_old(self):
        """Test byte string MQCFBS with old style."""
        attrs = {
            pymqi.CMQCFC.MQBACF_GENERIC_CONNECTION_ID: pymqi.ByteString(''),
            pymqi.CMQCFC.MQIACF_CONN_INFO_TYPE: pymqi.CMQCFC.MQIACF_CONN_INFO_CONN,
            pymqi.CMQCFC.MQIACF_CONNECTION_ATTRS: [pymqi.CMQCFC.MQIACF_ALL]
        }
        fltr = pymqi.Filter(pymqi.CMQC.MQIA_APPL_TYPE).equal(pymqi.CMQC.MQAT_USER)

        results = self.pcf.MQCMD_INQUIRE_CONNECTION(attrs) #, [fltr])

        self.assertGreater(len(results), 0)
```


PS
MQBACF_GENERIC_CONNECTION_ID is 7007

**Comment by dsuch** [comment]
Hi @SeyfSV & @colross,

if I remember correctly, I authored that piece of code well before Python 3 came into existence so if it does not play well with what is in use today, bytes vs. str, definitely please feel free to change it accordingly.

Regards.

**Comment by shivanekanti** [comment]
Hi @dsuch  could you take a look at the pull request https://github.com/dsuch/pymqi/pull/252 
I think it is the same issue I am trying to fix. But not sure if I did the correct way. 
thanks for help

**Comment by colross** [comment]
Hi all - I was wondering if are any plans to create a release vehicle for this issue?

**Comment by dsuch** [comment]
Hello @colross - I am currently busy with other work and I do not have time for preparing a new PyMQI release.

If you need this functionality in a new release then you can sponsor the work needed, please feel free to contact me directly to discuss it (pymqi at zato.io). Regards.
