### ISSUE TITLE
How get all names Message queue method MQCMD_INQUIRE_Q

### ISSUE THREAD

**Issue by Sheva1230** [dsuch/pymqi#251]
How do I get all the queues from the queue manager at once?
Here is my code it doesn't work
```
import logging
import pymqi

queue_manager = 'QM1'
channel = 'DEV.APP.SVRCONN'
host = '127.0.0.1'
port = '1414'
conn_info = '%s(%s)' % (host, port)
logging.basicConfig(level=logging.INFO)

qmgr = pymqi.connect(queue_manager, channel, conn_info)
pcf = pymqi.PCFExecute(qmgr)

pref ="*"
attrs = {
      pymqi.CMQC.MQCA_Q_NAME : pref
    }

result = pcf.MQCMD_INQUIRE_Q(attrs)
for queue_info in result:
        queue_name = queue_info[pymqi.CMQC.MQCA_Q_NAME]
        logging.info('Found queue `%s`' % queue_name)
```
And output error 
```
Traceback (most recent call last):
  File "D:/project/Work-Project/queue list.py", line 17, in <module>
    result = pcf.MQCMD_INQUIRE_Q({pymqi.CMQC.MQCA_Q_NAME: str("*")})
  File "C:\Users\ShevcovAA\AppData\Local\Programs\Python\Python37\lib\site-packages\pymqi\__init__.py", line 2769, in __call__
    message = self.__pcf.reply_queue.get(None, get_md, get_opts)
  File "C:\Users\ShevcovAA\AppData\Local\Programs\Python\Python37\lib\site-packages\pymqi\__init__.py", line 2021, in get
    raise MQMIError(rv[-2], rv[-1], message=rv[0], original_length=rv[-3])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2033: FAILED: MQRC_NO_MSG_AVAILABLE
```

**Comment by colross** [comment]
Use * as your MQCA_Q_NAME
pcf.MQCMD_INQUIRE_Q({MQCA_Q_NAME:'*'})

**Comment by Sheva1230** [comment]
Hi @SeyfSV , help with solving the problem. I saw that they had already solved the problem with this method and made improvements. Why does the method `MQCMD_INQUIRE_Q` not accept '*'

**Comment by Sheva1230** [comment]
@SeyfSV, Thank you. I will close the question

**Comment by Sheva1230** [comment]
@SeyfSV 
Version 1.11.0 works fine with this function. But where is the big load, according to the above code, it raises an empty array

**Comment by SeyfSV** [comment]
Try to increase `response_wait_interval`. 10000 is just 10 second.

**Comment by Sheva1230** [comment]
Interval works yes, but there is a problem with one of the queue managers.

Error:
> MQI Error. Comp: 2, Reason 2101: FAILED: MQRC_OBJECT_DAMAGED

**Comment by SeyfSV** [comment]
I will close this question because it is not pymqi specific. Suggest further conversation on [StackOverflow](https://stackoverflow.com/questions/66742537/how-get-a-list-of-mq-queues-pymqi/67251567#67251567)
