### ISSUE TITLE
need help for support for CFSL and unhexlified Bytestrings in pcf command requests

### ISSUE THREAD

**Issue by shivanekanti** [dsuch/pymqi#254]
The PCF commands  MQCMD_STOP_CONNECTION and MQCMD_INQUIRE_CONNECTION are expecting unhexlified ByteString for Connection ID, current pymqi gives exception when we pass such data. 

The PCF command MQCMD_SET_AUTH_REC expects the UserIDs as CFSL list current pymqi code is missing this. 

I have made code changes for both the above fixes, and created pull request 252 for the same. 
It looks like some tests have failed, I need some help on how to resolve it and also, if someone could review the changes to check if there is a better/alternative fixes for the same. 

thanks for help

**Comment by SeyfSV** [comment]
Hi @shivanekanti, 

What pymqi version do you use? If you use 1.11.1+ you can use new PCF format. Yes, it still do not documented, but it you can use tests as reference or ask here for help.

**Comment by shivanekanti** [comment]
Hi 

We are using 1.12.0. 
You mean there is a newer format of PCF?
I mean, If you are recommending to use PCF Format instead of MQAI Format. We are already using PCF format. 
The PCF code works fine for all 120+ MQ commands. Only the above two commands need the fix. 

Thanks for help

**Comment by shivanekanti** [comment]
Also, I am able to get the code working on my host using the fixes in the pull request. https://github.com/dsuch/pymqi/pull/252. 
Now I am trying to reflect the fixes here. But some of the tests are failing. I am not sure what to about it.

**Comment by shivanekanti** [comment]
Hi @SeyfSV 
Sorry  for the delay. 
Below is the sample code to that show how we are running display connections command. 
Without the fix, we were getting `line 2701, in __call__
    String=value.value.encode(bytes_encoding))
AttributeError: 'bytes' object has no attribute 'encode'`


`import os
import pprint
from collections import OrderedDict
from pymqi import ByteString
import pymqi  # pylint: disable=syntax-error
from mqadmin.exceptions.exceptions import MqPCFError

PORT = 2428
CHANNEL = 'TEST.SVRCONN'
CIPHERSPEC = 'ECDHE_RSA_AES_128_GCM_SHA256'
qmgr_name = 'TESTQM'
conname = 'TESTQM.testhost.net'


def create_sco():
    sco = pymqi.SCO()
    sco.KeyRepository = pymqi.ensure_bytes(os.environ.get('MQ_CERT_DIR'))
    return sco


def create_cd(conname, port=PORT):
    cd = pymqi.CD()
    cd.ChannelName = pymqi.ensure_bytes(CHANNEL)
    cd.ConnectionName = pymqi.ensure_bytes('%s(%s)' % (conname, port or PORT))
    cd.ChannelType = pymqi.ensure_bytes(pymqi.CMQC.MQCHT_CLNTCONN)
    cd.TransportType = pymqi.ensure_bytes(pymqi.CMQC.MQXPT_TCP)
    cd.SSLCipherSpec = pymqi.ensure_bytes(CIPHERSPEC)
    return cd


def create_hcon():
    hcon = pymqi.QueueManager(None)
    try:
        sco = create_sco()
        cd = create_cd(conname)
        hcon.connect_with_options(qmgr_name, cd=cd, sco=sco, opts=pymqi.CMQC.MQCNO_HANDLE_SHARE_BLOCK)
    except pymqi.MQMIError as e:
        if not (e.comp == pymqi.CMQC.MQCC_WARNING and e.reason == pymqi.CMQC.MQRC_ALREADY_CONNECTED):
            raise MqPCFError(e.errorAsString(), e.reason, conname) from e
    return hcon


connection_handle = create_hcon()
pcf_execute = pymqi.PCFExecute(connection_handle,
                               dynamic_queue_name=b'MQADMIN.*',
                               # The model queue will create temp dynamic queue with read ahead enabled
                               model_queue_name=b'MQADMIN.MODEL.QUEUE',
                               # 3 minutes for GMO wait for response messages on dynamic queue
                               # also 3 minutes is the expiry value on the response messages
                               response_wait_interval=3 * 60 * 1000,
                               # we shall always do GMO Convert from CCSID of qmgr to our/client OS CCSID
                               convert=True,
                               command_queue_name=b'SYSTEM.ADMIN.COMMAND.QUEUE'
                               )
#7007=MQBACF_GENERIC_CONNECTION_ID
#1110=MQIACF_CONN_INFO_TYPE
#1111=MQIACF_CONN_INFO_CONN
request_pcf = OrderedDict([(7007, ByteString(value=b'')), (1110, 1111)])
pcf_mqcmd = 'MQCMD_INQUIRE_CONNECTION'
try:
    response_pcf = eval('pcf_execute.' + pcf_mqcmd)(request_pcf)
    pprint.pprint(response_pcf)
except pymqi.MQMIError as e:
    print(f'pymqi exception{e}')
`

**Comment by SeyfSV** [comment]
Hi @shivanekanti ,

Can you replace
```
        request_pcf = OrderedDict([(7007, ByteString(value=b'')), (1110, 1111)])
```
with
```
        request_pcf = []
        request_pcf.append(pymqi.CFBS(Parameter=pymqi.CMQCFC.MQBACF_GENERIC_CONNECTION_ID,
                                String=b''))
        request_pcf.append(pymqi.CFIN(Parameter=pymqi.CMQCFC.MQIACF_CONN_INFO_TYPE,
                                Value=pymqi.CMQCFC.MQIACF_CONN_INFO_CONN))
```
Also, check [PR](https://github.com/shivanekanti/pymqi/pull/1)
