### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by 2020testuser** [dsuch/pymqi#264]
Hi,
I'm getting error when I try to run my docker file with IBM MQ Client and pymqi.
Could anyone share the working version of Dockerfile with IBMMQClient and pymqi which can connect successfully to a remote MQ Server? Appreciate any help!
Thanks in advance!
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "python3": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled`

**Comment by SeyfSV** [comment]
Hi @2020testuser , the question is not related to the `pymqi` project.

**Comment by agamjajoo** [comment]
@SeyfSV is correct, question is not related to `pymqi` project.

@2020testuser if you are just wanting to look at the docker file, here's what I use - 
[https://github.com/agamjajoo/docker_ibm_mq_python/blob/master/Dockerfile](url)

It's little different on the lines of - I go into the container to the run the scripts whereas from the looks of your error you are trying to execute something once/after container starts up, if that's non-negotiable then you'd want to make minor change in the dockerfile, yell out (separately) if you need advise. Happy to help!
