### ISSUE TITLE
How do we filter channel based upon the cipherspec?

### ISSUE THREAD

**Issue by atulk0** [dsuch/pymqi#267]
I'm trying to filter out MQ channels based upon the cipher spec. Say for example I have something like this?

```
args = {pymqi.CMQCFC.MQCACH_SSL_CIPHER_SPEC: 'TLS_RSA_WITH_AES_256_CBC_SHA'.encode('utf-8')}
```

When I try to do that, I get the following error:

```
pymqi.MQMIError: MQI Error. Comp: 2, Reason 3016: FAILED: MQRCCF_MSG_LENGTH_ERROR
```

**Comment by JoshMcMQ** [comment]
Which platform?

**Comment by atulk0** [comment]
My client is on Windows, the queue manager is running on Linux.

**Comment by SeyfSV** [comment]
Hi @atulk0 ,
If you want to filter in old format, you should use filter `filter = pymqi.Filter(pymqi.CMQCFC.MQCACH_SSL_CIPHER_SPEC).equal(self.cypher_spec)`
If you want to filter in new format, you should use something like this:
```
        attrs = [] 
        attrs.append(pymqi.CFST(Parameter=pymqi.CMQCFC.MQCACH_CHANNEL_NAME,
                                String=b'*'))
        attrs.append(pymqi.CFIN(Parameter=pymqi.CMQCFC.MQIACH_CHANNEL_TYPE,
                                Value=pymqi.CMQC.MQCHT_SVRCONN))

        object_filters = []
        object_filters.append(
            pymqi.CFSF(Parameter=pymqi.CMQCFC.MQCACH_SSL_CIPHER_SPEC,
                       Operator=pymqi.CMQCFC.MQCFOP_EQUAL,
                       FilterValue=self.cypher_spec))

        results = self.pcf.MQCMD_INQUIRE_CHANNEL(attrs, object_filters)
```

**Comment by atulk0** [comment]
Thanks @SeyfSV , it worked with old format. In the new format, I assume it is `Value=b'*`' rather than `String=b'*'`.

However, when I try with new format, I get the following error:

```
pymqi\__init__.py", line 2723, in __call__
    message = message + parameter.pack()
pymqi\__init__.py", line 312, in pack
    return struct.pack(*args)
struct.error: required argument is not an integer
```

**Comment by SeyfSV** [comment]
No, CFST class uses String attribute, check [this](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=types-mqcfst-string-parameter)

**Comment by atulk0** [comment]
Got it, thanks a lot @SeyfSV . It works with the new format as well.
