### ISSUE TITLE
Module 'pymqe' not found in Mac OS

### ISSUE THREAD

**Issue by MrEzio** [dsuch/pymqi#269]
Hi! I just installed the IBM MQ MacOS Toolkit for developers and followed the instructions for the installation there. (https://developer.ibm.com/components/ibm-mq/tutorials/mq-macos-dev/)

After installing IBM MQ to  `/opt/mqm/`  I added the locations of the bin directories  `/opt/mqm/bin/`  and  `/opt/mqm/samp/bin` to the PATH by editing  /etc/paths. I tested it by running `dspmqver` on the terminal and it was working.

Lastly I set the DYLD_LIBRARY_PATH to `/opt/mqm/lib64` on the terminal with export command.

Then I finally installed pymqi with pip3 install, everything went smoothly. When I wrote the code I got the error of Module 'pymqe' not found.

Thanks for the help! Been struggling with this for days.

**Comment by JoshMcMQ** [comment]
Do you have DYLD_LIBRARY_PATH set when you execute the code?

**Comment by MrEzio** [comment]
I set it in the terminal with `export DYLD_LIBRARY_PATH=/opt/mqm/lib64` then I go to the VsCode and run the code. Problem I see is that when I close the terminal and re open it again, `echo $DYLD_LIBRARY_PATH` doesn't show anything.

**Comment by MrEzio** [comment]
I tried setting it in the same directory where I compile the code or when I try a `python3 -c 'import pymqi'` on the terminal only. The env variable is set to the correct path, but the same bug persists.

**Comment by JoshMcMQ** [comment]
Can you set the env inside you python code?

**Comment by chughts** [comment]
The issue you are facing is that you need to run the export whenever you create a new terminal. 

You can edit your profile so that it is set automatically for every new terminal. How you do it depends on which shell you are using. If you haven't done anything to change it then you will be using zsh

In which case edit `~/.zshrc`
and add the export there.

**Comment by MrEzio** [comment]
@JoshMcMQ Yes I set the env inside the python code but it still didn't work. Running `amqscnxc` didn't present any problems. I have this in the terminal : 
```
$ amqscnxc
Sample AMQSCNXC start
Connecting to the default queue manager
with no client connection information specified.
MQCONNX ended with reason code 2058
```


@chughts I tried with ~/.zshrc by creating it and then putting the export of DYLD_LIBRARY_PATH to /opt/mqm/lib64. Now everytime I open the terminal and echo this env, it always shows the correct path, so that worked! But the error still persists with the pymqe module :/

**Comment by chughts** [comment]
Re: #200 are you running in a virtualenv ?
Running in a virtualenv ensures that you only have the python modules that your application requires, and not everything that is available globally on your machine.

**Comment by MrEzio** [comment]
No I'm not running it in a virtualenv. I wanted to get it working like Linux without the need of a virtualenv, but I guess in Mac, we have to use it?
Also another question a little bit unrelated to the pymqi module, when I installed the `IBM MQ DevToolkit 9.2.3.0`, I realized that I was missing `runmqckm`. Is there a reason why? `runmqakm` is there though.

**Comment by chughts** [comment]
`runmqckm` is not a part of the MQ Client Toolkit for MacOS.

**Comment by dsuch** [comment]
Mass-closing old tickets.

**Comment by andreasgou** [comment]
MacOS Monterey and the issue keeps on going.
Have you resolved it?
