### ISSUE TITLE
MQI Error. Comp: 2, Reason 2538: FAILED: MQRC_HOST_NOT_AVAILABLE

### ISSUE THREAD

**Issue by akki999** [dsuch/pymqi#274]
Each & every time when i try to connect with the API using PYMQI it throws me an this error. Can someone help me on this?
mine code snippet is:

```
import pymqi
queue_manager = 'QM01'
channel = 'SVRCONN.1'
host = '192.168.1.135'
port = '1434'
queue_name = 'TEST.1'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info)

pcf = pymqi.PCFExecute(qmgr)
pcf.MQCMD_PING_Q_MGR()

qmgr.disconnect()
```

And suppose if I try to use SSL_cipher parameter then it gives me another issues like below:

```
Python 3 style string (unicode) found but not allowed here: `b'10.94.135.147'(7392)`. Convert to bytes.
```

NOTE: I have changed the Queue Manager and other credentials because of confidentiality issue.

Thanks in Advance

**Comment by chughts** [comment]
2538, indicates that the combination of host, port and channel is incorrect.

**Comment by akki999** [comment]
Ok, understood @chughts can you please tell me that when I'm using SSL_cipher parameter then its giving some another issue associated to python3 string.

Why is this happening?

**Comment by chughts** [comment]
You don't show the code where you are setting the cipher, so it's difficult to tell. Especially as `b'10.94.135.147'(7392)` is the connection string, not the cipher.

Otherwise, this is a normal python 2 vs 3 problem string problem - https://portingguide.readthedocs.io/en/latest/strings.html

If you are using python 3 you need to convert your strings to bytes eg

````
    @staticmethod
    def getConnection(host, port):
        conn =  "%s(%s)" % (host, port)
        if sys.version_info[0] < 3:
            return str(info)
        else:
            return bytes(info, 'utf-8')
````

but I thought that this had been put into `pymqi`, so it wasn't necessary any more - https://dsuch.github.io/pymqi/examples.html#sending-unicode-data-vs-bytes

Maybe the pcf code still has this issue.

**Comment by akki999** [comment]
import logging

import pymqi

logging.basicConfig(level=logging.INFO)

queue_manager = 'QM01'
channel = 'SVRCONN.1'.encode('utf-8')
host = '192.168.1.135'
port = '1434'
queue_name = "TEST1".encode('utf-8')
conn_info = ("%s(%s)" % (host, port)).encode('utf-8')
ssl_cipher_spec = "TLS_RSA_WITH_AES_128_CBC_SHA256".encode('utf-8')
key_repo_location = r"C:\Users\Administrator\Desktop\QMRECCGW\MySelf_local".encode('utf-8')
message = "Hello from Python!".encode('utf-8')
# user = "QMRECCGWS"
# password = " "

cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
#cd.CertificateLabel = "EAI".encode("utf-8")
cd.UserIdentifier = "QMRECCGWS".encode('utf-8')
cd.Password = ''.encode('utf-8')


sco = pymqi.SCO()
sco.KeyRepository = key_repo_location
# sco.CertificateLabel = "ibmwebspheremqEAI".encode("utf-8")

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, cd, sco)

put_queue = pymqi.Queue(qmgr, queue_name)
put_queue.put(message)

get_queue = pymqi.Queue(qmgr, queue_name)
logging.info("Here's the message again: [%s]" % get_queue.get())

put_queue.close()
get_queue.close()
qmgr.disconnect()


The above code gives me this error **MQI Error. Comp: 2, Reason 2393: FAILED: MQRC_SSL_INITIALIZATION_ERROR** with PyMQI can you please help me understand what's the potential issue. Because it's urgent and we are facing a major set back in production.

**Comment by JoshMcMQ** [comment]
This is volunteer help and I would set your expectations as such.

Have you looked at the `AMQERR01.LOG` on your windows client machine?  This should help you figure out why you are getting a 2393.

Can you confirm that `C:\Users\Administrator\Desktop\QMRECCGW\MySelf_local` is the base name of your key repository? In other words you should have two files:
```
C:\Users\Administrator\Desktop\QMRECCGW\MySelf_local.kdb
C:\Users\Administrator\Desktop\QMRECCGW\MySelf_local.sth
```

Those two files should be readable by the user the program runs under.

**Comment by akki999** [comment]
Ok thanks for your help.

Can you do one last favour for me please?

Can you please where I can find that log file?
Is it on my server? Or Is it on the IBM server where Queue Managers are
Created?

And also those two files .kdb & .sth are both present in the same folder.

Thanks again for your Support.

Thanks & Regards
Aakash Bhatt
8433527231 / 7021462073

**Comment by JoshMcMQ** [comment]
I had mentioned "on your windows client machine".  What type of client install do you have?   If it is a full client check the under the errors folder in the location pointed to by one of these environment variables:

```
MQ_FILE_PATH
MQ_DATA_PATH
```

If it is a redist client it will go under the user's home directory check for a folder called `IBM` and still down from there to and errors folder.

**Comment by akki999** [comment]
I don't remember it that exactly which client I have installed but mostly o
think I have installed the redist client  version 9.2

Thanks & Regards
Aakash Bhatt
8433527231 / 7021462073

**Comment by dsuch** [comment]
Mass-closing old tickets.
