### ISSUE TITLE
Where does `pymqi` look for the MQ SDK at install time?

### ISSUE THREAD

**Issue by albertvaka** [dsuch/pymqi#275]
We are downloading and uncompressing the IBM MQ redistributable client for Windows. In which path should it be for `pymqi` to find the DLLs, include dirs... given there's no standard path for such things on Windows?

**Comment by SeyfSV** [comment]
Hi, read this https://www.ibm.com/docs/en/ibm-mq/9.2?topic=file-location-client-configuration and use MQ_FILE_PATH

**Comment by albertvaka** [comment]
Awesome! Maybe we could mention the existence of `MQ_FILE_PATH` in pymqi's README?
