### ISSUE TITLE
Will connections using CCDT be supported for MQ uniform clusters?

### ISSUE THREAD

**Issue by creasman** [dsuch/pymqi#277]
I need to connect to an MQ uniform cluster using Python.  This client works great for non-CCDT connections, but I don't see support for CCDT.  I read the previous issue (https://github.com/dsuch/pymqi/issues/268) on this topic.  The conclusion seems to be if I set cd=None, then the underlying client code will search and find the CCDT.  This is not working for me for the following reasons:

- Passing "cd=None" causes an exception at line 1607 in https://github.com/dsuch/pymqi/blob/master/code/pymqi/__init__.py.  If "cd" is one of the args the code expects a value, not None.
- Invoking "connect_with_options" without providing cd goes further into the code, but ends with an MQ error indicating it does not know the qmgr name ("*QM_ANY" in my case).  

The crux of the issue is there is no way to directly access the CNO object that is passed to MQCONNX.  For our NodeJS clients that use the CCDT we pass the value as a URL in the MQCNO object as follows:

```
let cno = new mq.MQCNO();
cno.SecurityParms = {"UserId": user, "Password": pwd}
cno.Options |= MQC.MQCNO_CLIENT_BINDING;
cno.CCDTUrl = ccdturl;

mq.Connx(qMgr, cno, function (err, hConn) {
   ...
}
```

The underlying MQ code requests the CCDT from the URL and makes the connection.  From what I can see, the connect_with_options API does not have a way to pass the CNO, just the Options and CD (which are sub-elements of CNO).

Am I missing something?  

Thanks,
Jim

**Comment by JoshMcMQ** [comment]
Can you post the exact error you get when you try with `connect_with_options`? Can you also check the AMQERR01.LOG on the MQ Client side and post any error produced.   This file is under `/var/mqm/errors` on a full client install or `$HOME/IBM/MQ/data` if you are using the ReDist client.

**Comment by creasman** [comment]
Thanks, Josh.  In the first scenario (cd=None), I get this error on the client side.  It never makes it to the server.
```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymqi/__init__.py", line 1607, in connect_with_options
    if cd.SSLCipherSpec and cd.Version < CMQC.MQCD_VERSION_7:
AttributeError: 'NoneType' object has no attribute 'SSLCipherSpec'
```

If I don't use the "cd" option at all I see this error.  Note, the message formatting is mine, but the text of the error is what's returned by the connect call.  
```
Configuration:
{
  "ccdtUrl": "http://localhost:8089/ccdt?name=CLNT.QC9",
  "qmgr": "*QM_ANY",
  "queueName": "REM.MQDEV.QUEUE.V1",
  "putUser": "mqdevsnd",
  "putPwd": "********"
}
INFO:  Connecting from CCDT: http://localhost:8089/ccdt?name=CLNT.QC9
INFO:  Qmgr name is *QM_ANY
ERROR:  Failed to connect: MQI Error. Comp: 2, Reason 2058: FAILED: MQRC_Q_MGR_NAME_ERROR
```

This is the call I'm using:
```
        try:
            self.qmgr.connect_with_options(qmgr_name,
                                        user=user,
                                        password=password,
                                        opts=options, sco=sco)

            logger.info('Connection to queue manager successful.')
            return self.qmgr

        except pymqi.MQMIError as e:
            logger.info(f'Qmgr name is {qmgr_name}')
            logger.error(f'Failed to connect: {e}')
            return None```

No errors are logged on the server side.  I'm certain it's not making it to the server.  The 2058 error is coming from the MQ client code.

Even if we somehow got past this error I still don't see how it could work.  There is no way to provide the CCDTUrl value to MCONNX since this must be passed in via MQCNO connect setting.  From what I can glean the connect_with_options doesn't expose this.  Instead, it builds the CNO directly.

Jim

**Comment by creasman** [comment]
One way to support this is to update pymqe.c to set cno.CCDTUrlPtr similar to how ClientConnPtr is done.  A new parameter would need to be added to connect_with_options (e.g., ccdturl=) to supply the value.  The IBM docs on CCDTUUrlPtr are at https://www.ibm.com/docs/en/ibm-mq/9.2?topic=mqi-mqcno-connect-options.  This requires MQCNO_VERSION_6, or higher.

**Comment by JoshMcMQ** [comment]
You forgot this:

> Can you also check the AMQERR01.LOG on the MQ Client side and post any error produced. This file is under /var/mqm/errors on a full client install or $HOME/IBM/MQ/data if you are using the ReDist client.

Specifying CCDTURL programmatically is only one of the ways to provide the location of the CCDT, it can be placed in the mqclent.ini or in an environment variable.   I think you are getting 2058 because you are trying to pass it programmatically when as you said it is not currently possible. 

See this answer:  https://github.com/dsuch/pymqi/issues/268#issuecomment-873416038

Pull requests are welcome to add ccdt url support.   This could be implemented as another optional named parameter to connect_with_options.  This would then not break existing apps not passing it.

**Comment by creasman** [comment]
I didn't forget the AMQERR01.LOG file.  As I mention, there are no errors in this file... just the normal informational messages from startup.  I can post these, but they won't be of any use.

In our other client applications we read the config information from a common JSON file and then pass this programatically.  I was hoping to do the same with Python.  I'll try writing this to a mqclient.ini file.  

Is there a particular reason you would not want to support passing the CCDT information programmatically?  Seems this would be on parity with how the cd option is being used for connection to a specific server.

**Comment by JoshMcMQ** [comment]
Hi Jim,  I think you are taking about the AMQERR01.LOG  on the queue manager,  I'm asking for the info from the machine where the client is running.

As to your questions about why it is not supported in pymqi,  CCDTURL was not added to the MQ C API until 9.0 so is somewhat of a newer feature.   pymqi is supported for free by people like you and I.  If you are interested in adding this feature you can make a pull request and add it so that it can be contributed back into pymqi for other people to utilize.   Welcome to open source.

**Comment by JoshMcMQ** [comment]
You could pass it as a ENV variable programmatically, something like this should work:

```
import os

os.environ['MQCCDTURL']='http://localhost:8089/ccdt?name=CLNT.QC9'
```

**Comment by creasman** [comment]
Josh, my apologies.  I wasn't reading your request carefully and just assumed the server log.  I really do appreciate your help and quick responses. 

This is the error from the client side log from my laptop:

```
12/23/2021 09:29:33 - Process(62169.1) User(ap677) Program(Python)
                    Host(AP677s-MacBook-Pro.local) Installation(MQNI92L21110500D)
                    VRMF(9.2.4.0)
                    Time(2021-12-23T14:29:33.578Z)
                    ArithInsert1(1013)
                    CommentInsert1(/Users/ap677/IBM/MQ/data/AMQCLCHL.TAB)
                   
AMQ9518E: File '/Users/ap677/IBM/MQ/data/AMQCLCHL.TAB' not found.

EXPLANATION:
The program requires that the file '/Users/ap677/IBM/MQ/data/AMQCLCHL.TAB' is
present and available.
ACTION:
This error may be caused by the program specifying an incorrect file location
programmatically via MQCNO value through CCDTUrlPtr or CCDTUrlOffset. If the
program has not specified the file location, the environment variables
MQCHLLIB, MQCHLTAB or MQCCDTURL may have been specified. If none of these
environment variables are set, the location of the file may have been specified
in the mqclient.ini through ChannelDefinitionDirectory and
ChannelDefinitionFile attributes under the Channels stanza. If the location was
not configured programmatically, by environment variable or by mqclient.ini
values then '/Users/ap677/IBM/MQ/data/AMQCLCHL.TAB' represents a default
location and filename for this installation. Ensure that file location is
correctly configured and that the file is available to the program.
----- amqrcdfa.c : 619 --------------------------------------------------------
```
It's looking for the binary CCDT (AMQCLCHL.TAB), which isn't there.  

Our MQ clients are deployed in the cloud and we've chosen to use a REST service to provide the connection information.  The client only needs to know the CCDTUrl value.  

Your suggestion of setting MQCCDTURL works like a charm.  Thanks!  I was considering submitting a PR with changes to support a ccdt parameter, but (full disclosure) I'm new to Python and it's been a couple of decades since I last wrote C code.  For now, I will stay with setting MQCCDTURL.

Thanks again,
Jim

**Comment by JoshMcMQ** [comment]
I wouldn't let that discourage you,  others will need to review and incorporate the change into a release.  I do think having it directly exposed is a cleaner solution than ENV variables.

Glad you found a working solution.  If you don't plan on submitting a pull request I think this can be closed.

**Comment by JoshMcMQ** [comment]
@chughts is this an enhancement you could take on?

**Comment by chughts** [comment]
@JoshMcMQ reading through the comments, I get the impression that setting the environment variable `MQCCDTURL` did the trick.

> Your suggestion of setting MQCCDTURL works like a charm

Is there a related `pymqi` change you are considering?

**Comment by JoshMcMQ** [comment]
@chughts specifically adding the ability to programmatically set the CCDT URL programmatically (see https://github.com/dsuch/pymqi/issues/277#issuecomment-1000341696).

**Comment by JoshMcMQ** [comment]
Didn't mean to reopen but will leave it for now.

**Comment by chughts** [comment]
It's a bit of a chicken and egg situation. If you are add an extra optional parameter to `connect_with_options` you need to indicate where the CCDT can be found, which environment variables like `MQCCDTURL` are already doing. 

The problem with environment variables is that some environments stop them from being inherited by child shells.

**Comment by JoshMcMQ** [comment]
@chughts I'm not suggesting adding an option to programmatically set the environment variable. 

My suggestion is to programmatically point to the ccdt via CCDTUrlOffset and CCDTUrlPtr in MQCNO. 

The suggestion was "update pymqe.c to set cno.CCDTUrlPtr similar to how ClientConnPtr is done. A new parameter would need to be added to connect_with_options (e.g., ccdturl=) to supply the value."

**Comment by Skyler-Altol** [comment]
@JoshMcMQ I have a better idea. This will actually kill several birds with one stone. Stop making the MQCNO as `MQCNO cno = {MQCNO_DEFAULT};` in the C code, and instead create an MQCNO class in the python level, same as we have for all the other objects. Then allow the user to optionally create a CNO, and pass it in.

This would allow for an application to set its name for example, (as appname is a CNO field), as well as multiple other things controlled by the CNO.

**Comment by JoshMcMQ** [comment]
That would work too.

**Comment by creasman** [comment]
I like @Skyler-Altol suggestion.  Being able to assign the application name is important from a MQ uniform cluster point of view as this is used by MQ to balance and distribute the connections across the various qmgrs in the cluster.  Having the CNO be a class seems a cleaner solution.

**Comment by Skyler-Altol** [comment]
Technically it *is* possible to set the application's name already, using the MQAPPNAME environment variable, which is what I've been doing with my python code that uses PyMQI. However, this is not exactly a "clean" solution. PyMQI should be aiming to replicate the C interface's functionality (at a high level) as much as possible. Why MQCNO was skipped when all the other classes were created at first... baffles me a little bit not gonna lie.

**Comment by dsuch** [comment]
@Skyler-Altol The reason why MQCNO was skipped is simply that it was not needed by anyone at that time and there is still no one willing to support adding such a feature.

I see various "I want to use this or that" or "I need to do this or that" comments in this tracker from employees of banks, airlines, large healthcare providers and other multi-billion enterprises.

At the same time, the number of people who want to sponsor the development of such features is below zero. 

Personally, I do not have much need to be a free worker for such people and unless there are some capabilities that I need myself in my own projects, I am not going to implement anything for such predatory companies who treat open source like a source of cheap labour.

**Comment by Skyler-Altol** [comment]
After being away for quite a while, here we go again :D

I started actually delving into writing a CNO class. However, I quickly ran into the same issue I identified in a previous issue that was raised, which is that the constants defined in PyMQI are not up to date. We cannot even *begin* to write the new functionality without these constants being updated. I did the legwork and provided the updated constants for CMQC and CMQCFC based on a 9.2.0.1 MQ client in a format that was compatible with Python, but was then explicitly told *not* to raise a pull request and to instead provide them in a github gist, which I did.

I spent probably close to 10 hours making what was contained within those gists, and it was just... "discarded" and ignored. Writing an automated solution to parse the constants with python really isn't necessary. If we can get the constants *close* to up to date with a known client version as a base, we can use any number of comparison tools to compare the cmqc.h from version X to new version Y, and see what IBM changed or added. We then replicate these changes over into our constant files, and voila. It would take probably 10 minutes at most, every ~6 months when IBM releases a new continuous delivery release. The ROI on such a complex piece of automation to handle all the edge cases just isn't good enough to warrant the effort when the aforementioned semi-automatic solution is available.

So please, *please*, consider implementing the constant updates contained within these:

https://gist.github.com/Skyler-Altol/de9c2fcecee896a4f306592d49636d95
https://gist.github.com/Skyler-Altol/c8de4842ea85f994974354c2ff786544

If an indication is given that those will be implemented, I'll spend the rest of the time needed to do the remainder of the smaller client header files.

**Comment by Skyler-Altol** [comment]
With @SeyfSV's help, #294 has been merged. This opens the door to writing the CNO class now, because all the requisite constants are present. I've just started a new job, and have actually been somewhat bored recently because I don't have the access to do much stuff atm. I'll see about getting a dev environment configured on my new work laptop & will get started on the CNO soon.
