### ISSUE TITLE
Using PCFExecute with z/OS 

### ISSUE THREAD

**Issue by yzhan289** [dsuch/pymqi#279]
I am trying to use PCFExecute for z/OS, and I saw from https://github.com/dsuch/pymqi/pull/198#issuecomment-643823886 that pymqi works for z/OS when constructing the PCF messages and sending them to the command queue. I want to use `PCFExecute` instead of constructing messages manually. Is that supported for z/OS? 

It seems like with `PCFExecute`, the reply queue keeps using the dynamic temporary queue `PYMQPCF.*` as the reply-to queue, but I want to send the messages to the command queue instead. Is there a way to change the reply-to queue with `PCFExecute`?

**Comment by JoshMcMQ** [comment]
PCFExecute uses the underling MQAI interface from IBM which does not support z/OS.

**Comment by yzhan289** [comment]
Thanks! Is there a timeline for when/if MQAI will support z/OS?

**Comment by JoshMcMQ** [comment]
IBM has stated that MQAI (MQ Admin Interface) is stabilized.   They will not be updating it with z/OS support.   PCF is the supported option.

**Comment by ofek** [comment]
> IBM has stated in many locations that MQAI will not be enhanced and will likely be formally deprecated in a future release

Does that also mean `PCFExecute` should be considered a legacy API?

**Comment by SeyfSV** [comment]
> It seems like with PCFExecute, the reply queue keeps using the dynamic temporary queue PYMQPCF.* as the reply-to queue, but I want to send the messages to the command queue instead. Is there a way to change the reply-to queue with PCFExecute?

Yes.

1. You can use `PCFExecute.dynamic_queue_name` attribute for this 

1. You can use pymqi for sending and recieving raw PCF. Do not use PCFExecute. Search for `test_arbitrary_message_with_mqcfil` in tests.

**Comment by SeyfSV** [comment]
@yzhan289 , did you solve your problem? Can I close issue?

**Comment by yzhan289** [comment]
Hi @SeyfSV, yes you can close the issue. Thanks for the help!
