### ISSUE TITLE
error: command 'c:\\mingw\\bin\\g++.exe' failed with exit status 1

### ISSUE THREAD

**Issue by mlotfi2005** [dsuch/pymqi#28]
Hi,
I tried to get the pymqi using pip but got :+1: 
error: command 'c:\\mingw\\bin\\g++.exe' failed with exit status 1

do I have to have WebSphere MQ installed in my machine ? is it free ?
thanks.

**Comment by dsuch** [comment]
Hi @mlotfi2005,

I'm very sorry but I'm unable to provide free support on Windows, as mentioned here https://github.com/dsuch/pymqi#supported-mq-versions

Please contact me on dsuch@zato.io if you'd like to discuss the terms of the commercial support.

Thanks!

**Comment by mlotfi2005** [comment]
never mind, I am only learning, no commercial.

On Thu, Nov 19, 2015 at 10:44 AM, Dariusz Suchojad <notifications@github.com

**Comment by dsuch** [comment]
I see, @mlotfi2005 - in that case I definitely suggest using Linux at least under Vagrant. This makes everything an order of magnitude easier.

I will close the ticket now, thanks again for raising it!
