### ISSUE TITLE
MQRC_SSL_INITIALIZATION_ERROR due to CipherSpec byte value getting truncated

### ISSUE THREAD

**Issue by harinivas-ganapathy** [dsuch/pymqi#280]
When attempting to use SSL/TLS I am getting below error - 
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2393: FAILED: MQRC_SSL_INITIALIZATION_ERROR

Below is the script I use - 
```
import pymqi

queue_manager = b'Q_MNGR'
channel = b'T_APPCHNL'
host = b'conserver.com'
port = b'1452'
queue_name = b'TEST_QUEUE'
conn_info = b'%s(%s)' % (host, port)
ssl_cipher_spec = b'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
key_repo_location = b'/home/runapp/appssl'
message = b'Hello from Python'

cd = pymqi.CD()
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.SSLCipherSpec = ssl_cipher_spec

sco = pymqi.SCO()
sco.KeyRepository = key_repo_location
sco.CertificateLabel = b'appnonprodmq'

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manger, cd, sco)

qmgr.disconnect()

```

In the MQ Logs at /var/mqm/errors/AMQERR01.LOG I see the below information
```
-----amqccisa.c : 1432---------------------------------------------------------------------
02/07/2022 06.40.06 PM - Process(32003.1) User(appuser) Program(python)
                                              Host(conserver.com) Installation(Installation4)
                                              VRMF(9.2.0.3)
                                              Time(2022-02-07T23.40.06.275Z
                                              CommentInsert1(T_APPCHNL)
                                              CommentInsert2(ECDHE_RSA_WITH_AES_256_GCM_SHA38)

AMQ9635E: CHANNEL 'T_APPCHNL' did not specify a valid CipherSpec.

----- amqccisa.c : 1432 --------------------------------------------------------------------
```

From info above Looks like the last char '4' was truncated from `ssl_cipher_spec`. And hence the error.

Please help. 

Let me know if additional details are required.

**Comment by JoshMcMQ** [comment]
This is not a pymqi issue.  The value `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`  you used is the non-IBM (Oracle)  Java ciphersuite value.   pymqi uses the C API and you would need to use the equivalent IBM MQ cipherspec  `ECDHE_RSA_AES_256_GCM_SHA384`.  You can find the mappings [here](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=jms-tls-cipherspecs-ciphersuites-in-mq-classes).

**Comment by harinivas-ganapathy** [comment]
Thanks for your quick response. This definitely helped. Updating the Cipher to `ECDHE_RSA_AES_256_GCM_SHA384` worked.
