### ISSUE TITLE
MQ newbie - trying to setup MQ client application

### ISSUE THREAD

**Issue by malcolmbovey** [dsuch/pymqi#281]
Hi,

I'm trying to setup a simple IBM MQ client application.  I have zero prior experience of MQ but have done my best to educate myself from the documentation.

I'm attempting to build application inside a container built on the default python 3.8 docker image.
So far I am downloading and installing the MQ "Redist" package from https://www.ibm.com/docs/en/ibm-mq/9.1?topic=linux-redistributable-clients (default installation folder)  I then install pymqi via pip

This all works, but when I try to import pymqi I get the following error:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymqi/__init__.py", line 132, in <module>
    from . import pymqe # type: ignore
ImportError: libmqic_r.so: wrong ELF class: ELFCLASS32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 1, in <module>
    import pymqi
  File "/usr/local/lib/python3.8/site-packages/pymqi/__init__.py", line 134, in <module>
    import pymqe # type: ignore # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'
```

Any assistance with this much appreciated.

Thanks

**Comment by chughts** [comment]
See #157 

Did you set `MQ_INSTALLATION_PATH` and `LD_LIBRARY_PATH` ?

Ensure that `MQ_INSTALLATION_PATH` is set to the root directory of the MQI Client installation and `LD_LIBRARY_PATH` is set to `$MQ_INSTALLATION_PATH\lib64`

**Comment by malcolmbovey** [comment]
Ah, that was it!  Fixed now.  Thanks in advance for any help I need with getting the actual application working...

**Comment by JoshMcMQ** [comment]
Resolved
