### ISSUE TITLE
MQSETMP - problem

### ISSUE THREAD

**Issue by Lipq1** [dsuch/pymqi#282]
Hello,

I'm trying to test 3 extra parameters for my message. I've used https://github.com/dsuch/pymqi/blob/master/code/examples/message_property_set.py 
as an example and I'm struggling with error which I don't understand at all.

SystemError: <built-in function MQSETMP> returned a result with an error set

Same result on windows/linux based machines.

**Comment by chughts** [comment]
Does the error occur on a 
```python
put_msg_h.properties.set(property_name, property_value) # Default type is CMQC.MQTYPE_STRING
```

If so what type is `property_value` in your case?

**Comment by Lipq1** [comment]
I'm using default one, so strings
put_msg_h.properties.set(b"param", b"value")

**Comment by chughts** [comment]
Did you try with strings inplace of bytes arrays?
```python
put_msg_h.properties.set("param", "value")
```

**Comment by SeyfSV** [comment]
Hi @Lipq1,

Please, provide example code that you use and full stack trace of the error.
Also you can check code that used for testing pymqi: https://github.com/dsuch/pymqi/blob/061492082248989436d174c8a081b51a922c6e6a/code/tests/test_message_property.py

**Comment by Lipq1** [comment]
Code below.

Stack:
`Traceback (most recent call last):`
`  File "test.py", line 8, in <module>`
`    put_msg_h.properties.set(b"param", b"value")`
`  File "venv\lib\site-packages\pymqi\__init__.py", line 2537, in set`
`    comp_code, comp_reason = pymqe.MQSETMP(`
`SystemError: <built-in function MQSETMP> returned a result with an error set`


When I'm using strings (`put_msg_h.properties.set("param", "value")`), error looks like that:
`Traceback (most recent call last):`
`  File "test.py", line 8, in <module>`
`    put_msg_h.properties.set("param", "value")`
`  File "venv\lib\site-packages\pymqi\__init__.py", line 2537, in set`
`    comp_code, comp_reason = pymqe.MQSETMP(`
`TypeError: a bytes-like object is required, not 'str'`


I can add that, when I skip properties.set() code works and I can see message on the queue, but of course without extra param.

```
import pymqi

qmgr = pymqi.connect(queue_manager="MANAGER", channel="CHANNEL", conn_info="HOST(PORT)", bytes_encoding="utf-8")

put_msg_h = pymqi.MessageHandle(qmgr)

put_msg_h.properties.set(b"param", b"value")

pmo = pymqi.PMO(Version=pymqi.CMQC.MQPMO_VERSION_3)
pmo.OriginalMsgHandle = put_msg_h.msg_handle

put_md = pymqi.MD(Version=pymqi.CMQC.MQMD_CURRENT_VERSION)

queue = pymqi.Queue(qmgr, "QUEUE")

queue.put("This is test message", put_md, pmo)

qmgr.disconnect()

**Comment by Lipq1** [comment]
Finally it works. 
Thanks @SeyfSV  for link to test. Below change fixed the issue.
 ```
key = b"param"
value = b"value"
put_msg_h.properties.set(key, value, value_length=len(value), property_type=pymqi.CMQC.MQTYPE_BYTE_STRING)
