### ISSUE TITLE
_MQConst2String not found

### ISSUE THREAD

**Issue by rkbroder** [dsuch/pymqi#287]
I am using:

[mqm@fibbing1 scripts]$ python3 --version
Python 3.6.8

I am trying to use _MQConst2String. I see it in pymqi/code/pymqi/__init__.py

I tried this from sample code I found, the import fails also.

try:
    from . import pymqe # type: ignore
except ImportError:
    import pymqe # type: ignore # Backward compatibility

**Comment by dsuch** [comment]
Hello @rkbroder,

I am going to close this ticket - the code you posted is not formatted, there are no details at all what you want to achieve, what the errors are, what PyMQI version it is etc.

Regards.

**Comment by rkbroder** [comment]
I figured it out with the help of people on MQSeries.net. Thanks.
