### ISSUE TITLE
Does pymqi support read ahead? If yes, how do I use it?

### ISSUE THREAD

**Issue by chmduquesne** [dsuch/pymqi#29]
Hi,

I would like to use the read ahead features as described in http://www-01.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.dev.doc/q027330_.htm

Is that possible with pymqi? If yes, where can I find a dummy example?

Thank you!

**Comment by dsuch** [comment]
Hi @chmduquesne,

I haven't used this exact feature so I cannot offer a working example but by skimming through the docs it seems it is enabled by using a specific MQOO_ option, MQOO_READ_AHEAD to be precise.

MQOO_ options are options used when opening queues.

So my suggestion is to use another usage example already using a different MQOO_ such as the one here ..

https://pythonhosted.org/pymqi/examples.html#how-to-use-an-alternate-user-id

.. which uses MQOO_ALTERNATE_USER_AUTHORITY and adapt it to your needs of MQOO_READ_AHEAD .

Cheers!

**Comment by chmduquesne** [comment]
Thank you for the quick reply and the helpful insight!

Cheers!

**Comment by chmduquesne** [comment]
Hello again!

I am reopening this issue because I have been struggling with this MQOO_READ_AHEAD option for a while. I opened a [topic](http://www.mqseries.net/phpBB2/viewtopic.php?t=71554) on the mqseries forum in order to have other people look into this. Maybe as the author, you have a deeper understanding of the library and can provide insights. 

Could you have a look at this thread and comment on the code I provide on this [gist](https://gist.github.com/chmduquesne/5d730dcf297d064abde5)? I would be very interested in getting your opinion.

Cheers,
Christophe-Marie

**Comment by chmduquesne** [comment]
It looks like that, for some reason, the performance of this read ahead feature is affected by the encoding. I tried to modify the requested encoding to match the encoding of the messages in the queue, but it does not work. Maybe you have an idea?

See [http://www.mqseries.net/phpBB2/viewtopic.php?p=401653#401632](http://www.mqseries.net/phpBB2/viewtopic.php?p=401653#401632) for the detail.

**Comment by chmduquesne** [comment]
FYI, nevermind the encoding. The bug is somewhere else.

**Comment by dsuch** [comment]
Closing - thanks!
