### ISSUE TITLE
Not binary but string message required

### ISSUE THREAD

**Issue by rubenhartenstein** [dsuch/pymqi#290]
Hi,

I implemented the following example coding in our system but did not receive the message as a string but bytes b’…’:
https://dsuch.github.io/pymqi/examples.html --> How to wait for multiple messages

Message content looks like this:
```
b'\xf0@\xf7\xf2\xf7\xf4\xf0\xf6\xf5\xf2\xf8\xf4@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf0\xf6K\xf0\xf5K\xf2\xf0\xf2\xf2@\xf1\xf1z\xf4\xf9z\xf0\xf9z\xf0\xf4@\xf4\xf2\xf5\xf4\xf9@\xd7\xd4\xc4@@\xf4\xf2\xf5\xf4\xf9\xf0\xf0\xf8@\xd9\xf2\xf0\xf5\xf0\xf6@\xe7\xf3\xf7\xf8\xf5\xf6\xf1\xf6\xf0\xf2\xf0\xf0\xf7\xf2\xf7\xf4\xf0\xf6\xf5\xf2\xf8\xf4@@\xf1\xf0\xf0\xf1\xf0\xf7\xf4\xf0\xf3\xf1\xf0@@@@@@@@@@\xf2\xf0\xf2\xf1\xf1\xf1\xf2\xf2\xf2\xf0\xf2\xf1\xf1\xf1\xf2\xf2\xf0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xf7\xc1’
```

What do I have to change in order to get a string message back?
Best regards Ruben

**Comment by rubenhartenstein** [comment]
Solution found: 

import ebcdic
b = b'\xf0@\xf7\xf2\xf7'
print(b.decode('cp1141'))

**Comment by rubenhartenstein** [comment]
Is there also another pymqi internal solution be possible?
What coding would be necessary for it?

**Comment by rubenhartenstein** [comment]
In my git revision history I could see that I also pushed this parameter to git and therefore also made a test with it.
But it did not work out. I still received binary data.

**Comment by JoshMcMQ** [comment]
What is the MQMD.Format of the message.  If this is not MQSTR then convert won't work.

**Comment by rubenhartenstein** [comment]
This is how my coding was:
md = pymqi.MD()
md.Format = pymqi.CMQC.MQFMT_STRING

# Get Message Options
gmo = pymqi.GMO()
gmo.Options = pymqi.CMQC.MQGMO_CONVERT | pymqi.CMQC.MQGMO_WAIT | pymqi.CMQC.MQGMO_FAIL_IF_QUIESCING

Should it work like this?

**Comment by JoshMcMQ** [comment]
Do you both put and get from the queue?   The MQFMT_STRING needs to be set by the app that puts the message.

**Comment by rubenhartenstein** [comment]
No, I am not able to influence the sender side. It is just coming as it is.
But nevertheless I have a running solution with that coding:
import ebcdic
b = b'\xf0@\xf7\xf2\xf7'
print(b.decode('cp1141'))

I will use it this way.

Thank you very much for your support! :-)
