### ISSUE TITLE
Docs Upgrade

### ISSUE THREAD

**Issue by Skyler-Altol** [dsuch/pymqi#297]
Hey guys,

One of the things I was wanting to do a while back was revamp PyMQI's docs. Right now the backend is using Sphinx, which while powerful... is a bit overkill for this library. We can link off to IBM's docs for deeper details, so I'm thinking that revamping the docs page using MkDocs with the google material theme would do wonders for modernising the layout & feel of the site, and while I'm at it I can tidy up some references to old legacy constants in CMQC, and also improve the onboarding process for new developers.

For examples of documentation sites for other well known python packages that use MkDocs with Material, take a look at FastAPI's docs:
https://fastapi.tiangolo.com/

Note how the site is responsive to device sizes and will center the content across all sizes (making viewing on an ultrawide monitor much easier). MkDocs also uses markdown for its backend rather than reST. Markdown is easy to work in syntax wise, so this is another plus. I'm happy to build a fork of the pymqi docs on my own github pages & show what it would look like with MkDocs as the static site generator. Will provide a link once I'm done.

**Comment by Skyler-Altol** [comment]
@SeyfSV can you assign this to me please? :)

**Comment by Skyler-Altol** [comment]
New docs also come with a user configurable dark mode ;) How awesome is this? :D

![image](https://user-images.githubusercontent.com/13567892/170934553-5ea65c39-c374-4c8e-804a-e746d64bffcb.png)

**Comment by Skyler-Altol** [comment]
Okay, I've got a basic look & feel prototype operational: https://skyler-altol.github.io/pymqi/

I haven't configured the theme to use the user's machine config at the moment, so it's just hard coded to use dark mode. But this can be easily done with no real issues, and there's a light mode that is very good as well. I would appreciate some feedback as to whether I should proceed with further time & effort in building this solution :)

**Comment by dsuch** [comment]
Hello @Skyler-Altol,

all of the documentation will be moved to https://zato.io soon - please do not work on this ticket as it will not be included in PyMQI.

Regards.

**Comment by Skyler-Altol** [comment]
That's a shame, because I had plans to uplift the docs and include a proper API reference as part of this work. Oh well.
