### ISSUE TITLE
 `struct.error` while unpacking RFH2 folder length

### ISSUE THREAD

**Issue by phdru** [dsuch/pymqi#3]
Hello! I'm a maintainer of an intranet site that uses IBM MQ. There are a few dozens of installations of the program working for many years. Recently at one of the sites we experienced an error very similar to what is described at https://bugs.launchpad.net/pymqi/+bug/1086354. The patch attached there helped. So I vote to include the patch.

**Comment by dsuch** [comment]
Done in b6e84e7189036988dc066c5f7fca417b9ecc49e3 - thanks @phdru !
