### ISSUE TITLE
Tests for PCFExecute.unpack

### ISSUE THREAD

**Issue by dsuch** [dsuch/pymqi#300]
Hi @SeyfSV,

there are various changes that I plan to make to PyMQI and I am looking at all the code in PCFExecute.unpack right now.

It is a long function with if/else logic and it appears that it could be likely made more dynamic - I would like to simplify it at one point but I would first like to confirm that it is covered by tests that you prepared?

In other words, can I change the internals of this function and keep re-running tests to make sure that the user-visible API is not affected?

Thanks.

**Comment by SeyfSV** [comment]
Hi @dsuch ,
I checked coverage report and found that there are 3 replaces not covered by tests :(
![image](https://user-images.githubusercontent.com/25712100/173186493-1a2547ff-a32f-4a1f-a6b0-9c375251d0df.png)
![image](https://user-images.githubusercontent.com/25712100/173186454-a13177a8-8644-4e86-911b-0bab0664a91d.png)

**Comment by dsuch** [comment]
Sure, thanks.
