### ISSUE TITLE
pymqe.error: MQSCO wrong size. Given: 568, expected 632

### ISSUE THREAD

**Issue by Bernie** [dsuch/pymqi#31]
When attempting to connect to a Channel with SSL, this error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pymqi/**init**.py", line 1357, in connectWithOptions
    rv = pymqe.MQCONNX(name, options, ocd.pack(), user_password, kw['sco'].pack())
pymqe.error: MQSCO wrong size. Given: 568, expected 632

After patching the file pymqi/**init**.py to add the expected padding, all subsequent SSL connection attempts fail with the error:

pymqi.MQMIError: MQI Error. Comp: 2, Reason 2393: FAILED: MQRC_SSL_INITIALIZATION_ERROR

The mqm error logs for these connection attempts say that the failure occurred due to a GSKit return value of 410.

This is with pymqi version 1.5.4.

Could these SSL initialization errors be a result of the SCO object not being properly initialized?

Thanks for any assistance in this matter.

**Comment by paltsevpavel** [comment]
Hi, @Bernie ! Do you solve this trouble? I've the same issue. May be you know how to fix it.

**Comment by Vlado-Vasilev** [comment]
Hello, we had the issue and paddings seems to work. It came to be ,that the certificate create on the server (we had client-server connection) was not complete. It was created with empty CNs.
Creating the cetrtificate with all optional fields populated helped us to solve.

**Comment by Bernie** [comment]
We had solved this issue by adding padding to the message until it was the expected size of 632 bytes.

Good to know the source of the issue is in the certificate, of which the size probably varies depending on the certificate used.  In that case, I suppose the proper fix would be to pad the certificate field to the proper size when it is smaller than expected.

**Comment by dsuch** [comment]
Hello,

this is now fixed - the reason was, as others have said, an incorrect size of MQSCO. It was not updated to be compatible with MQSCO_VERSION_5.

Thanks!

**Comment by angkar** [comment]
Hi

I am using pymqi 1.8.0 with Python 2.7.15 and MQ 7.1 and facing the same issue - how exactly did you change the padding?

Thanks
