### ISSUE TITLE
Channel Table Support

### ISSUE THREAD

**Issue by primetheus** [dsuch/pymqi#34]
We make heavy use of channel tables and it would be very useful to be able to open a connection based on a channel table, rather than specifying an IP and port. If I run mqsc at the CLI I can just specify a Queue Manager and Channel name, and I'd like to be able to do the same with Python

**Comment by primetheus** [comment]
we can use the environment variables

**Comment by dsuch** [comment]
Thanks - but for reference and posterity, can you please clarify by the ability to use environment variables? Are you thinking of any in particular?
