### ISSUE TITLE
Error when installing / compiling pymqi on Windows: MQCSP: illegal use of this type as an expression

### ISSUE THREAD

**Issue by rubinatorz** [dsuch/pymqi#35]
Hi there!

I tried to install PyMQI 1.5.4 on a Windows 2012 R2 environment, with Python 2.7.11 64 bit installed and MQ Client tools 7.5.0.6. But when installing with "pip install pymqi" I get the following errors:

```
Collecting pymqi
  Using cached pymqi-1.5.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): testfixtures in c:\python27\lib\site-packages (from pymqi)
Installing collected packages: pymqi
  Running setup.py install for pymqi: started
    Running setup.py install for pymqi: finished with status 'error'
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\abc\\appdata\\local\\temp\\pip-build-3iyg3c\\pymqi\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\abc\appdata\local\temp\pip-in9d7b-record\install-record.txt --single-version-externally-managed --compile:
    Building PyMQI client 64bits
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\pymqi
    copying pymqi\__init__.py -> build\lib.win-amd64-2.7\pymqi
    copying pymqi\CMQC.py -> build\lib.win-amd64-2.7\pymqi
    copying pymqi\CMQCFC.py -> build\lib.win-amd64-2.7\pymqi
    copying pymqi\CMQXC.py -> build\lib.win-amd64-2.7\pymqi
    copying pymqi\CMQZC.py -> build\lib.win-amd64-2.7\pymqi
    running build_ext
    building 'pymqi.pymqe' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\pymqi
    C:\Users\abc\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPYQMI_SERVERBUILD=0 "-Ic:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include" -Ic:\python27\include -Ic:\python27\PC /Tcpymqi/pymqe.c /Fobuild\temp.win-amd64-2.7\Release\pymqi/pymqe.obj
    pymqe.c
    pymqi/pymqe.c(240) : error C2275: 'MQCSP' : illegal use of this type as an expression
            c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include\cmqc.h(4001) : see declaration of 'MQCSP'
    pymqi/pymqe.c(240) : error C2146: syntax error : missing ';' before identifier 'csp'
    pymqi/pymqe.c(240) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(240) : error C2059: syntax error : '{'
    pymqi/pymqe.c(247) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(247) : error C2224: left of '.AuthenticationType' must have struct/union type
    pymqi/pymqe.c(248) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(248) : error C2224: left of '.CSPUserIdPtr' must have struct/union type
    pymqi/pymqe.c(249) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(249) : error C2224: left of '.CSPUserIdLength' must have struct/union type
    pymqi/pymqe.c(250) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(250) : error C2224: left of '.CSPPasswordPtr' must have struct/union type
    pymqi/pymqe.c(251) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(251) : error C2224: left of '.CSPPasswordLength' must have struct/union type
    pymqi/pymqe.c(256) : error C2065: 'csp' : undeclared identifier
    pymqi/pymqe.c(256) : warning C4133: '=' : incompatible types - from 'int *' to 'PMQCSP'
    error: command 'C:\\Users\\abc\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
```

I try to figure out what's going wrong, I searched on the Internet, I tried to compile the pymqi sources with MSC++4Python compiler, I tried to compile the pymqi sources with MinGW compiler... but all without any success.

In the end I used the pymqi source files and fixed the problem by making some changes to the pymqi/pymqe.c file. The first error in the log above is the "Illegal use of this type as an expression" on line 240. So I moved this declaration line:
`MQCSP csp = {MQCSP_DEFAULT};`
to the beginning of that code block, method pymqe_MQCONNX, right after:
`PyObject* user_password = NULL;`
(line 202/203).

Then I compiled pymqi with just 2 warnings:

```
Building PyMQI client 64bits
running build
running build_py
running build_ext
building 'pymqi.pymqe' extension
C:\Users\admin\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPYQMI_SERVERBUILD=0 "-Ic:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include" -IC:\Python27\include -IC:\Python27\PC /Tcpymqi/pymqe.c /Fobuild\temp.win-amd64-2.7\Release\pymqi/pymqe.obj
pymqe.c
pymqi/pymqe.c(248) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'MQLONG', possible loss of data
pymqi/pymqe.c(250) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'MQLONG', possible loss of data
C:\Users\admin\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64" /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 /LIBPATH:C:\Python27\PC\VS9.0\amd64 mqic.lib /EXPORT:initpymqe build\temp.win-amd64-2.7\Release\pymqi/pymqe.obj /OUT:build\lib.win-amd64-2.7\pymqi\pymqe.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\pymqi\pymqe.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\pymqi\pymqe.pyd.manifest
   Creating library build\temp.win-amd64-2.7\Release\pymqi\pymqe.lib and object build\temp.win-amd64-2.7\Release\pymqi\pymqe.exp
```

I think those 2 warnings exist because I'm running 64 bit Python with 64 bit pymqi, but MQ Client is just 32 bit. So there's a possible loss of data when converting long in 64 bit to long in 32 bit. I fixed those warnings by casting the values:

```
csp.CSPUserIdLength = (int) PyString_Size(user);
csp.CSPPasswordLength = (int) PyString_Size(password);
```

Then I compiled it again and the warnings disappeared. After that a "setup.py install" and the egg file was installed. PyMQI is installed as library, but when importing the library within python code I get:

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymqi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymqi\__init__.py", line 109, in <module>
    import pymqe, CMQC, CMQCFC, CMQXC
ImportError: No module named pymqe
>>>
```

So the pymqe module could not be found. I fixed this with "easy_install pymqi-1.5.4-py2.7-win-amd64.egg".

And now it's all working. But I'm wondering:
- Why is the error on line 240 in de pymqi/pymqe.c file appearing at my environment.
- Why is there a warning on long conversion between 64 and 32 bit. It should fit together though?
- Why do I need to use easy_install the egg file, because the installation instructions on https://pythonhosted.org/pymqi/#download-build-install doesn't mention this.

I hope you could answer my questions, or implement fixes for this problem. Thank you!

**Comment by jairomtzant** [comment]
Many thanks for your second approach @rubenbouman, I can only "fix" the first by myself :)

**Comment by ukrit-himakoon** [comment]
Any updates for this? I still face the same issue here.

**Comment by dsuch** [comment]
Hello @ukrit-himakoon,

unfortunately, I cannot provide community support under Windows, z/OS, HP-UX or in general, non-Linux environments.

I encourage you to contact me on dsuch@zato.io if you would like to arrange a commercial support contract that would cover your Windows-related needs.

Kind regards.

**Comment by yyt030** [comment]
i have the same issue and i change to install version 1.1 exe. file

**Comment by bzd111** [comment]
you can find  a file callec pymqe.pyd in the path \pymqi-1.5.4\build\lib.win-amd64-2.7\pymqi,cope to pymqi folder of pymqi-1.5.4\pymqi

**Comment by vaishnav-piyush** [comment]
Thanks @rubenbouman for very this helpful post. I was able to resolve the issue with `incompatible types - from 'int *' to 'PMQCSP'` with this. I didn't get the warnings which you mentioned so I skipped that part. 
But I still get the error when trying to `import pymqi`.
```
>>> import pymqi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymqi\__init__.py", line 109, in <module>
    import pymqe, CMQC, CMQCFC, CMQXC
ImportError: No module named pymqe
```

This even though I have already run easy_install on the egg file. 

```
>python setup.py easy_install dist\pymqi-1.5.4-py2.7-win32.egg
Building PyMQI client 32bits
running easy_install
Processing pymqi-1.5.4-py2.7-win32.egg
Removing c:\python27\lib\site-packages\pymqi-1.5.4-py2.7-win32.egg
Copying pymqi-1.5.4-py2.7-win32.egg to c:\python27\lib\site-packages
pymqi 1.5.4 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\pymqi-1.5.4-py2.7-win32.egg
Processing dependencies for pymqi==1.5.4
Finished processing dependencies for pymqi==1.5.4
```

**Comment by vaishnav-piyush** [comment]
**Update**
Solved the import issue by copying  pymqe.pyd in the path \pymqi-1.5.4\build\lib.win32-2.7\pymqi, to pymqi-1.5.4\pymqi

**Comment by roy-boy** [comment]
@rubenbouman, thank you so much for this post, I fixed my pymqi ssl mqsco structure size mismatch issue with your workaround, totally rocks! 
I'm using the latest pymqi 1.5.4 with MQ client 7.5 on Windows Python 27 32bit, hope this will help other Python user.

**Comment by JakobRohrhirsch** [comment]
Thanks for the help. This worked for me using MQ client 8.0 on Windows Python 2.7 64 Bit.

**Comment by GoodBoy962** [comment]
After some steps I got such an output:

```
C:\Users\pliskale\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:c:\Program Files (x86)\IBM\WebSphere MQ\to
ols\Lib64" /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 mqic.lib /EXPORT:initpymqe build\temp.win-amd64-2.7\Release\pymqi/pymqe.obj /OUT:build\lib.win-amd64-2.7\pymqi\pymq
e.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\pymqi\pymqe.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\pymqi\pymqe.pyd.manifest
   Creating library build\temp.win-amd64-2.7\Release\pymqi\pymqe.lib and object build\temp.win-amd64-2.7\Release\pymqi\pymqe.exp
pymqe.obj : error LNK2019: unresolved external symbol __imp_free referenced in function pymqe_MQGET
pymqe.obj : error LNK2019: unresolved external symbol __imp_malloc referenced in function pymqe_MQGET
pymqe.obj : error LNK2019: unresolved external symbol memset referenced in function pymqe_MQINQ
pymqe.obj : error LNK2019: unresolved external symbol __imp_strncpy referenced in function pymqe_MQSET
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
build\lib.win-amd64-2.7\pymqi\pymqe.pyd : fatal error LNK1120: 5 unresolved externals
error: command 'C:\\Users\\pliskale\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120
```

How can I fix it?

**Comment by pkaczynski** [comment]
I just did a clean install of recent (1.6.0) pymqi and MQ 8.0 with official VC++ for python 2.7 compiler. It works if you make a change in pymqe.c (line 240 -> 203) and then set PATH to '%PROGRAMFILES%\IBM\WebSphere MQ\Tools\Lib64'.

@dsuch can you change `pymqe.c` to comply to C standards (i.e. declarations on the beginning of the block)?

**Comment by dsuch** [comment]
> @dsuch can you change pymqe.c to comply to C standards (i.e. declarations on the beginning of the block)?

Done in PR https://github.com/dsuch/pymqi/pull/36 and merged in.

**Comment by JoshMcMQ** [comment]
@dsuch looks like this one is resolved, is there a reason to leave it open?

**Comment by dsuch** [comment]
Thanks @JoshMcMQ - I am closing the ticket.

**Comment by toppgun** [comment]
@dsuch @rubinatorz 
i have latest python 3.8 on linux and IBM 7.5
i have installed pymqi-1.9.3 
i have the libraries as below files in directory /python/lib/python3.8/site-packages/pymqi-1.9.3-py3.8-linux-x86_64.egg/pymqi>
CMQC.py
CMQZC.py
CMQXC.py
CMQCFC.py
__init__.py
pymqe.py
pymqe.cpython-38-x86_64-linux-gnu.so
__pycache__

however, i get the below error when i use import pymqi in python

Traceback (most recent call last):
  File "/python/lib/python3.8/site-packages/pymqi-1.9.3-py3.8-linux-x86_64.egg/pymqi/__init__.py", line 110, in <module>
    from . import pymqe
ImportError: libmqic_r.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "abc_mq.py", line 2, in <module>
    import pymqi
  File "/python/lib/python3.8/site-packages/pymqi-1.9.3-py3.8-linux-x86_64.egg/pymqi/__init__.py", line 112, in <module>
    import pymqe  # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'


Any pointer will be really helpful
