### ISSUE TITLE
Client to download

### ISSUE THREAD

**Issue by onlygecko** [dsuch/pymqi#37]
Hi,

on Your documentation page it say:

```PyMQI does not replace MQI, but is layered on top of it, so you must have MQ (either client or server) installed before you can use PyMQI.```

Can You tell me, where I can find the (official) Client from IBM?

Thanks,
Peter

**Comment by dsuch** [comment]
It would be here:

https://www.ibm.com/software/integration/wmq/clients/ 

Regards.

**Comment by onlygecko** [comment]
Wow. This was unbelievable quick. :-)

I've found this website before. My mistake was that I got confused by the download size of '111 Bytes' and the forward to the 'fix central' page.

For every one else:
* Follow the link from dsuch.
* Choose the MQ Version
* Choose the minor/bugfix - Version (Ignore the 111 Byte size information)
* Choose your OS (on the 'fix central' website)
* Enter IBM login details
* Download ...
