### ISSUE TITLE
Connecting to MQ as another user

### ISSUE THREAD

**Issue by Ron4326** [dsuch/pymqi#39]
Hi,

My issue is similar to https://answers.launchpad.net/pymqi/+question/180965.
I login to my system as user 'tron'. I need to connect to a queue manager on a different IP.
When I try to connect, I get this error message. "MQI Error. Comp: 2, Reason 2035: FAILED: MQRC_NOT_AUTHORIZED" on line "qmgr = pymqi.connect(queue_manager, channel, conn_info)"

When I check the logs, I can see that the user "tron" is attempting to connect to queue manager but fails as this user doesn't have the required permission.

Sample Code I used : 
`queue_manager = "Test"
channel = "TEST.CHANNEL"
host = "xxxx-xxxx"
port = "1458"
conn_info = "%s(%s)" % (host2, port)
user = 'mgm_test'
password = 'mgm_test1234'

qmgr = pymqi.connect(queue_manager, channel, conn_info, user, password)
`

"tron" is the user id that the eclipse is running under. (I'm using PyDev in Eclipse to run Python program). I can add tron to the queue manager authority records and the set up works. But I would like to connect to the queue manager with the value of user and password that I am having in my program. This user mgm_test is present in the qmgr auth records. 

So, is there a way now to connect to queue manager as different user ?
From the link, I gave above, it is mentioned that there is no option from PyMQI as of 2013, so would like to know, if there is any progress in 2016 ?

Thanks,
Ron

**Comment by dsuch** [comment]
Hello @Ron4326,

the thing really is that PyMQI is a wrapper around IBM's proprietary C libraries - this is not an open protocol and we cannot implement anything ourselves in Python unless the C libraries support it.

Can you please open a PMR with IBM and ask them how to achieve what you need in C? Then we will see how to translate it into PyMQI calls, if possible at all.

Thanks!

**Comment by Ron4326** [comment]
Hi @dsuch, 
That issue got solved (connecting to queue manager) when I gave permission to the user which runs the program. Strange that IBM doesn't provide implementation in C for it. Sorry, I won't be able to raise a PMR as I require permission in the organization I work.

**Comment by dsuch** [comment]
Sure, no worries, I'm glad you have it working now!
