### ISSUE TITLE
connectWithOptions does not accept user and password in new style args

### ISSUE THREAD

**Issue by yurist** [dsuch/pymqi#41]
This invocation fails with 'Invalid option':
qmgr.connect_with_options('', cd = cd, user = 'john', password = 'doe')

This invocation succeeds:
qmgr.connect_with_options('', cd, user = 'john', password = 'doe')

See https://github.com/dsuch/pymqi/blob/096058dbbb56c8d5a5ed6693aca5ae33bdea4aa3/code/pymqi/__init__.py#L1331
The list needs to be extended with 'user' and 'password'.

**Comment by SeyfSV** [comment]
Now it looks like
```
            if len_args > 2:
                raise TypeError('Invalid options: %s' % args)
```
