### ISSUE TITLE
PYMQI Error: RFH2 - XML Folder not well formed.

### ISSUE THREAD

**Issue by ionutvilie** [dsuch/pymqi#43]
Hello,

I have the bellow piece of code that i made from examples found on ibm and here.
I want to parse the RFH2 and extract some elements in order build a report with backed out messages.

the code works fine except that from time to time apparently some messages are generated that have "no body" :), when i get:
"pymqi.PYIFError: PYMQI Error: RFH2 - XML Folder not well formed. Exception: unbound prefix: line 1, column 24"

The header, i am pretty sure is well formated as it passes to a flow (Broker) that routes the message based on the information from the header. What i suspect is that because it has no data in the body the header is not interpreted correctly by pymqi.

questions:
- Do someone has any idea how i could bypass this and extract the data from the header because i can try catch the error but then the code does not serve the scope. 
- in order to extract the xml elements i pass the usr header to  xml.minidom and extract them. is there a better way like for example ESQL where you can easy extract them ? 

PS: i am not an IBM developer. (broker, integration bus etc), just app admin :)

```python
import pymqi
import time

start_time = time.time()

qmgr = pymqi.connect('QMC03', 'APP1.SVRCONN', 'localhost(1414)')
qName = 'foo.bar.to_app.error'

queue = pymqi.Queue(qmgr, qName)
qDepth = queue.inquire(pymqi.CMQC.MQIA_CURRENT_Q_DEPTH)
queue.close()
print 'Current depth: %d' % qDepth

queue = pymqi.Queue(qmgr, qName, pymqi.CMQC.MQOO_BROWSE)
msgDesc = pymqi.MD()
getOpts = pymqi.gmo(Options=pymqi.CMQC.MQGMO_BROWSE_NEXT)
getOpts.WaitInterval = pymqi.CMQC.MQWI_UNLIMITED

messages = []
rfh2 = []

seq = 0

try:
    while 1:
        # message = queue.get(None, msgDesc, getOpts)
        message = queue.get_rfh2(None, msgDesc, getOpts, rfh2)
        # messages.append(message)
        # print msgDesc
        # print rfh2[seq]
        print rfh2[seq]['usr'].replace('\n', '')
        print message
        # null MsgId and CorrelId, or cursor won't move up
        # the Q
        msgDesc['MsgId'] = ''
        msgDesc['CorrelId'] = ''
        seq += 1
except pymqi.MQMIError, me:
    # assume that error is raised when there are
    # no more messages in queue
    pass

queue.close()
qmgr.disconnect()
print("--- %s seconds ---" % (time.time() - start_time))

```

**Comment by dsuch** [comment]
Hi @ionutvilie,

can you please tell me what the full exception and data that cannot be parsed are? The fact that WMB can parse doesn't mean that it's well-formed XML.

Also, do not assume that an MQMIError will always mean that there are no more messages, there could be many reasons for exceptions and the way you have it now, with a bare 'pass' means that you don't know really what is going on, you need to catch the exception and look up the actual reason code and only then act accordingly.

Regards.

**Comment by ionutvilie** [comment]
Hi @dsuch,

Thanks for the reply.

The "assume" statement it is not written by me it is copy/pasted from here (browse.py): 
http://www.ibm.com/developerworks/websphere/library/techarticles/0708_salkosuo/0708_salkosuo.html 

The idea was to compare the number of the messages with the position of the cursor resulting 3 posible outcomes. one is perfect(eq), one is acceptable (gt) and not good(lt).

i tried catching it but the cursor does not move up using get_rfh2() so i ended up  using get() and then the dumb idea was to slice the message and extract the <usr> but it is way slower (as expected), `message = queue.get(None, msgDesc, getOpts)`

below is the full error: i can send you the messages, if is ok on the zato mail, there is nothing secret as they don't have any data. You will have to use qload to restore them though. 


```/usr/bin/python2.7 /home/ionut/PycharmProjects/ibmmq/main.py
Current depth: 158
Traceback (most recent call last):
  File "/home/ionut/PycharmProjects/ibmmq/main.py", line 44, in <module>
    message = queue.get_rfh2(None, msgDesc, getOpts, rfh2)
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 1781, in get_rfh2
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 728, in unpack
pymqi.PYIFError: PYMQI Error: RFH2 - XML Folder not well formed. Exception: unbound prefix: line 1, column 24

Process finished with exit code 1``` 

PS: i run the code without the try statement.

**Comment by dsuch** [comment]
Can you add a ```print(folder_data)``` statement to line 723, right after the 'try' statement? I'd like to see what is that cannot be parsed.

**Comment by ionutvilie** [comment]
```
/usr/bin/python2.7 /home/ionut/PycharmProjects/ibmmq/main.py
Current depth: 158
<mcd><Msd>jms_text</Msd><msgbody xsi:nil="true"></msgbody></mcd>
Traceback (most recent call last):
  File "/home/ionut/PycharmProjects/ibmmq/main.py", line 44, in <module>
    message = queue.get_rfh2(None, msgDesc, getOpts, rfh2)
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 1782, in get_rfh2
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 729, in unpack
pymqi.PYIFError: PYMQI Error: RFH2 - XML Folder not well formed. Exception: unbound prefix: line 1, column 24

Process finished with exit code 1
```

**Comment by dsuch** [comment]
Thanks @ionutvilie - I will be closing the ticket now.
