### ISSUE TITLE
RFH Header on Subscription

### ISSUE THREAD

**Issue by drychlik76** [dsuch/pymqi#44]
Hello,
I have successfully implemented a listener that subscribes to a JMS topic and am able to get the JMS message.  At the top of these messages, that amount to an XML file, is a RFH header of which I am having trouble finding the appropriate way to unpack these and discard them.  I am really just interested in the XML data so I can process the message using common XML libraries.  

The problem I see is that on the Subscription class no method exists for unpacking these or getting them like it does on a queue.
`
sub = pymqi.Subscription(qmgr)
data = sub.get(None, pymqi.md(), get_opts)
`
It appears that I can do this on a queue but not a subscription.
pymqi.Queue.get_rfh2([maxLength[, mDesc, getOpts[, rfh2_header_1]]])

I need to be honest and say this is my first time working with an IBM JMS service like this.  It's been Web services, and REST up to this point.  Any direction or help would be sincerely appreciated.  Thank you.

**Comment by dsuch** [comment]
Unless you are keen to understand the underlying network-level format, you will be likely much better off using Spring Python's pure-Python WebSphere MQ JMS implementation as found here http://docs.spring.io/spring-python/1.2.x/sphinx/html/jms.html

A few notes:

* Source code is at https://github.com/dsuch/spring-python
* Spring Python as such is a discontinued project but it still lingers on PyPI
* Some time down in 2017 it will become one of core Zato repositories https://github.com/zatosource/
* [Zato](https://zato.io/docs) itself uses is to implement WMQ JMS in Python so it's guaranteed that the JMS library will live on

**Comment by drychlik76** [comment]
Interesting for sure, I will check it out if I have no other option.  I hate to abandon this when it's almost done.  I just need to get past this RFH header issue.

I found this PSPROP that I could set to None that might work.  According to the documentation I could set that None and it appears that the properties would not be included.  Where would I set this property to None using the pymqi library?  I am assuming its on the Subscription class.

**Comment by dsuch** [comment]
I'm sorry but I cannot really assist you much in it beyond suggesting to have a look at the [MQRFH2JMS](https://github.com/dsuch/spring-python/blob/master/src/springpython/jms/factory.py#L614) which implements JMS as returned on wire by WebSphere MQ. I just haven't worked with it for at least 5 years.

But the MQRFH2JMS class should be of help, for instance the build_folders_and_payload_from_message method parses MQRFH2 into Python structures so this could be a good starting point.

Another point is, JMS producers configured through JNDI and .bindings files do not necessarily have to produce MQRFH2 headers even though JMS is used by programmers. I don't know if this is something that you can influence and the exact option in .bindings escapes me at the moment but it could be something worth considering.

**Comment by drychlik76** [comment]
Understood.  So the spring python library handles this lower level networking stuff for me?  Meaning, I dont have to worry about the RFH headers and I can just get the XML data on a Subscription to a topic?

**Comment by dsuch** [comment]
Hm, actually, now that I have looked at it again - no, it won't work with subscriptions at all. My apologies for the confusion but evidently I have not worked with this code for 5-7 years according to the commit log.

Spring Python will work only with queues, not with subscriptions. It's compatible with JMS but with regards to queues only, it doesn't handle subscriptions.

So in the end, if I were you, I would still you the code that you had, but I would have a look at MQRFH2JMS to see how MQRFH2 headers can be parsed and useful data extracted out of it.

**Comment by drychlik76** [comment]
@dsuch Thank you kindly for your help with this and pointing me in a general direction.

**Comment by dsuch** [comment]
Closing.

**Comment by toppgun** [comment]
I know this thread is closed but my issue looks related and is pressing :)

I am trying to send a message to IBM MQ via my python script (i am using pymqi) 
I am able to put the message to the relevant queue, but the queue is not accepting the message, it always remains in the queue when i browse using MQ explorer.
However, when i manually put the message providing the JMSType as <specifictype>, it is accepted.

This JMSType property is seen as  mcd.Type in the MQ explorer.

So, i suppose i need to set this property in my python script using MQ headers. correct me if i am wrong.
Any ideas on how i do that? can i do it using mqrfh2 ?
any pointer will be really helpful.

**Comment by SeyfSV** [comment]
What is "accepting"?

**Comment by toppgun** [comment]
my apologies, i wanted to say that the reader of the queue is not "accepting" the message without this header.

**Comment by SeyfSV** [comment]
What language does reader is? Is it Java application?
Sorry, I think it is not pymqi issue :)

PS
Try to ask your question on stackoverflow.com. I think it better suited for this and there are more guys on it, who can help you.

**Comment by toppgun** [comment]
Yes reader is a java application.
i agree it is not pymqi issue.

It has to do with header part to be sent along with the message to the Ibm Mq

**Comment by SeyfSV** [comment]
Take a look on your receiver. I think it filters messages by some conditions. If it is true and you can't fix that, then you should change your message, maybe set mcd.Type, as you wrote.
