### ISSUE TITLE
MessageHandle object crashes with wrong buffer size on 64bit Solaris systems

### ISSUE THREAD

**Issue by koushikt** [dsuch/pymqi#45]
MessageHandle object crashes with wrong buffer size on 64bit solaris systems. 
PyArg_ParseTuple's s# should return a int but its getting captured as a &long. This could have undefined behavior based on architecture.

**Comment by dsuch** [comment]
Thanks @koushikt - are you able to share more details? Where in the code it is? Which PyArg_ParseTuple?

**Comment by koushikt** [comment]
Hi,
In pymqe.c in function pymqe_MQCRTMH and in function MQSETMP; the
buffer_length variables are declared as long instead of int. It is passed
as a pointer to the function PyArg_ParseTuple which expects an int* not a
long*.
On 64 bit machines int* is not long*. This causes segfaults if you are
lucky or unexpected output if unlucky.

I also spotted another error. in __init__.py you use 0L as the default
value for Class pmo's PubLevel. But according to
https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.0.1/com.ibm.mq.csqzak.doc/fr14190_.htm
it should be set as 9L.

Thanks

Koushik Thiagarajan

**Comment by koushikt** [comment]
were you able to reproduce it?

Koushik Thiagarajan

**Comment by dsuch** [comment]
Hello @koushikt - I don't have any MQ instance handy and I don't work on PyMQI on a regular basis. It's likely at least several weeks or more until I will be able to have a closer look.

I thank you for the suggestions and I will make sure they get incorporated.

**Comment by SeyfSV** [comment]
Now all `buffer_length` variables have `Py_ssize_t` type and, I hope, this fix issue
