### ISSUE TITLE
Message Selectors

### ISSUE THREAD

**Issue by drychlik76** [dsuch/pymqi#48]
Hello,

I have a current running adapter using pymqi  that utilizes a subscription queue.  It's been doing fine however I have been tasked with using a message selector or a Filter to tell the subscription to filter the messages.  I have the filter string that I need to use, I am just not sure where to set it up in the implementation.  I see the Filter class, however I don't see where to use it in and not sure where to pass an instance of filter.  Do I pass it to the QueueManager, or setup it up in the SD() class?

This is what I am using to attempt to resolve it.
pymqi._Filter('my_selector', 'my_value', 'equal')

Any help would be sincerely appreciated.

**Comment by drychlik76** [comment]
After some digging more this is what I came up with.  I don't know if it's correct.
`import pymqi

sub_desc = pymqi.SD()
sub_desc["SubLevel"] = 1  # Import bug fix here
sub_desc["Options"] = pymqi.CMQC.MQSO_CREATE + pymqi.CMQC.MQSO_RESUME + pymqi.CMQC.MQSO_DURABLE + \
                      pymqi.CMQC.MQSO_MANAGED
sub_desc["SelectionStringVSPtr"] = 1

sub_desc.set_vs("SubName", "subscription name")
sub_desc.set_vs("ObjectString", "topic")
sub_desc.set_vs("SelectionString", "msg_src = 'I'")

print (sub_desc)`

**Comment by dsuch** [comment]
Thanks @drychlik76 - with your permission, I will be closing the ticket.
