### ISSUE TITLE
Connect in client mode without Queue Manager Name

### ISSUE THREAD

**Issue by kalyanpursunil85** [dsuch/pymqi#50]
Hello,

I'm using PyMQI (1.5.4) module to connect to IBM MQ in client mode. I would like to connect to queue without specifying the Queue Manager Name. 
Below is the test script i'm using to verify the connectivity.

```
import pymqi

queue_manager = ''
channel = "CHANNEL_NAME"
host = "HOST_IP"
port = "4060"
conn_info = "%s(%s)" % (host, port)
queue_name = "QUEUE NAME"

qmgr = pymqi.connect(queue_manager=queue_manager, channel=channel, conn_info=conn_info)
queue = pymqi.Queue(qmgr, queue_name)
message = queue.get()
print message
queue.close()
qmgr.disconnect()
```
I'm unable to connect to the queue. I get an error saying that queue is `None`. 
```
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    message = queue.get()
  File "/usr/local/lib64/python2.7/site-packages/pymqi/__init__.py", line 1717, in get
    self.__realOpen()
  File "/usr/local/lib64/python2.7/site-packages/pymqi/__init__.py", line 1551, in __realOpen
    rv = pymqe.MQOPEN(self.__qMgr.getHandle(),
AttributeError: 'NoneType' object has no attribute 'getHandle'
```
Any pointers on how to connect to queue without using Queue Manager Name would be helpful.

Thank you,
Sunil

**Comment by dsuch** [comment]
Hi @kalyanpursunil85,

can you please paste in the full error message?

Thanks.

**Comment by kalyanpursunil85** [comment]
@dsuch Updated my previous comment with the error traceback. Thank you!

**Comment by dsuch** [comment]
That 'qmgr' object, the one returned by 'qmgr = pymqi.connect(...)' - is that None? Can you confirm which path in pymqi.connect is used and what is returned?

**Comment by kalyanpursunil85** [comment]
@dsuch Yes, `qmgr` is None
`qmgr = pymqi.connect(queue_manager=queue_manager,channel=channel, conn_info=conn_info)
`

**Comment by shashankarao** [comment]
@dsuch Any updates on this thread? I am facing the same issue when I don't specify a Queue manager.`pymqi.connect(..)` returns `None` in my case too.

**Comment by dsuch** [comment]
Hello,

I cannot promise but it's possible that I will be able to look into it on Friday or the next week.

If this is an important matter, feel free to contact me on dsuch@zato.io to discuss a commercial support contract under which this will be given priority.

Regards.

**Comment by shashankarao** [comment]
@dsuch At this point in time, I am ok with a friday or next week being the timeline. I am still looking at various options currently. It is good to know that you have a commercial support. I will keep this in mind and see if this is something that we want in the future.
Thanks!

**Comment by sunilkalyanpur** [comment]
@dsuch Curious to know if you have an update on above issue

**Comment by dsuch** [comment]
Hello everyone,

I have had to focus on projects that are not related to MQ in the past few weeks but I'm back to an MQ-based project now so I should be able to come up with an answer to the question from this ticket.

Thanks for your understanding.

**Comment by shashankarao** [comment]
Thank you @dsuch! Looking forward for a resolution.

**Comment by dsuch** [comment]
Hello,

this is just to let you know that I'm still not in any project with MQ and did not have time to work on this ticket. I remember about it and will look into it as soon as I can.

**Comment by dsuch** [comment]
Done in PyMQI 1.7.0 - thanks everyone!
