### ISSUE TITLE
Auto-Reconnect?

### ISSUE THREAD

**Issue by smuribi** [dsuch/pymqi#55]
Is the Client Auto-Reconnect exposed in Pymqi?

connect_options = pymqi.CMQC.MQCNO_RECONNECT

**Comment by chughts** [comment]
Could this be fixed / supported by adding the following into CMQC.py ?

```python
MQCNO_RECONNECT_AS_DEF     = 0x00000000
MQCNO_RECONNECT                    = 0x01000000
MQCNO_RECONNECT_DISABLED =  0x02000000
MQCNO_RECONNECT_Q_MGR      =  0x04000000
```

**Comment by dsuch** [comment]
Hi @chughts - if it is not in CMQC.py, please feel free to send in a PR and I will merge it. Thanks.

**Comment by chughts** [comment]
OK, we will most likely roll these updates into #116

**Comment by JoshMcMQ** [comment]
@chughts this can be closed right?

**Comment by chughts** [comment]
@JoshMcMQ I think so, but as I didn't raise it in the first place I can't close it.
