### ISSUE TITLE
MQ Constants not updated in CMQC.py

### ISSUE THREAD

**Issue by avictor0826** [dsuch/pymqi#56]
when trying to build a API for MQ for automation of MQ activities, i found out that there are few MQ Constants missing in the CMQC.py
Have uploaded a few of them.
[missing CMQC.txt](https://github.com/dsuch/pymqi/files/1545360/missing.CMQC.txt)

Since MQ Constants are updated for each version, why dont we write a module to build CMQC.py from the cmqc.h dynamically.

**Comment by dsuch** [comment]
Hello @avictor0826, the constants are re-read periodically using [h2py](https://github.com/python/cpython/blob/master/Tools/scripts/h2py.py) - if you would like to send in a PR with newest values, I will be happy to merge it.

Thanks.

**Comment by SeyfSV** [comment]
Done in 01fb071c3ea8a1d194d5d0f0901b66b19aaca696
