### ISSUE TITLE
Several tests seemed to be broken due to PCFExecute calls referring to variables in the wrong module

### ISSUE THREAD

**Issue by henry-tay** [dsuch/pymqi#57]
I've noticed that some tests are failing due to PCFExecute calls that refer to methods defined in CMQCFC.py. It looks like this recent change might have broken these tests.

https://github.com/dsuch/pymqi/commit/4cef3b494a7174f4436972ffb24455ca20bb5752

An example of a failing test is test_pubsub_api_managed_durable (test_pubsub.TestPubSub) which fails with the error message 

`Traceback (most recent call last):
  File "/home/.../pymqi/code/tests/test_pubsub.py", line 72, in tearDown
    self.delete_sub(sub_desc)
  File "/home/.../pymqi/code/tests/test_pubsub.py", line 58, in delete_sub
    pcf.MQCMD_DELETE_SUBSCRIPTION(args)
  File "/home/.../pymqi/code/pymqi/__init__.py", line 2391, in __call__
    rv = pymqe.mqaiExecute(qmHandle, CMQC.__dict__[self.__name], *args)
KeyError: 'MQCMD_DELETE_SUBSCRIPTION'`

`MQCMD_DELETE_SUBSCRIPTION` is defined in `CMQCFC.py` and `cmqcfc.h` and not in `CMQC.py`.

**Comment by SeyfSV** [comment]
All tests pass successfully
