### ISSUE TITLE
class QueueManger: disconnect() BUG

### ISSUE THREAD

**Issue by SickAustrian** [dsuch/pymqi#62]
Hey,

I believe to have found a bug in the `disconnect()` method as part of the `QueueManger` class:
```
def disconnect(self):
        """disconnect()
        Disconnect from queue manager, if connected."""

        if self.__handle:
            rv = pymqe.MQDISC(self.__handle)
        else:
            raise PYIFError('not connected')
```

More specifically, the `disconnect` fails to reset the `self.__handle` properly. Currently, you can make consecutive `disconnect()` calls without getting a `raise PYIFError('not connected')` exception. It is hence tricky to verify whether a `QueueManger` object has successfully disconnected or not.

I would really appreciate if you could have a look at this.

Many thanks in advance!

**Comment by dsuch** [comment]
Hello @SickAustrian,

I understand what you are saying and such a cleanup procedure could be added but let me also add that a related caveat is that the only way to make sure if you are still connected to a queue manager is to issue an API call and catch an exception if you are not.

This is what MQ itself has been requiring and recommending for as long as it existed, i.e. there is no other way to be sure if the remote end is still there.

I understand that this is a twofold situation what you are describing and again, cleaning up internal PyMQI variables after .disconnect could be arranged. But looking at it from a broader perspective - if you want to be sure if you are connected or not, you need to issue some call, such as ping.

I understand that your case is a bit different - you want to be sure that you did disconnect, but I'm adding this information for completeness.

As for the changes to .disconnect - can you propose what can be done and send a PR?

Thanks.

**Comment by SickAustrian** [comment]
Hey @dsuch,

Thank you for your quick reply!

I agree that the an additional API should be made to the MQ queue manger to see if it is indeed disconnected. I am not arguing with that.

All I am proposing is a cleanup procedure for the disconnect method since its leaving the `QueueManger` object in an invalid state.

Yes I can propose a solution and send a PR. I cant promise though when this will be done as I am currently quite busy with work.

**Comment by dsuch** [comment]
PR #63 was merged, thanks again @SickAustrian!
