### ISSUE TITLE
Error running pymqi in ubuntu

### ISSUE THREAD

**Issue by Pzixel** [dsuch/pymqi#65]
I'm trying to run a simple queue listener on ubuntu, written in python.

I have ran following commands:

```bash
sudo apt install alien
mkdir /tmp/mqclient
curl http://... --output /tmp/mqclient/mqc.tar.gz
cd /tmp/mqclient
tar zxvf mqc.tar.gz
sudo adduser mqm
sudo usermod -m -d /var/mqm mqm
sudo ./mqlicense.sh 
sudo alien --scripts --to-deb MQSeriesRuntime-9.0.0-3.x86_64.rpm
sudo alien --scripts --to-deb MQSeriesClient-9.0.0-3.x86_64.rpm
sudo alien --scripts --to-deb MQSeriesSDK-9.0.0-3.x86_64.rpm
sudo dpkg -i mqseriesruntime_9.0.0-4_amd64.deb
sudo dpkg -i mqseriesclient_9.0.0-4_amd64.deb
sudo dpkg -i mqseriessdk_9.0.0-4_amd64.deb
sudo apt-get install python-pip python-dev build-essential
sudo pip install --upgrade pip  
sudo pip install mymqi  
echo "#!/usr/bin/env python

import pymqi

queue_manager = 'QM01'
channel = 'SVRCONN.1'
host = '192.168.1.135'
port = '1434'
queue_name = 'TEST.1'
message = 'Hello from Python!'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info)

queue = pymqi.Queue(qmgr, queue_name)
queue.put(message)
queue.close()

qmgr.disconnect()" > run.py
chmod +x ./run.py
./run.py
```

And then I faced an error:

> ubuntu@ip-111-11-110-5:/tmp/mqclient$ ./run.py
> Traceback (most recent call last):
>   File "./run.py", line 3, in <module>
>     import pymqi
>   File "/usr/local/lib/python2.7/dist-packages/pymqi/__init__.py", line 109, in <module>
>     import pymqe
> ImportError: libmqic_r.so: cannot open shared object file: No such file or directory
> 

I just followed the guide but it doesn't work.

When I run `install pip` yet another time it gives me:

> $ sudo pip install mymqi
> The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting mymqi
>   Could not find a version that satisfies the requirement mymqi (from versions: )
> No matching distribution found for mymqi

**Comment by dsuch** [comment]
Hello, can you tell me what the guide that you are following is?

**Comment by Pzixel** [comment]
@dsuch I'm talking about the [main page](https://github.com/dsuch/pymqi) with variations taken [from SO](https://stackoverflow.com/a/16947334/2559709) to make it work on ubuntu.

**Comment by dsuch** [comment]
I understand that you don't execute the commands as user 'mqm' and this is the issue - you need to. 

Alternatively, if you would like to run it all as another user, you need to make the .so library available for your other user - please look it up on the web, this is not something specific to PyMQI or WebSphere MQ.

The keywords that you need are "python" "cannot open shared object file: No such file or directory".

**Comment by Pzixel** [comment]
You are right!
```sh
$ sudo find . -type f -name "libmqic_r.so"
./opt/mqm/lib64/libmqic_r.so
./opt/mqm/lib/libmqic_r.so
```

Sorry for bothering, it seems that it actually used this user somehow' I expected I just created him, but I accedentaly used it to install items there.

**Comment by Pzixel** [comment]
I understand that it may be generic Python question and you don't have to answer it. If you think it's won't be healthy for the repo to answer this question (i.e. write exact steps that allow to completely configure pymqi on a clean ubuntu VM) then I just close it and going to ask my question somewhere else. I just thought that it's tied and would be helpful for everyone.

**Comment by Pzixel** [comment]
Well, I have ran:
```
sudo cp -r /opt/mqm/lib64/* /usr/local/lib/
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ldconfig
```
And now it seems to be doing the trick. Thank you.

**Comment by dsuch** [comment]
I realize that it is helpful for everyone using the library and it's not about not willing to assist you - I am simply tied up at work and don't have means to set up an environment from scratch and write it all down step by step including the commands for shared libraries.

**Comment by Pzixel** [comment]
I checked the documentation and it says that it signals that something is wrong on client side.

Beside that, I have written a working C# code that actually is able to connect to the server:

```cs
MQEnvironment.UserId = userName;
MQEnvironment.Password = password;

var manager = new MQQueueManager(queueManagerName, channelName, connName);
```

**Comment by Pzixel** [comment]
I was able to read my queue! Thank you for your advices.

I may provide a script that does all required work, if you wish.

**Comment by dsuch** [comment]
It's nice to hear it and naturally, feel free to share the result for other people's benefit!

**Comment by Pzixel** [comment]
Well, I've ended up with following script:

```bash
#!/bin/bash

LDPATH='/opt/mqm/lib64' # remove '64' prefix for 32bit system
WEBSPHERETARGZURL=$1

if [[ -z $WEBSPHERETARGZURL ]];
then
    echo `date`" - Missing mandatory argument WEBSPHERETARGZURL. "
    exit 1
fi

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

apt install curl python-pip rpm
mkdir mqclient
cd mqclient
curl "$WEBSPHERETARGZURL" -o mqc.tar.gz
tar zxvf mqc.tar.gz
./mqlicense.sh -accept
rpm -ivh --nodeps --force-debian MQSeriesRuntime-*.rpm 
rpm -ivh --nodeps --force-debian MQSeriesClient-*.rpm 
rpm -ivh --nodeps --force-debian MQSeriesSDK-*.rpm
rpm -ivh --nodeps --force-debian MQSeriesSamples-*.rpm 
 
pip install pymqi

echo $LDPATH > /etc/ld.so.conf.d/mqm.conf
ldconfig
```

which should be run in following manner

```bash
sudo ./install_websphere.sh "https://delivery04.dhe.ibm.com/sdfdl/v2/sar/CM/WS/07fr8/0/Xa.2/Xb.jusyLTSp44S0edhHTSqiGoXJnAaz1lT3SSosEqLUsjtB27-sofaqKKK6MeY/Xc.CM/WS/07fr8/0/9.0.0.3-IBM-MQC-LinuxX64.tar.gz/Xd./Xf.LPR.D1VK/Xg.9660130/Xi.habanero/XY.habanero/XZ.NdDSMAceuGC1hexQs1nyOGCrxOY/9.0.0.3-IBM-MQC-LinuxX64.tar.gz"
```

Make sure that URL ends with `IBM-MQC-LinuxX64.tar.gz` otherwise script won't work (for example, in case of  `IBM-MQ-LinuxX64.tar.gz`)

for 32bit systems first line should be modified as `LDPATH='/opt/mqm/lib'`.

It seems to be working. I will try it yet another time on a clean machine.

**Comment by JoshMcMQ** [comment]
@Pzixel from what you wrote it sounds like you did make the MQ installation the Primary installation.

Prior to MQ v7.1 you could only have single install of MQ on the server and MQ would always create symlinks from /usr/bin to /opt/mqm/bin and from /usr/lib to /opt/mqm/lib.  From 7.1 and later (currently 9.0 is latest) you have the potential to install multiple version on the system and because of this those previously created symlinks are not set by default.

To view a list of installations on the server run this command:

    dspmqver -i

You have the option of designating one install as the primary install on a server and by doing this those symlinks are created.  To set a primary installation you can run the following command as root:

    /opt/mqm/bin/setmqinst -p /opt/mqm -i

But as you are using 64 python this would not help you find the /opt/mqm/lib64 libraries, for this you can run the following command, note the "dot space" at the start of the command to source the profile.  This sets the LD_LIBRARY_PATH along with other MQ specific ENV variables.

    . /opt/mqm/bin/setmqenv -s -x 64 -l
