### ISSUE TITLE
Message with CorrelationId .

### ISSUE THREAD

**Issue by omagdy** [dsuch/pymqi#66]
When trying to send and receive messages using a correlation id, I encounter a problem.
Either the sent correlation id not being integer:

    put_mqmd = pymqi.MD()
    put_mqmd["MsgType"] = pymqi.CMQC.MQMT_REQUEST ----> Must be integer to send successfully

Or the expected correlation id not being string:

    get_mqmd = pymqi.MD()
    get_mqmd["CorrelId"] = str(put_mqmd["MsgId"])  ----> Must be string 

Naturally when I leave them both as intended, the client is unable to find the message in the queue as its expected correlation id is string while the one sent is integer. Am I missing something ? I used code similar to the one in the examples [page](https://dsuch.github.io/pymqi/examples.html).

**Comment by dsuch** [comment]
Hello @omagdy,

I'm not sure I understand it - you are setting MsgType in the former case and CorrelId in the latter one, both to MQMT_REQUST?

Regards.

**Comment by omagdy** [comment]
Hello @dsuch,

Sorry I did not realize that its 'MsgId' and not 'MsgType' so thanks for that.

Do I just need to set it for the put_mqmd like the following ?

    put_mqmd = pymqi.MD()
    put_mqmd["MsgType"] = pymqi.CMQC.MQMT_REQUEST
    put_mqmd["MsgId"] = x ------> Any string 

If that is the case then the last line is missing from the examples part of the correaltion id.

Thanks in advance.

**Comment by dsuch** [comment]
MQ itself always assigns a MsgId if one is not given explicitly and this is what the examples takes advantage of, i.e. there will be always some MsgId, either an explicit or an implicit one so the get by CorrelId is guaranteed to succeed.

But I can see how this is not necessarily clear unless you are already aware of it so I will re-work the example to employ a user-provided MsgId.

Thanks.

**Comment by dsuch** [comment]
This entirely depends on what your preferences are. The are two schools of thought, both equally correct.

1a. You send a message and make note of its MsgId
1b. Receiver gets the message and writes its MsgId to CorrelId of the response
1c. You wait for a message by CorrelId which per above will be the same as the original MsgId

2a. You generate a unique CorrelId
2b. You send a message filling out the CorrelId field with the value generated in the previous step
2c. Receiver gets the message and writes its CorrelId to CorrelId of the response
2d. You wait for a message by CorrelId which is the one you generated in step 2a

There is no difference in the outcome.

The latter variant may be preferred perhaps if you need control over what CorrelId is, i.e. you prefer to use user_account_id + timestamp for use-case-specific business purposes.

Also, MsgId is not particularly unique, it is the sending queue manager's name + timestamp + a handful of pseudo-random bytes.

Other than that, this is all the same and it's just a matter of preferences and reaching an agreement with the receiving end, for instance, they may already have already implemented a mechanism for responses in MQ integrations that you need to comply with (not sure if it applies to your situation).

**Comment by dsuch** [comment]
Hello @omagdy - I will close the ticket due to inactivity but feel free to reopen if need be. Regards.
