### ISSUE TITLE
Read messages in MQ

### ISSUE THREAD

**Issue by aravazhimp** [dsuch/pymqi#69]
I would like to know if there is an option to read messages from a queue in MQ queue manager?

I do know that we have queue.get(), which would read a message but also removes the message from the queue.  My requirement is to read messages from the queue but it should remain in the queue.

Something like browse message(s) from a queue.

**Comment by dsuch** [comment]
Hello,

yes, this is called message browsing in MQ parlance.

PyMQI is a low-level wrapper around IBM C libraries - you need to check in MQ docs how to do it in C and then apply the same principles to PyMQI based on the usage examples found here:

https://dsuch.github.io/pymqi/examples.html

**Comment by liushengwei** [comment]
Hello , are you Python Version 3.X  ?  or 2.X?

**Comment by Pzixel** [comment]
How exactly do you read the queue? I actually need this behavior with eliminating message when read as well as read beyond sync point. @dsuch could you elaborate, please?

**Comment by dsuch** [comment]
You open the queue in the same manner as usual but you need to specify different open options, i.e. you need to include message browsing flags.

I'm really pressed on time so I won't have means to prepare an example but this is literally what you need to look up in IBM docs: message browsing, open queue for browsing, MQOO.

Then use the correct flags based on examples which already have similar things, just not message browsing as such.

**Comment by Pzixel** [comment]
I think you need this code sample:

```python
queue = pymqi.Queue(qmgr, queue_name,
					pymqi.CMQC.MQOO_FAIL_IF_QUIESCING
					| pymqi.CMQC.MQOO_INPUT_SHARED
					| pymqi.CMQC.MQOO_BROWSE)

browse_first_options = pymqi.GMO()
browse_first_options.Options = pymqi.CMQC.MQGMO_BROWSE_NEXT | ymqi.CMQC.MQGMO_BROWSE_NEXT 

while True:
	md = pymqi.MD()
	message = queue.get(None, md, current_options)
```

**Comment by dsuch** [comment]
Thanks @Pzixel, this looks good - I will close the ticket now.

**Comment by aravazhimp** [comment]
thanks for your reply @dsuch. Thank for your suggestion @Pzixel 
@liushengwei python version is 2.x. PymQI is not supported in Python 3.x, I believe.

I apologise my late reply. Thanks again.

**Comment by dsuch** [comment]
Hello @liushengwei - if you compile PyMQI from a GitHub clone, it will support Python 3.x. 

There will be soon a new release on PyPI with support for 3.x too.

**Comment by aravazhimp** [comment]
thanks. I will try that in my home pc.
