### ISSUE TITLE
Connecting with user and password

### ISSUE THREAD

**Issue by bitfidus** [dsuch/pymqi#7]
Before I realize that the development effort has been moved here to github, I posted this message in launchpad:

> I'm trying to connect to a MQSeries queue that is configured with user/password. I try to connect to the queue using pymqi.cd() UserIdentifier/Password fields but I get this error:
>
> (MQI Error. Comp: 2, Reason 2035: FAILD: MQRC_NOT_AUTHORIZED)
>
>
> Is that the correct way to access that queue? How is it supposed to connect to a queue using user/password?

For connecting to the queue I've got the queue manager name, the channel name, the queue name but also a userid and a password.

Dariusz kindly answer my question:

> ...
> However, please also make sure to read the answers from this ticket  https://answers.launchpad.net/pymqi/+question/102012 - in short, I'm not sure if what you need is possible in Python at all. Username/passwords are usually associated with Java applications and your admins may not be aware of it. In any case, please use GitHub.

So, it seems that java apps introduce some kind of extra-layer of security.
Is it really impossible to connect to a MQSeries queue with userid/password?  What are the fields UserIdentifier/Password good for then? 

Thank you so much

**Comment by dsuch** [comment]
Hello,

just FYI, MQ 8.0 exposed the API necessary to connect with username/password credentials to queue managers whose CONNAUTH definition's CHCKCLNT is not NONE.

This will be released in PyMQI 1.5 in the upcoming week (17 Sep 2015 give or take a few days).

Cheers.
