### ISSUE TITLE
Asynchronous consumption of MQ messages

### ISSUE THREAD

**Issue by gerovermaas** [dsuch/pymqi#70]
Hi,

Using PyMQI, is it possible to implement the asynchronous consumption pattern as described here:
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.dev.doc/q023050_.htm

Thanks,

Gero Vermaas

**Comment by dsuch** [comment]
Hello @gerovermaas - this functionality requires additional MQI calls, namely MQCB and MQCTL, which we don't have implemented in PyMQI.

Please feel free to contact me directly on dsuch@zato.io if you'd like to sponsor their addition.

Regards.

**Comment by lockieRichter** [comment]
Has this functionality been implemented at all?

**Comment by dsuch** [comment]
@lockieRichter If it has not been, in what way can you help to make it happen?

**Comment by lockieRichter** [comment]
That's a good question, I'm not overly familiar with IBM MQ, this is the first time I've had to use it. But I would like to be able to consume the messages on our queue asynchronously.
Is this an open source project?

**Comment by SeyfSV** [comment]
Hi @lockieRichter ,

Please, take a look on [license](https://github.com/dsuch/pymqi/blob/master/LICENSE).

You can use python threads to read/write multiple queues asynchronously or single queue in multiple threads (I can assure that you will receive some boost comparing to single thread), or waiting message in one thread and do some job in another. It works.

If you still want to use MQ native calls with callbacks, than contact to @dsuch (project owner) or find someone who interested in adding this two years old enhancement to project. Also you always can add it to projects by yourself.

**Comment by lockieRichter** [comment]
@SeyfSV do you have an example of using a single queue with multiple threads?

**Comment by SeyfSV** [comment]
@lockieRichter first google's link (search string is `pymqi threads`) points to pymqi's [examples](https://github.com/dsuch/pymqi/blob/master/docs/examples.rst#how-to-correlate-request-and-response-messages-using-correlationid)
