### ISSUE TITLE
The MQCSP structure is sent even if no user or password is passed to connectWithOptions

### ISSUE THREAD

**Issue by JoshMcMQ** [dsuch/pymqi#71]
In the pymqe.c program the following line is called even if no user or password is passed to connectWithOptions.

    cno.SecurityParmsPtr = &csp;

This results in the unmodified MQCSP_DEFAULT MQCSP structure being sent.   We found this to be a problem when using a client security exit IBM provides called mqccred to send the MQCSP structure instead of having pymqi send it.  By default if the exit finds an existing MQCSP structure it does not overwrite it.  There is a FORCE option that allowed us to get it to work, but I think it would be cleaner if pymqi did not send this structure at all if there is no user and password to propagate.

Will you move the above line inside of the if statement, similar to the following:

```
  if(PyDict_Size(user_password)) {

    PyObject *user = PyDict_GetItemString(user_password, "user");
    PyObject *password = PyDict_GetItemString(user_password, "password");

    csp.AuthenticationType = MQCSP_AUTH_USER_ID_AND_PWD;
    csp.CSPUserIdPtr = Py23BytesOrText_AsStringAndSize(user, &csp.CSPUserIdLength);
    csp.CSPPasswordPtr = Py23BytesOrText_AsStringAndSize(password, &csp.CSPPasswordLength);
    if ((csp.CSPUserIdPtr == NULL && user!= NULL) || (csp.CSPPasswordPtr == NULL && password != NULL)) {
      PyErr_Format(ErrorObj, "Failed to parse user/password. Check they are bytes or string.");
      return NULL;
    }
    else {
        cno.SecurityParmsPtr = &csp;
    }
  }
```

**Comment by dsuch** [comment]
@JoshMcMQ - if this proved to get into your way then it sounds the logic that assigns this structure could be rectified indeed, this is a good idea and I will incorporate it. Thanks.

**Comment by dsuch** [comment]
This is done, thanks for suggesting it.
