### ISSUE TITLE
MQCA_VERSION not present in CMQC

### ISSUE THREAD

**Issue by Kulogniot** [dsuch/pymqi#77]
Hello everyone,
Is there a way to get version of MQ installed via pyMQI? (I'm not talking about command level but the detailed version). It should be a part of CMQC but it's not present there (at least in my pymqi module).

I've noticed that MQCA_VERSION module is missing.
Is there some other way to get the MQ version directly via MQI?

@Edit
My pyMQI ver: 1.7.2 (obtained via pip)
Python ver. 2.7.15

**Comment by dsuch** [comment]
You can have this information indirectly as below:

```python
>>> import pymqi
>>> pymqi.__mqlevels__
('5.0', '5.1', '5.2', '5.3', '6.0', '7.0', '7.1', '7.5', '8.0.0', '8.0.1')
>>> 
```

Attribute ```pymqi.__mqlevels__``` is a compile-time constant obtained through MQCMDL_LEVEL_* C constants from cmqc.h.

Now that I ponder your question, I think it will make sense to add something like ```pymqi.__current_mq_level__```, again, it should be a compile-time constant taken from MQCMDL_CURRENT_LEVEL.

As for the missing values - you will find that you can add them easily yourself, if you find anything missing, just send a PR and it will be merged.

As for MQCA_VERSION - it looks to be related to the Inquire Queue Manager call whose version may be different than what PyMQI is compiled with so I am not sure if this is truly what you are looking for?

**Comment by Kulogniot** [comment]
Indeed, the MQCA_VERSION that I was talking about is a part of Inquire QM call, i just wanted to use it but as stated earlier, it's nowhere to be found.

**Comment by dsuch** [comment]
You can find it in /opt/mqm/inc/cmqc.h under Linux or its counterparts on other systems. Feel free simply to add it to CMQC.py and to send a pull request on GitHub so that it can be included for your and other people's benefit.

**Comment by Kulogniot** [comment]
Thanks a lot! It works now :+1: 
I will create a request later as it seems the connection is blocked from my workplace.

**Comment by Kulogniot** [comment]
@dsuch provided a valid solution for this issue
