### ISSUE TITLE
The value of UncommittedMsgs is always no.

### ISSUE THREAD

**Issue by tongwandouxiong** [dsuch/pymqi#81]
@JoshMcMQ Hi,Under what circumstances, UncommittedMsgs will return meaningful values, although the official gives the meaning of this attribute:The number of uncommitted changes (puts and gets) pending for the queue .But I can't get it to return meaningful values, and it's always no

**Comment by JoshMcMQ** [comment]
@tongwandouxiong, An uncommitted message is a message that is put or get under a unit of work (SYNCPOINT) that has not been committed.   MQ returns NO if the count is zero or a number otherwise.

**Comment by JoshMcMQ** [comment]
@tongwandouxiong Good to hear, closing this issue.
