### ISSUE TITLE
pymqi can't be installed

### ISSUE THREAD

**Issue by damonops** [dsuch/pymqi#86]
I install pymqi using 'pip install pymqi' and 'python setup.py install',but both are the same error--"Python.h can not found",the file 'Python.h' is included by pymqe.c.

**Comment by dsuch** [comment]
Hello @damonops - please look up this message "Python.h can not found" in the Internet - it is a rather common error when installing C-based extensions and there is a lot of information on what to do when it happens.

In itself, this is not a PyMQI error hence I am closing the ticket. Thanks!

**Comment by damonops** [comment]
Thanks, sorry I'm not a developer.

**Comment by dsuch** [comment]
No worries - this is fine. I just wanted to say that this error may occur with a lot of libraries, i.e. it is not specific to PyMQI, and other questions/forum posts from the Internet can explain it very well.

**Comment by damonops** [comment]
I have solved the problem, thanks.

**Comment by dsuch** [comment]
For the benefit of other users that may look up the same error message in the context of PyMQI's compilation - can you please link to the answer(s) that helped you?
