### ISSUE TITLE
Support getting PCF messages from a queue into a dict

### ISSUE THREAD

**Issue by colinpaicemq** [dsuch/pymqi#90]
There is support for issuing a PCF command and getting back a PCF response.
MQ also provides messages in PCF format, for example for statistics and events ( such as an MQ Object was changed - and here are the details.
I would like a new ver MQGETPCF which is just like MQGET, but it returns a dictionary of the data instead of the byte string message.

I have some python code which does this, but think it would be better in the base

**Comment by JoshMcMQ** [comment]
@colinpaicemq #75 was opened by @gmmeyer who wanted to parse messages from `SYSTEM.ADMIN.STATISTICS.QUEUE`, so I'm sure he would be happy for this addition.

I noted in #83 is another request related to enhancing the PCF support.  Right now pymqi uses MQAI to interact with the command server, I suggested that moving to direct PCF commands would be a good enhancement as well.

Also somewhat related #88 asked for adding parsing of DLH headers and even has a link to some old unformatted code to do this but as @dsuch mentioned since the time that code was provided things pymqi had changes to support Python 3.

It is great to see someone with your experience and background willing to contribute to this project.  I think to provide your code you just do a pull request and then @dsuch can merge it in.

**Comment by colinpaicemq** [comment]
I started by writing some Python code ( not c code)  to do PCF the hard-way  (building up the data all in python)
Building up the data, doing MQPUT to the command queue, using pymqi.mqget to get the message
and then my code to deconstruct it.  The output of my program is 
'CHANNEL_NAME': 'COLIN', 'CHANNEL_TYPE': 'SVRCONN', 'ALTERATION_DATE': '2018-08-16', 'ALTERATION_TIME': '17.17.06', 'CERT_LABEL': ''...

So it gets the value field type 3501...  and converts it to  MQCACH_CHANNEL_NAME and takes the MQCACH_ off the front to give CHANNEL_NAME.
It also converts numbers to words - such a Channel type you get the word SVRCONN in stead of the number 7.

Ive used it to just read  the event queue - and should work with the SYSTEM.ADMIN.STATS.QUEUE

If people are interested in the alpha code - please contact me on colinpaicemq@gmail.com and I'll send what I have.

regards

Colin

**Comment by SeyfSV** [comment]
Done #202

**Comment by Skyler-Altol** [comment]
@SeyfSV can using this new functionality please be documented in the examples? I am very interested in using this, but have limited experience with programming against MQ. (Though I have extensive Python experience).

**Comment by SeyfSV** [comment]
Hi @Skyler-Altol,
You can use tests as reference: https://github.com/dsuch/pymqi/blob/master/code/tests/test_pcf.py#L169. It does not have connecting and disconnecting, but you can use it from examples.
`Support getting PCF messages from a queue into a dict` is just single `unpack` static method of `PCFExecute` class, that returns parsed dictionary.
```
    def test_arbitrary_message_with_mqcfil(self, value):
        """Test arbitrary message with MQCFIL."""
        message = pymqi.CFH(Version=pymqi.CMQCFC.MQCFH_VERSION_1,
                            Type=pymqi.CMQCFC.MQCFT_USER,
                            ParameterCount=1).pack()
        message = message + pymqi.CFIL(Parameter=1,
                                       Values=value).pack()

        queue = pymqi.Queue(self.qmgr, self.queue_name,
                            pymqi.CMQC.MQOO_INPUT_AS_Q_DEF + pymqi.CMQC.MQOO_OUTPUT)

        put_md = pymqi.MD(Format=pymqi.CMQC.MQFMT_PCF)
        queue.put(message, put_md)

        get_opts = pymqi.GMO(
            Options=pymqi.CMQC.MQGMO_NO_SYNCPOINT + pymqi.CMQC.MQGMO_FAIL_IF_QUIESCING,
            Version=pymqi.CMQC.MQGMO_VERSION_2,
            MatchOptions=pymqi.CMQC.MQMO_MATCH_CORREL_ID)
        get_md = pymqi.MD(MsgId=put_md.MsgId)  # pylint: disable=no-member
        message = queue.get(None, get_md, get_opts)
        queue.close()
        message = pymqi.PCFExecute.unpack(message)

        self.assertTrue(isinstance(message[0][1], list),
                        'Returned value is not list: {}'.format(type(message[0][1])))

        self.assertTrue(len(message[0][1]) == len(value), 'List length is different!')

        for item in message[0][1]:
            self.assertTrue(item in value, '{} value not in values list'.format(item))
            value.remove(item)
```

**Comment by Skyler-Altol** [comment]
@SeyfSV I'm getting NotImplementedErrors thrown when trying to use unpack() with event messages from SYSTEM.ADMIN.COMMAND.EVENT:


`message = pymqi.PCFExecute.unpack(message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Skyler\Desktop\MonitoringTest\venv\lib\site-packages\pymqi\__init__.py", line 2865, in unpack
    raise NotImplementedError('Unpack for type ({}) not implemented'.format(pcf_type))
NotImplementedError: Unpack for type ((20,)) not implemented`

**Comment by SeyfSV** [comment]
20 - `MQCFT_GROUP` and 23 - `MQCFT_INTEGER64` are added 12 days ago (ffebfeaed521c46c1720f09f2300262a3f049c34) and are not in release yet.
Please use version from `master`

**Comment by Skyler-Altol** [comment]
After re-testing with current master, messages are being processed correctly :D While the dict only contains the numerical IDs (so we'd still have to do the translation that Colin mentions above) the actual raw data is there in dict format. This will make it a billion times easier to build the PCF -> JSON converter for the $SYS/MQ topic. (amqsevt sadly can't handle $SYS/MQ messages).

Thanks SeyfSV 🥇

**Comment by JoshMcMQ** [comment]
@Skyler-Altol why do you say `amqsevt` can't handle `$SYS/MQ`?

See my [answer](https://stackoverflow.com/questions/62391346/spring-defaultjmslistenercontainerfactory-dropping-messages-on-jboss-eap-7/62418873#62418873) on Stackoverflow as an example.

**Comment by Skyler-Altol** [comment]
@JoshMcMQ because in the case of the CPU Data, amqsevt reports it as "Application Type", unless you go into the raw C code and edit it. That's why I said above that the $SYS/MQ messages don't "strictly" follow PCF standards because there are ID collisions which should never happen. I have asked one of our IBM Vendors at work to raise it up the flagpole to look into fixing that, and make the fields have unique IDs, therefore solving that problem.

I have some screenshots of the behaviour I'm describing. Will edit them into this post shortly.

**Comment by JoshMcMQ** [comment]
@Skyler-Altol thank you for that info.   I have only used it for the ActivityTrace information and it works OK.  I have run into so seemingly corrupt data being returned that includes 00-1F characters that are not properly escaped in the json output, I raised this and IBM said they will fix it.
