### ISSUE TITLE
Not able to connect to MQ using PYMQI

### ISSUE THREAD

**Issue by yasinmoha** [dsuch/pymqi#93]
I am getting the below error while connecting to IBM MQ using library pymqi.

Its a clustered MQ channel

> pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

Please see my code below.

```
queue_manager = "QMNAME"
channel = bytes(str("CHANNEL_NAME"))
host = "xx.xx.xx.xx"
port = "1800"
queue_name = "QN"
conn_info1 = bytes("%s(%s)" % (host, port))
message = b'{"alert":[{"timestamp":"Wed Jun 27 11:07:37 CDT 2018","shortDescription":"Last 24 hrs Sev 4 Volume Deviation is 84% lower than baseline","alertColor":"red","title":"Sev 4 Volume Deviation"}]}'
```

```
# Message Descriptor
put_mqmd = pymqi.MD()
qmgr = pymqi.connect(queue_manager, channel, conn_info1)
queue = pymqi.Queue(qmgr, queue_name)
```

Getting error at the line below

`qmgr = pymqi.connect(queue_manager, channel, conn_info1)`

**Comment by dsuch** [comment]
Hello @yasinmoha,

the error message, as returned to PyMQI by MQ, states that it is a channel configuration error - what does the administrator of your MQ installation say about it?

Regards.

**Comment by yasinmoha** [comment]
He asked me to check the version of the MQ client which I am running the code on. Both MQ server and MQ client server are 8.0

**Comment by JoshMcMQ** [comment]
I answered this question on StackOverflow about 1 hour ago, I think this can be closed:

[Unable to connect to IBM MQ using pymqi](https://stackoverflow.com/questions/54900223/unable-to-connect-to-ibm-mq-using-pymqi/54901171#54901171)

**Comment by dsuch** [comment]
Thanks @JoshMcMQ - I am closing the ticket in this case.

**Comment by yasinmoha** [comment]
Thank you Josh

**Comment by JoshMcMQ** [comment]
@dsuch on the topic of StackOverflow there is not a [pymqi] tag.  Most of them are tagged [ibm-mq] and [python] currently. Do you think it would be worth it to create one?  I did a quick [search](https://stackoverflow.com/search?q=pymqi+is%3Aquestion) and found 29 questions that contain the string "pymqi", I have enough rep to create one, but if we do we should probably have some info prepared to populate the tag abstract (sort blurb about pymqi) and the tag wiki (more information including links to sites such as https://github.com/dsuch/pymqi/, and any others?)

**Comment by dsuch** [comment]
Thanks @JoshMcMQ - I will prepare the information and ask you for the creation of the tag, this is a good idea.
