### ISSUE TITLE
queue.put error

### ISSUE THREAD

**Issue by liuguiyu** [dsuch/pymqi#94]
with example code, seems I can connect to queue manager. while do queue.put, got error as below:

$ python mq.py
Traceback (most recent call last):
  File "mq.py", line 13, in <module>
    queue.put('Hello')
  File "C:\Python37\lib\site-packages\pymqi\__init__.py", line 1719, in put
    check_not_py3str(msg)  # Python 3 bytes check
  File "C:\Python37\lib\site-packages\pymqi\__init__.py", line 144, in check_not_py3str
    raise TypeError("Python 3 style string found but not allowed here: '{0}'. Convert to bytes.".format(var))
TypeError: Python 3 style string found but not allowed here: 'Hello'. Convert to bytes.

$ python --version
Python 3.7.2

MQ version 9.1

**Comment by dsuch** [comment]
Please send in the full code that you have in addition to the traceback. Thank you.

**Comment by chughts** [comment]
I think that this will be related to you running on Python 3. The way you handle string data for pymqi will vary if you are using Python 2 or 3. I normally add a static method, that does the thinking for me. 

```python
  @staticmethod
  def stringForVersion(data):
    if sys.version_info[0] < 3:
      return str(data)
    else:
      return bytes(data, 'utf-8')
```

**Comment by dsuch** [comment]
Thanks @chughts - with no feedback from @liuguiyu  I think we can close the ticket now.

**Comment by JoshMcMQ** [comment]
@dsuch, based on the comment from @chughts, if a app was running fine under Python 2 and then later upgraded to Python 3 they would break?

Can the logic used by @chughts be embedded in the pymqi methods?

On one hand it does not break existing applications using Python 2.

On the other hand it means that anyone moving an app from Python 2 to 3 needs to change the app to account for the "string" difference.

What are your thoughts.

**Comment by dsuch** [comment]
@JoshMcMQ - it may be a good idea to have some kind of a conversion layer for each operation.

What @chughts has will usually work for sure but then again, MQ supports so many encodings that UTF-8 will not always do the trick, I am thinking about EBCDIC in particular.

Perhaps simply a startup parameter will suffice, e.g. 'default_encoding' and then it would be up to user to make sure either they convert data themselves or they leave it up to PyMQI.

As for whether an app would continue to work or not on Python 2 vs. 3 - this would depend on how it was designed. Many people do not want to think about such differences and I recognize that the library could handle it for them.

**Comment by piotr-gomola** [comment]
I'm using Python 3.5.3

With IBM MQ docker dev image:
https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md

In [28]: getq.put(bytes('Hello from Python!', 'utf-8'))
---------------------------------------------------------------------------
MQMIError                                 Traceback (most recent call last)
<ipython-input-28-74ab1a3e4521> in <module>
----> 1 getq.put(bytes('Hello from Python!', 'utf-8'))

/mnt/projects/das/tag/env-srv-tagger-gateway/lib/python3.5/site-packages/pymqi/__init__.py in put(self, msg, *opts)
   1725         if not self.__qHandle:
   1726             self.__openOpts = CMQC.MQOO_OUTPUT
-> 1727             self.__realOpen()
   1728         # Now send the message
   1729         rv = pymqe.MQPUT(self.__qMgr.getHandle(), self.__qHandle, m_desc.pack(),

/mnt/projects/das/tag/env-srv-tagger-gateway/lib/python3.5/site-packages/pymqi/__init__.py in __realOpen(self)
   1630                           self.__qDesc.pack(), self.__openOpts)
   1631         if rv[-2]:
-> 1632             raise MQMIError(rv[-2], rv[-1])
   1633         self.__qHandle = rv[0]
   1634         self.__qDesc.unpack(rv[1])

MQMIError: MQI Error. Comp: 2, Reason 2085: FAILED: MQRC_UNKNOWN_OBJECT_NAME

How can i fix this?

**Comment by chughts** [comment]
@piotr-gomola I don't think this is the same error for which this now closed issue was raised. 

Having said that I suspect that you are using sample pymqi code where 

`queue_name = 'TEST.1'`

but in the docker image

> The following queues and topics are created:
> 
> DEV.QUEUE.1
> DEV.QUEUE.2
> DEV.QUEUE.3
> DEV.DEAD.LETTER.QUEUE - configured as the Queue Manager's Dead Letter Queue.
> DEV.BASE.TOPIC - uses a topic string of dev/.

**Comment by piotr-gomola** [comment]
You'r right. I was my fault - misconfiguration.

**Comment by piotr-gomola** [comment]
*It was

**Comment by akhiilkasare** [comment]
> I think that this will be related to you running on Python 3. The way you handle string data for pymqi will vary if you are using Python 2 or 3. I normally add a static method, that does the thinking for me.
> 
> ```python
>   @staticmethod
>   def stringForVersion(data):
>     if sys.version_info[0] < 3:
>       return str(data)
>     else:
>       return bytes(data, 'utf-8')
> ```

I are using python 3.7.4 and MQ version 9.2 can you share the code snippet and in which file we have to make the changes
