### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by Pzixel** [dsuch/pymqi#97]
Related to #96 

I apologise for any inconvinience, I didn't mean anything wrong to you. I didn't ask anything or `Gimme what I need`. I just desribed my user story and was intended you may see if it's valuable to be implemented.

I never thought someone owe me anything, I don't ask for free help, and I never wanted to harass you in any way. I might use wrong words when I sent the issue, but you locked the conversion so I had no way to edit issue to reflect what I really meant.

What I really meant is that currently `message` if of type `str` when it'd better should be object with `header` and `body` parts.

I aplogise again and hope won't react this much on people who didn't think enough on correct wording. I agree that I could and should, but I didn't really mean anything bad.

**Comment by dsuch** [comment]
Thanks @Pzixel - in that case everything is good and let's follow up in the original ticket on the technical matters. Thanks again.
