### ISSUE TITLE
pymqi on macos Library not loaded: @rpath/libmqic_r.dylib

### ISSUE THREAD

**Issue by acabrele** [dsuch/pymqi#99]
I'm trying to set up IBM MQ and pymqi on my macbook. MQ is done via docker, no issues there. I've installed the IBM MQ from https://developer.ibm.com/messaging/2019/02/05/ibm-mq-macos-toolkit-for-developers/ and followed the instructions. I pip installed pymqi with no issues after that.

But when simply running import pymqi I get

`ImportError: dlopen(/Users/.../Library/Python/2.7/lib/python/site-packages/pymqi/pymqe.so, 2): Library not loaded: @rpath/libmqic_r.dylib`

I've been on this for a day now trying all manner of linking, copying, permissions of files, setting env vars etc. No suggestions seem to work despite it being quite a common issue (looking at google results at least).

libmqic_r.dylib is available in two locations including /opt/mqm/lib64

**Comment by dsuch** [comment]
Hello @acabrele,

can you run the Mac equivalent of 'ldd pymqe.so' to find out which exact libraries it requires?

I am not sure if Mac has 'ldd', perhaps it does?

**Comment by acabrele** [comment]
pymqe.so:
	@rpath/libmqic_r.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)

**Comment by dsuch** [comment]
Ah, I thought it would return absolute paths to check - I do not have Mac and I am not familiar with ```@rpath```, maybe other Mac users will know?

**Comment by chughts** [comment]
I think that this question as also been asked on Stack - https://stackoverflow.com/questions/55240523/pymqi-on-macos-library-not-loaded-rpath-libmqic-r-dylib/55240744#55240744

and suspect that as a newbie to development on a mac all that is missing is a c / c++ compiler which is most easily obtained by installing Xcode.

**Comment by chughts** [comment]
Although on closer inspection it could be related to `export DYLD_LIBRARY_PATH` having multiple paths when only the mac-toolkit /lib64 is required.

**Comment by acabrele** [comment]
Hi Thanks yes I'm DL xcode now... wifi is terrible.  Multiple paths weren't there originally, I built them up while trying to resolve - at first only had the ones in the guide.

**Comment by dsuch** [comment]
Hello @acabrele,

can you please tell me what the current status is?

I am not sure if everything is resolved already by following hints from @chughts?

**Comment by acabrele** [comment]
Hi, i'm afraid this has not resolved it.  I tried updating the references in those files with install_name_tool which has got me past those initial errors but I'm doubtful it is a solution given @rpath us used everywhere

**Comment by dsuch** [comment]
OK, so just to confirm it - given a clean Mac environment, without any modifications, changes or customisations that you might have introduced, even accidentally, and after following documentation from IBM and PyMQI, you cannot run 'import pymqi', is that correct?

I ask because install_name_tool is not mentioned anywhere in either of these places so if it is a more involved matter of setting up a development environment on Mac in the first place, then I am afraid this is not the best place to inquire about it and StackOverflow would be indeed a better one.

**Comment by chughts** [comment]
You will need to uninstall PyMQI. Install all the pre-reqs - Xcode, Toolkit, set Paths etc. then install pip install PyMQI. Its easier if you are using  virtualenv so you don't pollute the global python space.

**Comment by acabrele** [comment]
@dsuch - I only introduced install_name_tool when attempting to fix.  Previous to that I followed the instructions provided.  It wasn't a completely clean OS, but the pre-reqs were all newly installed.

I just tried remove and reinstall via pip and still no luck.

I can do a linux virtual but then probably won't repro these issues.

**Comment by acabrele** [comment]
@chughts regarding 
"In the question you say 'libmqic_r.dylib is available in two locations including /opt/mqm/lib64' What is the other location? Are they the same file? "

I just created a link to the same file, there were posts about expectations in the install being under /opt/mqm.  Again this was all part of trying to make it work.

I'm going to roll back everything I can and try again

**Comment by chughts** [comment]
As a belt & braces tactic it might be worthwhile also setting `MQ_INSTALLATION_PATH` also. Shouldn't be required, but won't do any harm neither.

**Comment by acabrele** [comment]
Yeah I had set that too, just checked. Tomorrow will work on starting from scratch

**Comment by acabrele** [comment]
I managed to get this done just now, cleaned everything up and started again
1) installed xcode
2) Downloaded IBM MQ Client from [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/mactoolkit/)
3) Unzipped to /opt/mqm
4) export DYLD_LIBRARY_PATH=/opt/mqm/lib64
5) Added /opt/mqm/bin and /opt/mqm/samp/bin to paths
6) ran dspmqver which gives this output:
`Name:        IBM MQ
Version:     9.1.1.0
Level:       p911-L190205
BuildType:   IKAP - (Production)
Platform:    IBM MQ for macOS
Mode:        64-bit
O/S:         Darwin 18.2.0
InstName:    MQNI09010100
InstDesc:    IBM MQ V9.1.1.0 (for Developers)
Primary:     No
InstPath:    /opt/mqm
DataPath:    /Users/.../IBM/MQ/data
MaxCmdLevel: 911
LicenseType: Developer`
7) sudo pip install pymqi
8) import pymqi fails with Library not loaded: @rpath/libmqic_r.dylib
9) try export MQ_INSTALLATION_PATH=/opt/mqm
10) import pymqi same error

What did I miss?

**Comment by dsuch** [comment]
I pushed a commit thanks to which during compilation of PyMQI you will have information what libraries and directories were used, such as below.

You need to build or install PyMQI from a git checkout, this is not on PyPI.

```bash
$ python setup.py build
Building PyMQI client mode 64bits
Using library_dirs:`['/opt/mqm/lib64']`, include:`['/opt/mqm/inc']`, libraries:`['mqic_r']`
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pymqi
copying pymqi/__init__.py -> build/lib.linux-x86_64-2.7/pymqi
copying pymqi/CMQC.py -> build/lib.linux-x86_64-2.7/pymqi
copying pymqi/CMQCFC.py -> build/lib.linux-x86_64-2.7/pymqi
copying pymqi/CMQXC.py -> build/lib.linux-x86_64-2.7/pymqi
copying pymqi/CMQZC.py -> build/lib.linux-x86_64-2.7/pymqi
running build_ext
building 'pymqi.pymqe' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pymqi
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYQMI_BINDINGS_MODE_BUILD=0 -I/opt/mqm/inc -I/usr/include/python2.7 -c pymqi/pymqe.c -o build/temp.linux-x86_64-2.7/pymqi/pymqe.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pymqi/pymqe.o -L/opt/mqm/lib64 -lmqic_r -o build/lib.linux-x86_64-2.7/pymqi/pymqe.so

$
```

**Comment by chughts** [comment]
What do you have in /opt/mqm/lib64

I have:

> libcurl.dylib		libmqe_r.dylib		libmqm_r.dylib
> libedit.so		libmqecs_r.dylib	libmqmcs_r.dylib
> libimqb23gd_r.dylib	libmqic_r.dylib		libmqmzse.dylib
> libimqc23gd_r.dylib	libmqicb_r.dylib	libmqxzu_r.dylib
> libmqcxa64_r.dylib	libmqiz_r.dylib		libmqz_r.dylib
> libmqcxa_r.dylib	libmqjx_r.dylib		libmqzsd_r.dylib
> libmqdc_r.dylib		libmqjxx_r.dylib

**Comment by acabrele** [comment]
Will try the build this morning.

In /opt/mqm/lib64 `i have the same list

**Comment by acabrele** [comment]
`Building PyMQI client mode 64bits
Using library_dirs:`%s`, include:`%s`, libraries:`%s`
running build
running build_py
creating build
creating build/lib.macosx-10.14-intel-2.7
creating build/lib.macosx-10.14-intel-2.7/pymqi
copying pymqi/__init__.py -> build/lib.macosx-10.14-intel-2.7/pymqi
copying pymqi/CMQC.py -> build/lib.macosx-10.14-intel-2.7/pymqi
copying pymqi/CMQCFC.py -> build/lib.macosx-10.14-intel-2.7/pymqi
copying pymqi/CMQXC.py -> build/lib.macosx-10.14-intel-2.7/pymqi
copying pymqi/CMQZC.py -> build/lib.macosx-10.14-intel-2.7/pymqi
running build_ext
building 'pymqi.pymqe' extension
creating build/temp.macosx-10.14-intel-2.7
creating build/temp.macosx-10.14-intel-2.7/pymqi
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DPYQMI_BINDINGS_MODE_BUILD=0 -I/opt/mqm/inc -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pymqi/pymqe.c -o build/temp.macosx-10.14-intel-2.7/pymqi/pymqe.o`

After that there are also a bunch of warnings like 
`pymqi/pymqe.c:1277:18: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
              if(!compCode == MQCC_OK) {`

**Comment by acabrele** [comment]
OK I updated that line to 
`print("Using library_dirs:%s, include:%s, libraries:%s" % (library_dirs,include_dirs,libraries))`
and get
Using library_dirs:['/opt/mqm/lib64'], include:['/opt/mqm/inc'], libraries:['mqic_r']

**Comment by chughts** [comment]
Are you still getting ?

`ImportError: dlopen(/Users/.../Library/Python/2.7/lib/python/site-packages/pymqi/pymqe.so, 2): Library not loaded: @rpath/libmqic_r.dylib  `

Your paths look ok, DYLD_LIBRARY_PATH, looks ok. But either `libmqic_r.dylib` not being found, or it is not being read. 

What version of Mac iOS are you on? I am running on 10.14

Run `ls -l  /opt/mqm` and `ls -l /opt/mqm/lb64/libmqic_r.dylib` to verify file permisions. I get 

> -r-xr-xr-x  1 soheelchughtai  staff  16864  9 Nov 17:54 /opt/mqm/lib64/libmqic_r.dylib

**Comment by acabrele** [comment]
Yes still getting same error.  Version is 10.14.3.

I opened permissions up to check that before, currently drwxrwxrwx on everything (-rwxrwxrwx on libmqic_r.dylib)

pip freeze gives me pymqi==1.9.2

Is there a reason your python 2 and 3 versions are different?  I'm runnin 2.7 but pymqi 1.9.2 not 1.8.0

**Comment by chughts** [comment]
I installed a while a go, and tested some pymqi installation updates in my python 3 environment.

**Comment by acabrele** [comment]
freeze has many:
altgraph==0.10.2
astroid==1.6.5
backports.functools-lru-cache==1.5
bdist-mpkg==0.5.0
bonjour-py==0.3
configparser==3.7.2
enum34==1.1.6
futures==3.2.0
isort==4.3.4
kafka-python==1.4.4
lazy-object-proxy==1.3.1
macholib==1.5.1
matplotlib==1.3.1
mccabe==0.6.1
modulegraph==0.10.4
numpy==1.8.0rc1
pika==0.13.1
py2app==0.7.3
pylint==1.9.4
pymqi==1.9.2
pynuodb==2.3.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2018.9
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.4.1
wrapt==1.11.1
xattr==0.6.4

**Comment by chughts** [comment]
I would recommend that you install virtualenv, which you can do with `pip install virtualenv`, then create and start / source a virtual env, so that nothing else can interfere.

**Comment by acabrele** [comment]
Legend... that worked... I didn't know about virtualenv so thanks for that.

I've wasted so long on this I'm completely not interested in finding out what the conflict is...

**Comment by guimarc-br** [comment]
Hello Guys.

@acabrele  I am spend too much time on that as well... with the same problem that you reported .  I followed your steps but not fixed that yet.....
I am running on MAC OS MOJAVE and running a project on PYTHOn under  Intellij.
1 - Installed XCODE
2 - Created a ENV from scratch
3 - Download and unziped the toolkit from mac to OPT/MQM
4 - Performed the Export for MQ installation and DYL .
5 - Install the pymqi
But go the same error.

Please help me on that.. I really appreaciated

**Comment by acabrele** [comment]
Have you configured intellij to use virtualenv for the project?  Thats the only thing I can think... I was new to this and it was the separate environment that fixed it

**Comment by guimarc-br** [comment]
Have you created the virtual environment or PIPENV environment ? Because i have created from scratch the Virtual Environment
